### ISSUE TITLE
Add support for additional JWT claims

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#1]
Should have optional support for addition claims (sub, aud, etc). Have an option for using pyjwt leeway as well when decoding tokens

**Comment by aguegu** [comment]
Nice job. I came as a flask-jwt user. 

Despite support for additional claims, how to delete the default claims? like `jti`, `user_claims`, for small projects, I do not need any of that.

**Comment by vimalloc** [comment]
Thanks for the feedback! Currently there isn't a way to do that, but I agree that this would be a good feature to have. I have a couple ideas for how to do this rolling around in the back of my mind. Let me think on that some, and I'll propose an API how this might look.

If no serious issues are ran into, I think I could find the time to address this within a few days.

Cheers!

**Comment by vimalloc** [comment]
(some rambling incoming, this post is largely for my own benefit, so I can get my thoughts consolidated)


This might be more difficult then I originally thought. For deleting default claims in the jwt, the problems boils down to two big parts:

1. How do you disable a claim
2. What do you do if a function is called or configuration value is set which requires one of the disabled claims.

Starting with number 2, as I think this will be the primary factor in how this feature is implemented. Lets look at some of the claims we put in the token (both in RFC 7519 spec and outside of the spec) and how they are used.

* ```identity```:
  * Returns the identity of a jwt via ```get_jwt_identity()```
* ```fresh```:
  * Allows marking endpoints as fresh with ```@fresh_jwt_required```
* ```type```:
  * Allows for making separate access and refresh tokens, and endpoints to match them via ```@jwt_required``` vs ```@jwt_refresh_token_required```
* ```jti```:
  * Used as a key for revoking tokens when ```app.config['JWT_BLACKLIST_ENABLED'] = True```
* ```user_claims```
  * Used to put custom claims into a token via ```@jwt.user_claims_loader``` and retrieved via ```get_jwt_claims()```. These are put into a seperate claim on the JWT to prevent key name collisions with our other custom keys we put in the jwt (such as fresh, type, identity).

Currently, when a jwt is decoded, we verify that all of the above claims are in the token, and the rest of the extension uses those claims as needed. If we remove one of the claims, it will remove some functionality from the extension, and we would need a way to signal the user of this if they attempted to use said functionality. For example, if a user disabled the ```type``` claim, and attempted to use ```@jwt_refresh_token_required```, I would like them to receive an exception along the lines of:

> Error: You are attempting to use jwt_refresh_token_required when the 'type' claim is disabled. To use this functionality, you must not disable the 'type' claim, and discard any current JWTs you have generated

compared to something like

> KeyError: 'type'

A way to do this might be to move the tokens from a straight python dictionary into a Tokens helper object, that raises good exceptions if a claim is attempted to be accessed that has actually been disabled. I haven't spent too much time thinking about this yet though, just my first thoughts.

This leads us into other problem, how do you disable a claim? We could expose the
```jwt_encode``` and ```jwt_decode``` methods to the user via a decorator, but the user would need to know the internal workings of this extension in order to safely re-write these functions in such a way that didn't cause problems when using other parts of the extension, such as ```@jwt_refresh_token_required``` or ```@fresh_jwt_required```. It would be totally do-able, and the easiest solution for me to implement, but it would also be the solution that would probably cause the most issues for a someone attempting to use it.

An alternate way would be to have a list of claims for our JWTs in the app.config, some functions to set the default values of the claims for a JWT, and decorators to override the default functions. We would need to have a way for various functions in flask-jwt-extended to see if a claim on a token was disabled or not too.

One problem I could see that would be common to any solution is what happens if you disable a claim, and want to re-add it later. If we initially have  ```fresh``` disabled, but
later decide that we want to use ```@fresh_jwt_required``` endpoints, we would need to re-enable the ```fresh``` claim. But in doing so, everyone who currently has a JWT now has a token that is missing that claim, and this extension would need to know how to handle that, or reject all of the existing JWTs as invalid (which probably isn't desired). This could get complex pretty quick.

Which leads us to one final consideration: this might add a decent complexity increase in the extension, and the less complex this extension is, the less chance there is for bugs (which, when working with an extension like this, any bug could have critical consequences). Is the ability to make a JWT a few bytes smaller worth this increase in complexity?

Anyways, there is my rambling of initial thoughts. I'll continue to think on this and update this ticket as needed.

**Comment by vimalloc** [comment]
Last thought:

The lowest hanging fruit for me would be to just expose the encode_jwt and decode_jwt methods, and trust that anyone using these would not attempt to use any functions/settings that require claims where were removed from the JWT (and expect to get cryptic trackbacks if they do). You would need to override both the encode (for making new jwts) and decode (for skipping verification of expected claims) for this to work. Do you have any thoughts about this?

**Comment by aguegu** [comment]
somehow I am under the impression that you over-extend the jwt features, which would lead this plugin too complex to blend in.

**Comment by vimalloc** [comment]
It is a very opinionated plugin for sure. Blacklisting, token fershness, and refresh tokens are all outside of the plain JWT specs, and need some additional work to implement them (for better or worse, depending on your use case). That said, I do think there are use cases where all these features are good to have, but obviously not every use case will be.

If this ends up being too opinionated for your use cases, I do suggest looking at pyjwt directly. They have a very easy to use API for handling per spec JWTs. Throw a simple endcode/decode method together, and add a jwt_required decorator and you are good to go. 

Per this issue, I don't think I want to add the ability to remove claims from JWTs. It would add a bunch of edge cases in the rest of the code, which I think would be bad in an extension of this nature. 

I hope you find something that works great for your application!

**Comment by aguegu** [comment]
Thanks. I would look into pyjwt, which I believe got all the core functions. My main applications focus on fast prototyping. To extend all the options are of lower priority for now.

**Comment by vimalloc** [comment]
In case you are still interested in this, or someone else stumbles upon this, let me introduce Flask-JWT-Simple (https://github.com/vimalloc/flask-jwt-simple). It is a toned down version of this extension with all the opinionated stuff needed for the extra features ripped out. This new extension allow you full control over claims when creating JWTs, and places no restrictions on what claims need to be in consumed JWTs.

If there are features missing from the simple variant of this extension that you would like to see, I would be more then happy to port them over. The two that I could see being helpful right off hand is JWT blacklisting and JWT claim verification. 

Cheers.
