### ISSUE TITLE
how to use different file 

### ISSUE THREAD

**Issue by BumwooPark** [vimalloc/flask-jwt-extended#101]
hi  i'm using flask_jwt_extended . 

 i want to using jwt = JWTManager() 

but i make different file  name is route . 

so i using current_app as app 

but i see RuntimeError: Working outside of application context.

how to do i use ?? 

thanks

**Comment by vimalloc** [comment]
Your question isn’t very clear. It sounds like you are trying to use the factory pattern, in which case you could use ‘’’with app.app_context():‘’’ to manually create your own context, or use ‘’’@app.before_first_request’’’ and put any setup code that requires an application context in there. You can also use blueprints (http://flask.pocoo.org/docs/0.12/blueprints/) in conjunction with the factory pattern to good effect. 

You may want to read up on the application context more here: http://flask.pocoo.org/docs/0.12/appcontext/

**Comment by BumwooPark** [comment]
thank u for reply 
I think it is a lack of understanding application context 😅
