### ISSUE TITLE
JWT_ACCESS_COOKIE_PATH = /api/ and logout endpoint at /token/remove

### ISSUE THREAD

**Issue by alexschrod** [vimalloc/flask-jwt-extended#102]
Hey, I'm just curious about something. In your [JWT in Cookies](https://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html) page, you set `app.config['JWT_ACCESS_COOKIE_PATH'] = '/api/'`, but then later, you have this bit of code:

```
@app.route('/token/remove', methods=['POST'])
@jwt_required
def logout():
    ...
```

Is it just me, or will the `/token/remove` endpoint never satisfy the `@jwt_required` when `JWT_ACCESS_COOKIE_PATH` is set to `/api/`?

**Comment by vimalloc** [comment]
You are absolutely correct, good catch! Do you want to submit a pull request to fix that documentation? Or I can update the docs later today. 

Cheers 👍

**Comment by alexschrod** [comment]
I'd be happy to help, but I actually don't know what the solution is to that conundrum. I suppose putting the `/token/*` endpoints under `/api/` is the easiest solution? What do you have in mind?

**Comment by vimalloc** [comment]
That’s seems totally reasonable to me. I think we did something similar in our production site.

**Comment by mbosoft** [comment]
Your route is /protected but your JWT_ACCESS_COOKIE_PATH is /api/. That will prevent the cookie from being sent to that endpoint. Either change the endpoint to /api/protected, or change the cookie path to just /
