### ISSUE TITLE
Instead of Refresh Tokens use freshness date?

### ISSUE THREAD

**Issue by dunkmann00** [vimalloc/flask-jwt-extended#107]
Instead of using multiple kinds of tokens (access & refresh), would it not be easier to just add another claim to the access token that stored the freshness date? This way one would not need as many endpoints to handle the various types of login that you describe in the documentation (and I think it would simplify flask-jwt-extended slightly as well).

So for example, rather than just setting fresh as a True or False value, you could set a timedelta for it and add that onto the current time, similar to the other time values in the JWT payload. The decorators in flask-jwt-extended could check for freshness by examining the fresh date. Doing this would eliminate the need for a separate token.

What do you think? I didn't want to make this suggestion too long for fear of it becoming confusing. But if anything I wrote is unclear please let me know!

**Comment by vimalloc** [comment]
That's an interesting idea. It would be more limited in a few use cases, specifically blacklisting. If you could use an access token to create an access token, it could become difficult to actually blacklist a compromised token, as each token can keep generating more and more tokens, compared to a refresh token that can only (in the examples at least) be generated with a valid username and password. But that probably isn't a huge deal, and could be worked around on a per application basis. 

Without thinking about it too much, I think this could work. The big issue I see is that I don't want to break compatibility with this extension if this change was introduced. I think this extension is flexible enough that the change could be made without breaking existing code bases. My first though would be to update the `fresh` kwarg to take either a boolean or a datetime value, have the view decorators check the datetime value if `fresh` isn't a boolean value, and in the users codebase they could replace `@jwt_refresh_token_required` with `@jwt_required` and generate new access tokens in that endpoint as needed.

I don't have a lot of time to work on this right now, but if you wanted to give it a shot, I would be happy to look over it and see if it was something that could be merged into this extension.

Cheers.

**Comment by dunkmann00** [comment]
I'd be glad to. However, I don't think it is necessary to have the access token be used to create another access token. The fresh date could be short (i.e. 15 mins, like the current default token expiration) and the expiration date be long (i.e. 30 days, like the current refresh token token expiration). This way if the user tries to access anything that is critical or more secure they would need to login again after 15 minutes. But if they are not doing anything like that then they won't be bothered with re-logging in for quite some time.

**Comment by vimalloc** [comment]
Ok, yeah that makes sense. 

I don't want to remove the refresh tokens from this extension (due to breaking changes) but if you want to work on adding the token freshness as a date, I would be down for incorporating that into flask-jwt-extended.

Cheers.

**Comment by dunkmann00** [comment]
Awesome, I'll see what I can work up.

And I understand, I feel like that does make more sense to keep them.

**Comment by vimalloc** [comment]
Released in version 3.5.0. Thanks for contributing!
