### ISSUE TITLE
Why revoke tokens functions are no more available ? 

### ISSUE THREAD

**Issue by zmellal** [vimalloc/flask-jwt-extended#109]

**Comment by vimalloc** [comment]
I’m assuming you are referring to how token revoking used to work before the 3.0.0 release? Basically, they way it was setup previously was super brittle and prone to breaking in different use cases. The 3.0.0 update puts a bigger burden on the developer, but is also much more generalized and can be used just about anywhere. You can read this for additional information: https://github.com/vimalloc/flask-jwt-extended/releases/tag/3.0.0

**Comment by zmellal** [comment]
Thank you for your explanations. I close the issue. 
@gbossert please take a look when you have time.
