### ISSUE TITLE
Understanding how to use CSRF tokens via cookies for `jwt_refresh_token_required` route

### ISSUE THREAD

**Issue by JulieRossi** [vimalloc/flask-jwt-extended#111]
Hi @vimalloc ,

First, thanks for this great library !

I just have one question, I can't figure out how to properly use a `jwt_refresh_token_required` decorated route when setting CSRF tokens in cookies.

To be more specific, I set:
- `JWT_COOKIE_CSRF_PROTECT = True`
- `JWT_CSRF_IN_COOKIES = True`
- `JWT_ACCESS_CSRF_COOKIE_NAME = 'csrf_access_token'`
- `JWT_REFRESH_CSRF_COOKIE_NAME = 'csrf_refresh_token'`

When I use my `/login` route and then some `jwt_required` decorated data, everything works fine.
But when my acess token expires, I post on my `jwt_refresh_token_required` decorated route but there I get `"Missing CSRF token in headers"` 401 error.

Looking at the code, I can't figure out how to use CSRF token from cookie in this refresh route since the only way to get the token is from headers : https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/view_decorators.py#L176

Is there a way for this decorator to use directly CSRF token from cookies or do I need to explicitly pass the CSRF token in the header when making my http post ?

(I'm using version 3.4.0)

**Comment by vimalloc** [comment]
By default you can grab that double submit token by using JavaScript to access the  ‘csrf_refresh_token’ cookie (that name can be controlled via the ‘JWT_REFRESH_CSRF_COOKIE_NAME’ option). 

You do not have to send that in another cookie though, you can use the ‘JWT_CSRF_IN_COOKIES’ option to disabled setting those additional cookies, and instead send the csrf toke to the frontend in your login payload. There is an example of how to do that on the cookies documentation page: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

**Comment by JulieRossi** [comment]
Ok, I don't really know about CSRF so thank you for the explanation !
