### ISSUE TITLE
Add get_csrf_token to the API

### ISSUE THREAD

**Issue by farshiana** [vimalloc/flask-jwt-extended#112]
Hey,

You mention get_csrf_token in your [JWT in Cookies](https://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html) page, but it isn't in the API. I know it is available via utils but do you plan on adding it? 

Btw, thanks for the lib :)

**Comment by vimalloc** [comment]
Whoops! That should absolutely be exported and part of the API. I'll get a new version pushed out with that fixed tonight.

Thanks! :+1:

**Comment by farshiana** [comment]
Awesome, thanks!

**Comment by vimalloc** [comment]
Released in 3.5.1. Cheers!
