### ISSUE TITLE
Missing options in documentation

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#12]
These optionss are all available in the code and usable in app.config, but are not in the options page for the documentation. 

```
COOKIE_SECURE = False
ACCESS_COOKIE_NAME = 'access_token_cookie'
REFRESH_COOKIE_NAME = 'refresh_token_cookie'
ACCESS_COOKIE_PATH = None
REFRESH_COOKIE_PATH = None
```

**Comment by rlam3** [comment]
@vimalloc could you provide a case where we would be could use access/refresh cookies? Thanks!

**Comment by vimalloc** [comment]
Sure. Check out this for a good write up of why you might want to store your JWTs in cookies:
https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

And here to see how this would look in flask_jwt_extended:
http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

Tomorrow I'll make sure all the various options you can set when using cookies are documented, as well as adding a logout endpoint to the documentation.

Cheers!

**Comment by rlam3** [comment]
@vimalloc You are awesome! 

Cheers!
