### ISSUE TITLE
Don't set PROPAGATE_EXCEPTIONS config setting

### ISSUE THREAD

**Issue by decaz** [vimalloc/flask-jwt-extended#122]
I think it's bad idea to change application config implicitly. I don't want exceptions to be raised - Flask already logs them for me. Is such a behavior really necessary and this extension can't work without changing my application config?

**Comment by vimalloc** [comment]
I don't recall why this was set initially, I think it was something to do with inter-operability with other flask extensions (such as restplus, etc). I agree that setting it here probably is not the correct thing to do. Would you like to make a pull request to remove it?

**Comment by decaz** [comment]
@vimalloc I have created the PR #124.

**Comment by vimalloc** [comment]
The past couple days have been crazy at work. I will get this reviewed this tonight.

**Comment by decaz** [comment]
@vimalloc can the version `3.7.1` be released now?

**Comment by vimalloc** [comment]
done

**Comment by decaz** [comment]
@vimalloc thanks!
