### ISSUE TITLE
No theme flask

### ISSUE THREAD

**Issue by sanfx** [vimalloc/flask-jwt-extended#125]
I believe you forgot to bundle the theme along:

```
$ make clean && make html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created

Theme error:
no theme named 'flask' found (missing theme.conf?)
make: *** [html] Error 2
```

**Comment by vimalloc** [comment]
The theme is in the `requirements.txt` (specifically `Flask-Sphinx-Themes`). Make sure you have your virtualenv activated and the requirements installed, and that command should work as expected.

Cheers.
