### ISSUE TITLE
User loader error handler not triggering

### ISSUE THREAD

**Issue by fgblomqvist** [vimalloc/flask-jwt-extended#127]
This error handler:
https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/jwt_manager.py#L117
Is not triggering for me. Instead, a normal exception is raised (`UserLoadError`).

My app uses blueprints and app factory and adds in flask-jwt-extended like this:
```
from my_app.auth import jwtm
jwtm.init_app(app)
```
and in auth.py:
```
jwtm = JWTManager()
```

Let me know if there is any info I can provide!

EDIT: It is more odd than I thought. I am not getting this error locally (got confused why my test suite wasn't catching it but I then discovered it is because it is not happening locally, at least not in the scenario I am testing). Will try to replicate it. Noticed another error in the docs though. It says that the default user loader error loader returns a 400 error. It actually returns a 401 error, as mentioned in the section below. (http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.user_loader_error_loader)

**Comment by vimalloc** [comment]
What version of flask-jwt-extended are you using, and are you using any other extensions like flask-restful, flask-restplus, etc? Perhaps it is related to the propagate_exceptions change in version 3.7.1? Could you try adding `PROPAGATE_EXCEPTIONS = True` in your flask configuration and see if that helps?

Good catch with the 400 vs 401. Would you like to make a pull request to fix that?

**Comment by fgblomqvist** [comment]
Yes, I can certainly make that PR (I'll probably get to it tomorrow).

And so far I haven't been able to reproduce it locally or on production, despite mirroring the conditions. Maybe it's because I went ahead and set my own error loader. But that doesn't really interfere with the errorhandler though so not sure. Will try a bit more tomorrow, otherwise I'll let it rest until it happens again.

These are the versions I am using:
```
        'Flask-Caching==1.3.3',
        'Flask-Cors==3.0.3',
        'Flask-JWT-Extended==3.6.0',
        'Flask-Migrate==2.1.1',
        'Flask-RESTful==0.3.6',
        'Flask-Rollbar==1.0.1',
        'Flask-SQLAlchemy==2.3.2',
        'Flask==0.12.2'
```
Just realized I am a bit outdated on Flask-JWT-Extended, will update that tomorrow as well!

**Comment by vimalloc** [comment]
Just wanted to check up on this and see if the issue is still persisting or if this can be closed?

Thanks!

**Comment by fgblomqvist** [comment]
I'll close it, haven't ran into it again.
