### ISSUE TITLE
jwt_optional does not give None, instead the old token

### ISSUE THREAD

**Issue by gaara4896** [vimalloc/flask-jwt-extended#132]
```
@api.route("/")
class Payment(Resource):

    @jwt_optional
    @api.header("Authorization", "access token", required=False)
    @api.doc(payment_fields)
    @api.expect(payment_fields)
    def post(self):

        username = get_jwt_identity()
```

This endpoint are jwt optional, which can be either identify with access token or email alone. This endpoint are use for both make payment or first registration. 

I first logged in with an account, then i logged out and clear my browser cookie and local storage which I use to store access token, then when I try to register it appear my old username instead of `None`. But everytime when I restart my backend it appear back to `None` again. Are there way to stop the cache?

**Comment by vimalloc** [comment]
There shouldn't be any caching going on in this extension. Could you provide a complete minimum example that I could run to see the behavior you are seeing? 

Are you running this with the flask development server, or in production using something like uwsgi or gunicorn? I would also be interested the output of  `print(request.headers)` and `print(request.cookies)`  in this request, to see what the server is receiving on the requests that are giving you issues.

**Comment by gaara4896** [comment]
The flask is a a backend server, running purely flask development server, I had tried to log the result of request.headers and request.cookies

**request.headers**

```
Dnt: 1
Content-Type: application/x-www-form-urlencoded
Referer: **something domain name**
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Content-Length: 126
Connection: close
X-Forwarded-For: **something else**
X-Real-Ip: **something else**
Host: localhost:5000
```

**request.cookies**

```
{}
```

It seems that access token are not presented.

**Comment by vimalloc** [comment]
Huh, that is very odd. There shouldn't be any caching going on here, at least provided by this extension. I'll try to reproduce this locally. What version of flask and flask-jwt-extended are you using?

**Comment by vimalloc** [comment]
I am unable to reproduce this locally, using the newest version of flask, flask-jwt-extended, and python 3.6.2. Here is the code I was using to test this:

```python
from flask import Flask, jsonify, request
from flask_jwt_extended import (
    JWTManager, jwt_optional, create_access_token, get_jwt_identity,
    set_access_cookies, unset_jwt_cookies
)

app = Flask(__name__)
app.config['JWT_SECRET_KEY'] = 'super-secret'  # Change this!
app.config['JWT_COOKIE_CSRF_PROTECT'] = False
app.config['JWT_TOKEN_LOCATION'] = ['cookies']
jwt = JWTManager(app)


@app.route('/login')
def login():
    access_token = create_access_token(identity='fooar')
    resp = jsonify({'login': True})
    set_access_cookies(resp, access_token)
    return resp


@app.route('/logout')
def logout():
    resp = jsonify({'logout': True})
    unset_jwt_cookies(resp)
    return resp

@app.route('/test')
@jwt_optional
def test():
    print(request.cookies)
    username = get_jwt_identity()
    print(username)
    return jsonify(user=username)


if __name__ == '__main__':
    app.run()
```

This works exactly as one would expect. If you're still seeing this behavior, could you provide a minimum working example that can be used to replicate this?
