### ISSUE TITLE
Default invalid token callback may not be secure

### ISSUE THREAD

**Issue by CristianoYL** [vimalloc/flask-jwt-extended#133]
Hi, I'm quite new to this extension, and please correct me if I'm wrong.

While playing around with the `@jwt_protected` endpoint, and trying to customize my `invalid_token_loader` callback I noticed that we can get different error messages depending on how we tamper the token.

I understand it's reasonable to differentiate between an invalid token and an expired token and respond to them accordingly. However, when I play around with the bits in the token, I receive error messages of all kinds, including: 

- Invalid header string: 'utf-8' codec can't decode byte 0x88 in position 18: invalid start byte
- Invalid crypto padding
- Signature verification failed
- Invalid payload padding

It concerns me that it might be revealing too much information than needed, and may introduce risk to the encryption. I'm not an expert in crypto, but it seems that the above design may result in a Padding Oracle Attack[ ( Wiki link here).](https://en.wikipedia.org/wiki/Padding_oracle_attack)

Do you think it's a good idea to just return a unified message such as "Token is invalid" instead?

**Comment by vimalloc** [comment]
The `Invalid <section> padding`and  `invalid header string` are errors that occur before the secret is used to try and validate the token. The first ones mean that you have altered the  JWT in such a way that one of the [sections](https://scotch.io/tutorials/the-anatomy-of-a-json-web-token#toc-what-does-a-jwt-look-like) no longer contains valid base64 and cannot be base64 decoded. The second one means that after  base64 decoding the segment, it is not a valid utf-8 string. 

These will not pose security issues like what you linked above, as these can all be verified and have the same results shown locally by anyone who has the invalid token. The only error in your list that actually tries to validate the token using the secret key is the `Signature verification failed` error.

That said, I'm not really opposed to returning a uniformed error message in all cases. I don't think it would change very much in practice though. If you wanted to submit a PR for that, I could look over it.

Cheers.

**Comment by CristianoYL** [comment]
Hi @vimalloc ,

Thanks for the reply and the tutorial. I'll look into it a bit more and let you know if I shall make a PR.

Thanks.
