### ISSUE TITLE
JWT in Cookies example-- should @jwt_required be required on a logout route?

### ISSUE THREAD

**Issue by mgd722** [vimalloc/flask-jwt-extended#134]
Hi @vimalloc!  Thank you so much for a making an awesome, well-documented extension.  In your [JWT in Cookies example](http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html), the logout route looks like this:

```
@app.route('/token/remove', methods=['POST'])
@jwt_required
def logout():
    resp = jsonify({'logout': True})
    unset_jwt_cookies(resp)
    return resp, 200
```

Is there any particular reason for why the `jwt_required` decorator is needed here?  If a user's access token has expired this decorator prevents him from logging out and removing his refresh token cookie.  Refreshing an expired token just to log the user out seems a bit silly.

**Comment by vimalloc** [comment]
Nope, that is entirely an oversight when writing the docs. Good catch! Would you want to submit a pull request to fix that up?

Cheers! :+1:
