### ISSUE TITLE
how to blacklist user generated refresh token

### ISSUE THREAD

**Issue by sunit26** [vimalloc/flask-jwt-extended#137]
i want to blacklist user generated refresh token one way is to put it on blacklist but since the token is generated by user how would i know the particular user has which token.i don't want to store these token in db and query db each time for blacklist check.

Edit : Here user i am refereeing to is API user.

**Comment by vimalloc** [comment]
How is the token generated by the user? That sounds really bad tbh. Possible security concerns about users creating their own tokens aside, if they have the secret needed to generate tokens and one of their tokens get blacklisted, they could just create another and keep going on their way. 

All that said, if you do want to blacklist user created tokens, it wouldn’t really be any different then solution outlined in the documentation. You will need to create an endpoint, grab the token in that endpoint, and put it into your blacklist data store.

**Comment by sunit26** [comment]
How can i grab that particular token that is created by some API user.

**Comment by vimalloc** [comment]
You need to have the token sent to your backend by the user. In this extension, you can setup your backend by using the `@jwt_refresh_token_required` decorator, and the `get_raw_jwt()` function in your endpoint. See: http://flask-jwt-extended.readthedocs.io/en/latest/blacklist_and_token_revoking.html

**Comment by sunit26** [comment]
@vimalloc i have read the docs but this approach is fine when you are integrating your flask API with
 front-end or mobile app and you yourself handling the front-end app or mobile app you can blacklist the tokens when ever you want  because you are handling the tokens.

But lets takes the use case where you want to give access to third party, In that case you have to give a user and password so that they can access my API's. Let's assume that they have started consuming our API's and after some time i want to revoke their access for that i can change the status in my db for that user and the third party user will not able to generate the tokens(access/refresh) again but they have already access token and refresh token. Access token might expire as they have short life but generally refresh token has long life. So in this case the third party user still able to use the  refresh token to generate access and use my API's till the refresh token expires.

So in this how can i revoke third party access token since i don't have the refresh token generated by the third party API user.

**Comment by vimalloc** [comment]
When they create an access or refresh token using the username and password supplied, you can store the created token in a database with their username and a revoked status of `unrevoked`. Then, when you want to actually revoke the refresh tokens, you can go to the database, find tokens that have been created by the given username, and update the revoked status in the database. Basically you are storing the tokens at creation time, instead of at revocation time.

Here is an example you could use to get started with this: https://github.com/vimalloc/flask-jwt-extended/tree/master/examples/database_blacklist
