### ISSUE TITLE
current_app.json_encoder should be passed to jwt.encode

### ISSUE THREAD

**Issue by matthewstory** [vimalloc/flask-jwt-extended#138]
I use a custom JSON encoder in Flask to help serialize my models for my REST end-points. currently this encoder is not passed to `jwt.encode`:

_flask_jwt_extended/tokens.py:29_
```
encoded_token = jwt.encode(token_data, secret, algorithm).decode('utf-8')
```

The `jwt.encode` method takes an optional `json_encoder` argument. I contend that we should use this option to pass in the json encoder for the current Flask app.

It looks like the tokens module has been designed to not have any knowlege of the config module, so probably the patch here would be to add a new `@property` to the config object which returns `current_app.json_encoder`, and then to add json_encoder as an optional argument to all encoding methods in `tokens.py`.

Happy to provide a PR for this if we agree it's useful and the approach above is correct.

**Comment by vimalloc** [comment]
That sounds absolutely reasonable to me. If you can submit a pull request I would be happy to get that merged and release a new version.

Cheers :+1:

**Comment by matthewstory** [comment]
Happy to add more tests if you find it necessary.

**Comment by vimalloc** [comment]
Released in version 3.8.0. Thanks for contributing! :+1:

**Comment by matthewstory** [comment]
Awesome, thanks!

**Comment by matthewstory** [comment]
After I pulled down the most recent version it didn't work for me ... I didn't push one line in the first PR ... so sorry about that.
