### ISSUE TITLE
Why do we need a separate fresh login endpoint?

### ISSUE THREAD

**Issue by CristianoYL** [vimalloc/flask-jwt-extended#145]
Hi, 

It's more of a best practice question. I've been working on this extension recently. And I noticed that in the documentation, it is recommended to create three endpoints `/login`, `/refresh` and `/fresh-login`.

I can understand that we don't want the user to login via credentials every time thus we need the `/refresh` endpoint. But I'm not sure about the `/fresh-login` endpoint, since that the `/login` endpoint gives us a fresh access token already. 

I understand the concern that we don't want to generate refresh tokens over and over again. But my argument would be that, in practice, we only need the user authenticates via credentials once in a long period of time, and meanwhile, he only needs to use the refresh token to re-authenticate. I feel like using the `/login` endpoint would be sufficient as opposed to introducing another `/fresh-login` endpoint, and there wouldn't be an abuse of generating refresh tokens.

Please let me know if I erred. Thank you.

**Comment by vimalloc** [comment]
There isn’t any hard and fast rules for this, it mostly depends on the needs of your application. For our use case, we had a few actions that we only wanted to allow if the user had a fresh access token, such as submitting a payment or modifying a dns record. We added that second login endpoint for these actions as needed (we use a low token expires time, and all tokens created with the refresh token are marked as non-fresh), to prevent creating lots of refresh tokens like you said. 

There is no reason you have you use this pattern, or if you wanted you could roll both of those login endpoints into one endpoint with an optional quest string arg to specify if a refresh token should be created as well, or something like that.

Hope this helps. If you have any follow up questions don’t hesitate to ask.

**Comment by CristianoYL** [comment]
@vimalloc Thanks for your timely reply. So can we come to the conclusions:
- If we feel that our user would frequently need a fresh token, then create a `/fresh-login` endpoint.
- If the fresh token is needed very occasionally, we can just use the `/login` endpoint.

Given that both these endpoints respond with fresh access tokens.

**Comment by vimalloc** [comment]
Sounds perfect! :+1:

**Comment by CristianoYL** [comment]
Thanks for the response. I'm closing this issue now.
