### ISSUE TITLE
how to revoke token on all devices

### ISSUE THREAD

**Issue by thinhlx1993** [vimalloc/flask-jwt-extended#146]
Hello, I have one question. When I change the password on chrome I added token to a blacklist but the user still logged on firefox and it is a security problem of mine. How to revoke all token of the user when changing the password?

**Comment by Pseudonick47** [comment]
Hey,
One of the solutions I found for blacklisting all issued tokens is storing last password change time in the db, and using custom claim which checks whether the `token issued at` is before or after the last password change.
Not sure if that is the best method, let me know what you think

**Comment by vimalloc** [comment]
That is totally a viable option. Another one may be to store all your tokens in a database at token creation time, along with the identity of those tokens. Then you can query the database by identity and revoke all of the active tokens currently in there (or any subset thereof). There is some code in the examples directory that should get you started with that if you want to go in that direction. 

Hope this helps!

**Comment by thinhlx1993** [comment]
I think the solution is saving access_token, refresh_token and user_id to the database, use Redis revoked_store if use change password finds user_id on the database and revoke all user token. :)

**Comment by vimalloc** [comment]
👍 

I’m gonna close this for now then. Feel free to comment / reopen if you have any other questions.
