### ISSUE TITLE
allow to modify existing JWT token without changing CSRF tokens

### ISSUE THREAD

**Issue by rgbj** [vimalloc/flask-jwt-extended#147]
I have a "by the book" (i.e. I applied http://www.redotheweb.com/2015/11/09/api-security.html) 'login' endpoint that verifies credentials and emits JWT in a cookie + token in the response body. The caller is then tasked with storing the access token sent in the response body and using it through a header for subsequent calls.

I have some other endpoints that get used later in the application flow that would like to store more data as user claims in the JWT, essentially using the JWT user claims as a kind of lightweight client-side session system. If I rebuild a brand new JWT, then the XSS/CSRF tokens gets updated, and the client has to update its subsequent calls accordingly.

I'd like the fact there is more data as user claims in the JWT to be kind of transparent to the client, i.e. it shouldn't have to take care that the token values changed. So, I'd like to add data in the user claims without generating new access tokens.

Here is a code sample that outlines what I want to do:

```python
from flask import Flask, jsonify
from flask_jwt_extended import (
    JWTManager,
    create_access_token,
    get_csrf_token,
    get_jwt_claims,
    get_jwt_identity,
    get_raw_jwt,
    jwt_optional,
    jwt_required,
    set_access_cookies,
)
from flask_jwt_extended.tokens import _encode_jwt

app = Flask(__name__)

app.config['JWT_SECRET_KEY'] = 'some random value'
app.config['JWT_COOKIE_SECURE'] = False
app.config['JWT_TOKEN_LOCATION'] = ['cookies']
app.config['JWT_ACCESS_COOKIE_NAME'] = 'at'
app.config['JWT_ACCESS_COOKIE_PATH'] = '/'
app.config['JWT_CSRF_IN_COOKIES'] = False
app.config['JWT_IDENTITY_CLAIM'] = 'sub'

jwt = JWTManager(app)


@app.route('/jwt', methods=['POST'])
@jwt_optional
def jwt():
    uc = get_jwt_claims()
    return jsonify({
        'login': get_jwt_identity(),
        'ext': uc.get('ext')
    })


@app.route('/one', methods=['POST'])
def one():
    access_token = create_access_token('bobby')
    resp = jsonify({
        'step': 'one',
        'access_csrf': get_csrf_token(access_token)
    })
    set_access_cookies(resp, access_token)
    return resp


@app.route('/two', methods=['POST'])
@jwt_required
def two():
    jwt = get_raw_jwt()
    uc = jwt['user_claims']
    uc['ext'] = 'something'
    token_data = {
        app.config['JWT_IDENTITY_CLAIM']: jwt[app.config['JWT_IDENTITY_CLAIM']],
        'fresh': jwt['fresh'],
        'type': jwt['type'],
        app.config['JWT_USER_CLAIMS']: uc,
        'csrf': jwt['csrf']
    }
    at = _encode_jwt(token_data,
                     app.config['JWT_ACCESS_TOKEN_EXPIRES'],
                     app.config['JWT_SECRET_KEY'],
                     app.config['JWT_ALGORITHM'])
    resp = jsonify({
        'step': 'two'
    })
    set_access_cookies(resp, at)
    return resp
```

1. `/one` gives me a cookie + token
2. using that cookie and that token, I can call whatever protected endpoint I want
3. at some point, I call `/two`
4. the JWT changes, but the token stays the same. I can continue to call protected endpoints with the token I got in step 1

Two questions:
- is it safe to do something like that, or did I just dig a huge hole security-wise?
- if it is safe, is there a way to add something to flask-jwt-extended to make it easier? As it is, I need to call the private `_encode_jwt` function, and the setup leading to this call is kind of ugly..

Thanks in advance!

**Comment by vimalloc** [comment]
So there isn’t a security concern there, but it probably isn’t an optimal way to use jwts. I would personally suggest either putting all the data you will need into the jwt from the get go, or on the client side grab the token from the double submit cookie before every request instead of returning it back once the post body so that you don’t have to worry about the csrf token changing out from under you. 

I obviously don’t know the details of your app, is there any reason one of these two solutions would not work for you?

**Comment by rgbj** [comment]
As for your first suggestion: The data I am adding later on isn't available initially. That's why I can't put it in the JWT from the get go.

The second option would work -- in fact, I went through it before evolving towards the system I describe here -- However, it would require more complex code on the client side, which is what I was trying to avoid.

Anyway, thanks for your feedback; I'll close this issue now.
