### ISSUE TITLE
How to change token error response key?

### ISSUE THREAD

**Issue by aledejesus** [vimalloc/flask-jwt-extended#153]
As stated in the [docs](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.expired_token_loader) , the default response structure when there's an issue with the token is {'msg': < error message >}. I know that I can change the response by providing a callback for each error but that feels like too much just to change the error key, e.g., change 'msg' to 'error'. Is there a simpler way to achieve this?

**Comment by vimalloc** [comment]
Alas, that does not exist. The only way to do this will be to use the decorators that allow you change the result of the callbacks.
