### ISSUE TITLE
Signer and verifier deprecated warning -  Asymmetric keys with Algorithm

### ISSUE THREAD

**Issue by mpsiva89** [vimalloc/flask-jwt-extended#154]
I am using the following configuration for JWT implementation

> JWT_ALGORITHM = 'RS256'
> JWT_PRIVATE_KEY = open("/private_key.pem", "r").read()
> JWT_PUBLIC_KEY = open("/public_key.pub", "r").read()
> 

Everything is working fine. But I am getting the following warning message. 

```
/python3.6/site-packages/jwt/algorithms.py:178: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  self.hash_alg()

```

**Comment by vimalloc** [comment]
That's gonna be something to do with the underlying pyjwt or the cryptography packages that is used by this extension. What version of those packages to you have installed? I'm wondering if upgrading them will fix the issue.

**Comment by vimalloc** [comment]
I'm going to close this out. If upgrading the pyjwt and cryptography libraries does not fix the issue for you, feel free to re-open this and I would be happy to help dig some more. :+1:
