### ISSUE TITLE
Missing Authorization Header although header is present

### ISSUE THREAD

**Issue by simonsax** [vimalloc/flask-jwt-extended#156]
I have a vue nuxt app and get the following error message in case I initiate a (serverside) request from my nuxt server (for example when I reload a page):
`flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header`

but when I print the header it looks like this:
- Accept: application/json, text/plain, */*
- Connection: keep-alive
- Pragma: no-cache
- Cache-Control: no-cache
- Upgrade-Insecure-Requests: 1
- User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like - Gecko) Chrome/66.0.3359.181 Safari/537.36
- Referer: http://localhost:3000/
- Accept-Encoding: gzip, deflate, br
- Accept-Language: en,en-US;q=0.9,de-CH;q=0.8,de;q=0.7
- Cookie: jwt= {{jwt Token -> deleted for better readability }}
- Authorization: Bearer {{jwt Token -> deleted for better readability }}
- Host: 127.0.0.1:5000

When I initiate the same request from the user client (for example when I navigate around without reloading) I don't get any error. I noticed that in this case the header looks slightly different:
- Host: 127.0.0.1:5000
- Connection: keep-alive
- Pragma: no-cache
- Cache-Control: no-cache
- Accept: application/json, text/plain, */*
- Origin: http://localhost:3000
- Authorization: Bearer {{jwt Token -> deleted for better readability }}
- User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like - Gecko) Chrome/66.0.3359.181 Safari/537.36
- Referer: http://localhost:3000/dashboard
- Accept-Encoding: gzip, deflate, br
- Accept-Language: en,en-US;q=0.9,de-CH;q=0.8,de;q=0.7

Any idea why I get an error although the token seems to be present in both cases?
Your help is much appreciated!
Best regards
Simon

**Comment by vimalloc** [comment]
How are you initiating that server side request? Are you manually injecting the header into it?

Also, it that first request it looks like you are sending the JWT in with cookies and headers, is that intentional? Wonder if maybe there is something going on there?

**Comment by simonsax** [comment]
Thanks vimalloc, for your response. Unfortunately I wasn't able to solve the problem but I think it's not an issue of flask-jwt-extended. I set the token with the setToken-Method provided by the axios nuxt.
