### ISSUE TITLE
csrf in cookie not validated

### ISSUE THREAD

**Issue by maskiran** [vimalloc/flask-jwt-extended#157]
When CSRF is sent in a cookie, the verify_jwt is looking for a header and is not looking at the cookie

**Comment by vimalloc** [comment]
Yep, that's the point. Otherwise there is no CSRF protection happening.

For additional information, please refer to this links:
https://github.com/vimalloc/flask-jwt-extended/issues/150
http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html
