### ISSUE TITLE
Why is 'nbf' claim even created?

### ISSUE THREAD

**Issue by mths0x5f** [vimalloc/flask-jwt-extended#158]
https://github.com/vimalloc/flask-jwt-extended/blob/19c5720bfd1961be10938fa555f83af6d187924b/flask_jwt_extended/tokens.py#L19-L22

Why is 'nbf' claim is even created if is set to the exactly same value of 'iat'? Correct if I'm wrong, but a not-before-claim makes sense only when set to a epoch greater than 'iat'.

And this leads to another question: how can I set it without patching the lib? Seems that it would better be set conditionally like 'exp' few lines below.

**Comment by vimalloc** [comment]
Both claims exist mostly for legacy reason. Both of those claims are present in Flask-JWT and when this library was first created I wanted to match that as closely as possible to make it easier for people to migrate over this library. At this point I don't think the breaking change of removing one of those claims would give enough benefit to justify it.

If you want to be able to be able to change this you could patch it in your codebase or submit a PR to this extension. I am curious what your use case is for needing this change?

**Comment by mths0x5f** [comment]
First, I'm sorry if sounded impolite. What I imagine, in multi token issuers scenarios, is that a token may be get reject because clock skew as the JWT spec enforces that a 'nbf' has to be respected. I can't think of any use case that would break with the default removal (Someone relying in this clause instead of 'iat'?).

Indeed I do not have a real use case for manually setting for now, if not the hypothetic and paranoid forced delay to access protected views (with someone being notified in the mid-term).

**Comment by vimalloc** [comment]
Yeah, it's unlikely removing the `nbf` claim would cause a problem, but I could see someone doing something funky on the frontend like parsing out that value in javascript and using it for some reason. Probably not happening, but I don't like the idea of removing that if there is the possibility of it breaking someones code out from under them.

I would be totally down to add an option to remove this or set a different `nbf` time though!
