### ISSUE TITLE
"msg": "Missing Authorization Header" when JWT_TOKEN_LOCATION = 'cookies'

### ISSUE THREAD

**Issue by davidrpmorris** [vimalloc/flask-jwt-extended#16]
As the title suggests, I've set `JWT_TOKEN_LOCATION` to `'cookies'` but when I try to access a protected endpoint I get: `"msg": "Missing Authorization Header"`

PS Migrating from a forked version of flask-jwt where I was using cookies as well. Thanks for this project @vimalloc!

**Comment by vimalloc** [comment]
It looks like I have ```NoAuthorizationError``` hardcoded to return "Missing Authorization Header" regardless of if you are using cookies or headers. Whoops! I'll get that fixed up here in a bit.

 In the meantime, contrary to what it sounds like, this just implies that a ```NoAuthorizationError``` was raised. If you are using cookies, this can happen the cookie that is supposed to contain the JWT is not in the request, or if you are using the built in CSRF protection, that the CSRF double submit verification header is missing.

Thanks for the report!

**Comment by vimalloc** [comment]
Just pushed out a new version to pypi/pip that should fix this. Let me know if you continue to have any trouble with the cookies.

Cheers.
