### ISSUE TITLE
Token Location "Cookie": SESSION_COOKIE Configuration Option Ignored

### ISSUE THREAD

**Issue by nicostuhlfauth** [vimalloc/flask-jwt-extended#161]
Once I use `max_age` with `set_access_cookies()`, the _JWT_SESSION_COOKIE_ option is being ignored. It doesn't matter if I set it or not, because it defaults to True. 

### Scenario 1: No `max_age` set
Closing the browser results in the deletion, like expected.

### Scenario 2: `max_age` set
Cookies are still there after re-opening the browser.

Tested in Chrome with Flask-JWT-Extended 3.10.0.

It's definitely not the behavior I expected, so, is there something wrong or an error in reasoning?

**Comment by vimalloc** [comment]
The max_age and session cookie are mutually exclusive, behind the scenes they both go to the `max_age` argument in flask (http://flask.pocoo.org/docs/1.0/api/#flask.Response.set_cookie). This is described in the `max_age` argument in the API here (http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.set_access_cookies). If there is anything that isn't clear there, I would totally welcome a PR to expand the documentation :+1:

**Comment by nicostuhlfauth** [comment]
Thanks for clearing that up @vimalloc :) I would suggest the following improvement for the API docs:

> max_age – The max age of the cookie. If this is None, it will use the JWT_SESSION_COOKIE option (see Configuration Options). Otherwise, it will use this as the cookies max-age **and the JWT_SESSION_COOKIE option will be ignored**. Values should be the number of seconds (as an integer).

**Comment by vimalloc** [comment]
Sounds good. Would you be willing to submit a PR to update that? It should be as simple as updating the docstrings for set_access_cookies and set_refresh_cookies in this file: https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py

:+1:
