### ISSUE TITLE
How to start server

### ISSUE THREAD

**Issue by shafikhaan** [vimalloc/flask-jwt-extended#167]
Hey everyone,

Successfully installed the dependencies in requirements.txt, But i am having difficulty in server starting.
Any help will be greatly appreciated.

**Comment by Groenbech96** [comment]
Hi @shafikhaan 

Do you want a local server running for debugging? 
Then you could follow this guide [Flask hello world](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) by miguelgrinberg. He goes into many different topics of flask. 

If not, could you provide some information about where you want to deploy the flask api? Different setups for different solutions. 
Could you provide a error log from when trying to start the flask app? 

Hope it helps.
