### ISSUE TITLE
JWT for Simultaneous login's

### ISSUE THREAD

**Issue by bhakta0007** [vimalloc/flask-jwt-extended#168]
Hello,

When I login simultaneously (to parallel sessions) I see that only the latest JWT is valid (the previous ones become invalid). Now if the first session does a re-login, then the second one becomes invalid. 

What is the recommended approach in solving this if we want to support multiple-sessions for the same user.?

-B

**Comment by vimalloc** [comment]
These is nothing in this extension that would prevent simultaneous logins. By default, this extension doesn’t store any state server side at all, and who is logged in is completely determined by the token being passed in with a request. 

My guess is you are either using cookies and trying to login multiple times with the same web browser, which is causing the browser to override one set of cookies with another, or doing something in a custom blacklist function that is revoking one token when a newer token is created.

**Comment by bhakta0007** [comment]
ok, I  need to figure out why I am seeing this behavior..I will get back
