### ISSUE TITLE
TypeError: jwt_required() missing 1 required positional argument: 'fn'

### ISSUE THREAD

**Issue by D4Vinci** [vimalloc/flask-jwt-extended#175]
Whenever I use the decorator jwt_required() I get this error

`
	Traceback (most recent call last):
	  File "app.py", line 2, in <module>
	    from api.db import *
	  File "/home/d4vinci/******/******/Project/******/api/db.py", line 51, in <module>
	    @jwt_required()
	TypeError: jwt_required() missing 1 required positional argument: 'fn'
`

and this is my auth function
`
@app.route('/api/db/auth',methods=['POST'])
def auth():
    if not request.is_json:
        return jsonify({"msg": "Missing JSON in request"}), 400

    email = request.json.get('email', None)
    password = request.json.get('password', None)
    if not username:
        return jsonify({"msg": "Missing email parameter"}), 400
    if not password:
        return jsonify({"msg": "Missing password parameter"}), 400

    if email in [ u.email for u in User.objects.all()]:
        return jsonify({"msg": "Bad username or password"}), 401
    elif verify_hash(password,User.objects.filter(email=email).password):
        return jsonify({"msg": "Bad username or password"}), 401

    access_token = create_access_token(identity=username+password+"*"*5)
    return jsonify(access_token=access_token), 200
`

and the function with the decorator is
`
@app.route("/api/db/whoami")
@jwt_required()
def who():
    current_user = get_jwt_identity()
    return jsonify(logged_in_as=current_user), 200`
`

**Comment by vimalloc** [comment]
Use `@jwt_required` instead of `@jwt_required()`.

**Comment by D4Vinci** [comment]
Fixed this by using @jwt_required instead of @jwt_required() .
It's better to fix this in the documentation instead of making everybody learn about decorators to fix this :smile:

**Comment by D4Vinci** [comment]
Commented at the same time :smile:

**Comment by vimalloc** [comment]
So we did :) Is there anywhere in the documentation where it has something like this?

```
@app.route('/protected', methods=['GET'])
@jwt_required()
def protected():
   return "foo"
```

If so, that's a bug in the docs that should be updated.

**Comment by D4Vinci** [comment]
Sorry, my bad

**Comment by ben-mvi** [comment]
Ha! I had the same issue. I am actually upgrading from flask_jwt (not being maintained anymore) to this library and in flask_jwt they use @jwt_required() with the parens. So that was the source of my confusion...

Thanks!

**Comment by Edorka** [comment]
For those using Flask-restful Resource replace also `method_decorators = [jwt_required] ` with `method_decorators = [jwt_required()] `

**Comment by vimalloc-mavenlink** [comment]
Prior to the `4.0.0` release of flask-jwt-extended, `@jwt_required` was the right decorator to use. On version `4.0.0` and above, `@jwt_requried()` should be used instead. See https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/ for all the breaking changes of this release.

**Comment by fweep** [comment]
In line with @Edorka's comment above, for flask-rest-jsonapi, you should use:

    decorators = (jwt_required(),)

in your resources.

**Comment by OpetherMB** [comment]
they updated it to `@jwt_required( )`

**Comment by danilsyah** [comment]
thanks for help, this is the issue that solved my code
