### ISSUE TITLE
expired token loader callback to differentiate refresh tokens from access tokens

### ISSUE THREAD

**Issue by sridharp2992** [vimalloc/flask-jwt-extended#180]
Hi,

I'm working on implementing refresh tokens for my Flask app.
I have short-lived access tokens and slightly longer lived refresh tokens.
All tokens unanimously go to the expired token loader callback and once it hits that we won't be able to retrieve the token to check the type.
I'm looking for a way I can teach my callback function to do action A if an expired refresh token hits and action B if an expired access token hits.

How do I accomplish this?

Thanks & Regards
Priya

**Comment by vimalloc** [comment]
Hrm, that is a use case I haven't considered before, and I don't think it is easily done with the existing code. I could think of a work around for it for now, but it would be a little hacky. You could do something with custom decorators like this:

```python
def jwt_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            verify_jwt_in_request()
            return fn(*args, **kwargs)
        except ExpiredSignatureError:
            return jsonify({'msg': 'custom access token expired message'}), 401
    return wrapper

# And the same thing for refresh_jwt_required. The docs around custom decorators
# can be seen here: http://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html
```

**Comment by sridharp2992** [comment]
I haven't tried this yet. I can try and keep you posted on how that goes!
Thanks again!
