### ISSUE TITLE
token_in_blacklist_loader throws a runtime exception even though after providing a callback function

### ISSUE THREAD

**Issue by sridharp2992** [vimalloc/flask-jwt-extended#181]
I want to blacklist the tokens that are created and expired / upon logout.
I'm storing the tokens in redis and revoking them upon expiration and upon logout.
I have a callback function decorated with @token_in_blacklist_loader which returns a boolean value based on whether the token is revoked or not.
I'm not sure why I'm getting the Runtime Error:  A token_in_blacklist_callback must be provided via the '@token_in_blacklist_loader' if JWT_BLACKLIST_ENABLED is True;

**Comment by vimalloc** [comment]
Can you provide what the decorated function looks like, including the decorator?

**Comment by sridharp2992** [comment]
@jwt.token_in_blacklist_loader
    def check_token_in_blacklist(decr_token):

        revoked_token = redis_db.get(decr_token['jti'])
        if revoked_token is None:
            return True
        return revoked_token == 'true'

I have a callback function like the one above which returns True or False based on whether the token is revoked or not.

**Comment by vimalloc** [comment]
I will need more information here. Testing locally, it seems to work exactly as expected

Code powering the test:

```python
from flask import Flask, jsonify

from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token
)


app = Flask(__name__)

app.config['JWT_SECRET_KEY'] = 'super-secret'
app.config['JWT_BLACKLIST_ENABLED'] = True
jwt = JWTManager(app)

@jwt.token_in_blacklist_loader
def check_if_token_in_blacklist(decrypted_token):
    return True


@app.route('/login', methods=['POST'])
def login():
    return jsonify(access_token=create_access_token('test')), 200


@app.route('/protected', methods=['GET'])
@jwt_required
def protected():
    return jsonify({'hello': 'world'})

if __name__ == '__main__':
    app.run()
```

And the results of hitting the code

```
$ http POST :5000/login
HTTP/1.0 200 OK
Content-Length: 295
Content-Type: application/json
Date: Tue, 07 Aug 2018 05:11:07 GMT
Server: Werkzeug/0.14.1 Python/3.6.4

{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzM2MTg2NjcsIm5iZiI6MTUzMzYxODY2NywianRpIjoiM2VkN2RkNTQtMjhhNC00NWRlLWFkOTMtNTliNWFiZjBhMmEyIiwiZXhwIjoxNTMzNjE5NTY3LCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.7Xf479FOfm1RMjRA5AaGh_2Zt14SMMlPzW0N7sMEMWo"
}


$ export ACCESS="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzM2MTg2NjcsIm5iZiI6MTUzMzYxODY2NywianRpIjoiM2VkN2RkNTQtMjhhNC00NWRlLWFkOTMtNTliNWFiZjBhMmEyIiwiZXhwIjoxNTMzNjE5NTY3LCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.7Xf479FOfm1RMjRA5AaGh_2Zt14SMMlPzW0N7sMEMWo"

$ http :5000/protected
HTTP/1.0 401 UNAUTHORIZED
Content-Length: 39
Content-Type: application/json
Date: Tue, 07 Aug 2018 05:11:31 GMT
Server: Werkzeug/0.14.1 Python/3.6.4

{
    "msg": "Missing Authorization Header"
}


$ http :5000/protected Authorization:"Bearer $ACCESS"
HTTP/1.0 401 UNAUTHORIZED
Content-Length: 33
Content-Type: application/json
Date: Tue, 07 Aug 2018 05:11:47 GMT
Server: Werkzeug/0.14.1 Python/3.6.4

{
    "msg": "Token has been revoked"
}
```

**Comment by vimalloc** [comment]
As I posted in my last comment, the token revoking feature seems to be working, which doesn’t surprise me as it is extensively tested in this codebase (https://github.com/vimalloc/flask-jwt-extended/blob/master/tests/test_blacklist.py). This means there is likely a bug in your code causing the issues. Based on that error, I think it’s probably with how you are registering your callback function with the `JWTManager`. 

In order to help debug this I will need a Minimum, Complete, and Verifiable Example demonstrating the issue you are seeing. (https://gamedev.meta.stackexchange.com/questions/2201/whats-a-minimum-complete-verifiable-example-mcve-and-how-do-i-provide-it). The error you provided simply doesn’t give me enough information to help.

**Comment by vimalloc** [comment]
This still is not a minimum, complete, and verifiable example, so all I can do is speculate. If you callback function is nested inside of another function, such as:

```python
def jwt_callbacks():
    @jwt.token_in_blacklist_loader
    def check_if_token_in_blacklist(decrypted_token):
        revoked_token = redis_db.get(decrypted_token['jti'])
        if revoked_token is None:
            return True
        return revoked_token == 'true'
```

Then your callback function is never going to be set unless you actually call the `jwt_callback()` is actually called at some point (and it should only ever be called once). You probably want to remove the `jwt_callbacks` method and move the `check_if_token_in_blacklist` outside of that function.

**Comment by sridharp2992** [comment]
Yes, it was my bad. I missed to add the function call here. But I am calling the callback function inside my createapp function where I create the flask app instance and register the blueprints and my classful endpoints.

What other information would you need?

Thanks!

**Comment by sridharp2992** [comment]
Also, I have other callback functions in this file, which work perfectly fine.
I'm just not able to figure out why the blacklist alone is failing!

**Comment by vimalloc** [comment]
I need a minimum, complete, and verifiable example ;)

Basically I need some small sample code I can run locally that reproduces the issue you are seeing. You can take the code based in the comment here (https://github.com/vimalloc/flask-jwt-extended/issues/181#issuecomment-410935704) and modify it to be a full working example of the issue you are seeing, and that would help me be able to help you with the issues you are seeing.
