### ISSUE TITLE
Correct the "expire flag" of key in set. [redis]

### ISSUE THREAD

**Issue by christian-quisbert** [vimalloc/flask-jwt-extended#182]
https://github.com/vimalloc/flask-jwt-extended/blob/3d598d401d06aa959cdca33c9e63b4c6ad64b98e/examples/redis_blacklist.py#L85

**L85 and L86 are incorrect.**

This 2 lines should be:
` revoked_store.set(access_jti, 'false', timedelta(seconds=ACCESS_EXPIRES.total_seconds() + 600)
`
`
revoked_store.set(refresh_jti, 'false', timedelta(seconds=REFRESH_EXPIRES.total_seconds() + 600)
`
In this way, for example, the tokens are revoked 10 minute after they expired.

**Comment by vimalloc** [comment]
They are not incorrect, you can absolutely `*` a timedelta to increase it:

```python
>>> ACCESS_EXPIRES = timedelta(minutes=15)
>>> ACCESS_EXPIRES
datetime.timedelta(0, 900)
>>> ACCESS_EXPIRES * 1.2
datetime.timedelta(0, 1080)
```

You can use a different metric for you application, but for the sake of this example application it is fully functional.

**Comment by vimalloc** [comment]
For your example, if you want it to be 10 minutes after the token expired, it could be more clearly written like so:

```python
revoked_store.set(access_jti, 'false', ACCESS_EXPIRES + timedelta(minutes=10))
```

**Comment by christian-quisbert** [comment]
That way I get a type error with the operator "*".

`>>> from datetime import timedelta`
`>>> ACCESS_EXPIRES = timedelta(minutes=15)`
`>>> ACCESS_EXPIRES`
`datetime.timedelta(0, 900)`
`>>> ACCESS_EXPIRES * 1.2`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`TypeError: unsupported operand type(s) for *: 'datetime.timedelta' and 'float'`
`>>> `

**Comment by vimalloc** [comment]
Oh, I didn't realize, but that must be a python3 only feature. I'll make a note of that on the project example, thanks. Also, for what it's worth, if you have the ability to use python3 instead of python2, I highly recommend you do so. Python2 will be officially end of lifed in 2020.

Cheers.
