### ISSUE TITLE
Add refresh token consideration to jwt_optional 

### ISSUE THREAD

**Issue by xolott** [vimalloc/flask-jwt-extended#183]
I'm writing an authorization endpoint to work with [Ambassador](https://github.com/datawire/ambassador)

Ambassador redirect to my authz endpoint (/auth/validate), perform some validation and then redirect to my final endpoint (the resource that the user want to access) I want to let flask-jwt-extended the validation of the token in case that exists in the headers, so, I add the `@jwt_optional` decorator to the validate endpoint.

But, if I made a request to `/auth/refresh` sending the Refresh Token as Authorization Header, the `/auth/validate` endpoint return a 401 response with the message: `Only access tokens are allowed`. Changing the Authorization Header to the access token, I got a 401 response with the message  `Only refresh tokens are allowed` (failing in the `/auth/refresh` endpoint).

Is there any reason to exclude the refresh token validation with a partially protected endpoint? How do I know if the token in the Authorization Header is an access token or a refresh token?

**Comment by vimalloc** [comment]
I'm hesitant to change the current jwt_optional behaivor, just because of the potential breaking changes that may have on other peoples codebase. It could be worked around with a custom decorator instead (http://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html).

Something like this (untested)

```python
def all_jwt_optional(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            verify_jwt_in_request()
        except (NoAuthorizationError, InvalidHeaderError):
            pass
        try:
            verify_jwt_refresh_token_in_request()
        except (NoAuthorizationError, InvalidHeaderError):
            pass
        return fn(*args, **kwargs)
    return wrapper
```
