### ISSUE TITLE
how to get token in flask?

### ISSUE THREAD

**Issue by libaibuaidufu** [vimalloc/flask-jwt-extended#184]
i want to get token in flask,then take token to request other api in flask.
have a method?
thanks

**Comment by vimalloc** [comment]
I'm not entirely sure what you're asking. If you are in a protected endpoint and want to get the decoded token, you can use http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.get_raw_jwt. If you are in a protected endpoint and want to get the encoded token, you can look at the built in flask `Request` object and grab it from the headers or cookies or however you are sending it in to your application. I'm not sure if there is a good reason to do that though.

**Comment by libaibuaidufu** [comment]
I also think it's meaningless to do this，then I get the encoded token in the headers. thanks!

**Comment by vimalloc** [comment]
Sure thing, glad I could help.
