### ISSUE TITLE
Why not provide a seprate config params for JWTManager

### ISSUE THREAD

**Issue by minghu6** [vimalloc/flask-jwt-extended#185]
In a model
```python
jwt = JWTManager(config=config)
```

In the app.py

```python
app = Flask(__name__)
jwt.init_app(app)
```

**Comment by vimalloc** [comment]
That's just not very common in the Flask ecosystem. By using the app config we get all of the great flask configuration management without having to complicate our codebase. http://flask.pocoo.org/docs/1.0/config/

**Comment by minghu6** [comment]
I mean the config is also a instance of `flask.config.Config`

we can write 
```python
jwt = JWTManager(config=config)
#########################
from xxx import jwr
jwt.init_app(app)
```
instead of 

```python
jwt = JWTManager()
#########################
from xxx import jwt_config
app.config.update(jwt_config)
jwt.init_app(app)
```
ps: my project follow the guide of http://flask-restplus.readthedocs.io/en/latest/scaling.html
