### ISSUE TITLE
An in-depth explanation of how the double-submit protection works

### ISSUE THREAD

**Issue by briancappello** [vimalloc/flask-jwt-extended#19]
http://www.redotheweb.com/2015/11/09/api-security.html

Personally, I found it more helpful than the stackoverflow link, and less opinionated/pushy-salesman-like than the stormpath article. If you want to add it, otherwise, feel free to just close this issue :)

**Comment by vimalloc** [comment]
Thanks! I think this is a much better article then the stuff I have previously linked to. I'll update them to point at this :+1:
