### ISSUE TITLE
Is it a risk to store the refresh token in the browser?

### ISSUE THREAD

**Issue by tharakabimal** [vimalloc/flask-jwt-extended#192]
I know this is not a package issue. But I just need help. Should I store the refresh token in the browser (local storage/cookies)?

**Comment by vimalloc** [comment]
If you are writing a web app, you are going to need to store the refresh token somewhere that it can actually be accessed and used. That basically means JavaScript (local storage) or coookies are your best options. Either one of them will totally work. You could look at the discussion in #177 to see some trade offs of either approach

**Comment by tharakabimal** [comment]
Thanks, will do.
