### ISSUE TITLE
Looking for additional maintainers

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#194]
First off, my current involvement of this project is not going to change, I will still be actively maintaining it. I am however looking to get a couple other maintainers for this project and the sister project, flask-jwt-simple.

When I first wrote this extension it just because I needed this functionality for my job. I did not expect it to widely used at all. Now that this extension is actively being used, the reason I'm looking for additional maintainers is to make sure this project will still live on in case I'm [hit by a bus](https://en.wikipedia.org/wiki/Bus_factor).

The primary responsibilities of a maintainer would be code reviews and helping with issues that come in. All these are pretty low traffic so it shouldn't be much work. If you're intrested or have more questions, please let me know either in this ticket, or in the `#flask-jwt-extended` irc channel on freenode.

Cheers :+1:

**Comment by Nimor111** [comment]
Read this on reddit and since I've been looking to get involved in open source for a while this looks like a good opportunity. I've been using python for almost two years now if that helps :) I'm interested.

**Comment by NandoTheessen** [comment]
Hey there @vimalloc!
I'd love to help you maintain both repos!
Let me know if you need help w/ anything or how I can get started 👍

**Comment by vimalloc** [comment]
Thanks @Nimor111 and @NandoTheessen, I really appreciate it!

Let me get some contributor role stuff setup. My initial thoughts here is I will make you both contributors, and we all try it out for a couple months to make sure that everyone is on the same page and happy with where this project is going. Specific things I'm thinking are:

* Have both of you help with new tickets coming. Specifically helping out if someone has an issue with this extension (often by pointing them to the correct examples or documentation), and verifying bugs if they arise.
* Requiring code reviews on incoming pull requests (originating from me or anyone else) before they can be merged into master.
* Move over from irc to a public gitter or slack (instead of irc) to make it easier to have a way to communicate with each other and the users of this extension.
* Provide feedback for any new feature requests or improvements to the extension.
* If either of you are feeling brave, you could try to tackle https://github.com/vimalloc/flask-jwt-simple/issues/6 as well. It's not a big priority or anything, but might help familiarize you with some of the code base. That is for flask-jwt-simple, but there are a lot of similarities between these two extensions. 

If we are both happy after trying this out for a while, I can get you access to push to master yourself and cut new releases of the extension.

Any thoughts, concerns, ideas, etc about this? Nothing is set it stone here, I want to make sure everyone is happy with this.

Thanks again!

**Comment by erasmo07** [comment]
Hey @vimalloc 
It sounds great what you propose, 
I can help you I have knowledge in Python and I would like to help in some Open Source Project.

**Comment by deathweaselx86** [comment]
I'm also interested. Let me know if there's still room. 💯

**Comment by vimalloc** [comment]
@deathweaselx86 and @erasmo07 sure thing! I would never complain about having more people help out with open source software! 👍

**Comment by frfahim** [comment]
Hi @vimalloc, I am interested too. Let me know if there any chance to get involved, eagerly waiting for your response.

**Comment by vimalloc** [comment]
Good news, I've gotten the gitter page setup. I think I've invited everyone, but in case that didn't go through you can see it here: https://gitter.im/flask-jwt-extended/Lobby

If you still are interested in maintaining this, please go ahead and join in the conversation there. Thanks!

**Comment by vimalloc** [comment]
I’m going to close this at this point in time. Future discussions will happen on gitter.
