### ISSUE TITLE
Exceptions in production not producing json

### ISSUE THREAD

**Issue by constemi** [vimalloc/flask-jwt-extended#20]
Flask with blueprint pattern, using Flask Restful with a Token Resource class and method decorator for jwt_required. 

```
'''In app.py'''
from flask_jwt_extended import JWTManager
from flask import Flask

jwtmanager = JWTManager()

def create_app():
    app = Flask(__name__)

def register_extensions(app):
    jwtmanager.init_app(app)


'''in views.py'''
from flask_restful import Resource, Api
from flask_jwt_extended import jwt_required

api = Api()

class TokenResource(Resource):
    method_decorators = [jwt_required]

class HelloWorld(TokenResource):
    def get(self):
        return 'Hello, World!'

api.add_resource(HelloWorld, '/hello')
```

The issue I am having is with exceptions and it likely has little to do with this library. When I run into a common jwt_extended exception on the flask development server with debug enabled I get this which is awesome!
```
{
  "msg": "Token has expired"
}

```
With Gunicorn I get this on the exact same request with the same expired token.
gunicorn --reload --worker-class "gevent" "app:create_app()"
```
{"message": "Internal Server Error"}

```
with a traceback that the development server never showed. 

```
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
resp = resource(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
return self.dispatch_request(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
resp = meth(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/flask_jwt_extended/utils.py", line 222, in wrapper
jwt_data = _decode_jwt_from_request(type='access')
File "/usr/local/lib/python3.5/site-packages/flask_jwt_extended/utils.py", line 204, in _decode_jwt_from_request
return _decode_jwt_from_headers()
File "/usr/local/lib/python3.5/site-packages/flask_jwt_extended/utils.py", line 176, in _decode_jwt_from_headers
return _decode_jwt(token, secret, algorithm)
File "/usr/local/lib/python3.5/site-packages/flask_jwt_extended/utils.py", line 136, in _decode_jwt
data = jwt.decode(token, secret, algorithm=algorithm)
File "/usr/local/lib/python3.5/site-packages/jwt/api_jwt.py", line 75, in decode
self._validate_claims(payload, merged_options, **kwargs)
File "/usr/local/lib/python3.5/site-packages/jwt/api_jwt.py", line 104, in _validate_claims
self._validate_exp(payload, now, leeway)
File "/usr/local/lib/python3.5/site-packages/jwt/api_jwt.py", line 149, in _validate_exp
raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired
```
It is raising the exception and I imagine it is calling the Signature expired callback which sends the json back out but clearly something goes wrong and it bubbles up and Flask hands out a 500 in place of what would have been a signature expired json message as the flask dev server does. 

This probably has nothing to do with this specific library at all and any hints at all your give me about which direction to go in on this would be much appreciated by me. Using this with the flask development server has been perfect but now getting something ready for production I am encountering this persistent issue. My regular views return json just fine with the production setup but these exceptions don't.  I was hoping maybe somebody had been running this in production and would be able to give me a hint on where I went wrong here. Thanks!

**Comment by vimalloc** [comment]
My first guess is that it is related to exception propagation ([Flask Configuration](http://flask.pocoo.org/docs/0.11/config/)). Can you try adding this setting to your app.config?

```python
PROPAGATE_EXCEPTIONS = True
```

Let me know if that fixes the issue for you. If so, I'll add some documentation for this to help avoid future problems.

Cheers!

**Comment by constemi** [comment]
Thank you so much! nailed it. I was going crazy thank you! =)

**Comment by vimalloc** [comment]
No problem! I actually had the same issue when using flask-jwt (https://github.com/mattupstate/flask-jwt/issues/74), which is why I am aware of it :p 

I'm thinking it may be a good idea to explicitly enable it in this extension, I can't really think of a use case where you wouldn't want it set in production. If I push out a new version here in a bit which does that, would you mind testing it and seeing if it works without having to explicitly set PROPAGATE_EXCEPTIONS yourself?

Thanks for the report!

**Comment by constemi** [comment]
absolutely I would be happy to and report back.

**Comment by vimalloc** [comment]
I have a new version pushed, should be up on pypi soon if not already. Whenever you have a chance, let me know if that resolves it for you.

Thanks again!

**Comment by constemi** [comment]
Works perfectly I removed the config setting PROPAGATE_EXCEPTIONS. Rebuilt it completely with 1.0.1 and the extension is now handling that config setting properly. Thanks! Really love this extension!

**Comment by vimalloc** [comment]
Awesome, glad to hear it! :)

**Comment by aijogja** [comment]
Is it secure to set `PROPAGATE_EXCEPTIONS` in production?

**Comment by vimalloc** [comment]
Yes. Just make sure you do not set debug mode in production.

Here is an example example showing that uncaught exceptions will not be leaked:

```python
from flask import Flask, jsonify
from flask_jwt_extended import  JWTManager, jwt_required
from flask_jwt_extended.exceptions import NoAuthorizationError

app = Flask(__name__)

# Setup the Flask-JWT-Extended extension
app.config['JWT_SECRET_KEY'] = 'super-secret'
app.config['PROPAGATE_EXCEPTIONS'] = False
jwt = JWTManager(app)

@app.route('/login', methods=['POST'])
def login():
    raise ValueError("exception without errorhandler")

@app.route('/protected', methods=['GET'])
def protected():
    raise NoAuthorizationError("exception with errorhandler")

if __name__ == '__main__':
    app.run()
```

```
$ http POST :5000/login
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Length: 291
Content-Type: text/html
Date: Sun, 24 Jun 2018 03:38:22 GMT
Server: Werkzeug/0.14.1 Python/3.6.4

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>


$ http :5000/protected
HTTP/1.0 401 UNAUTHORIZED
Content-Length: 38
Content-Type: application/json
Date: Sun, 24 Jun 2018 03:38:31 GMT
Server: Werkzeug/0.14.1 Python/3.6.4

{
    "msg": "exception with errorhandler"
}
```

**Comment by alexwwang** [comment]
I met this problem while using flask-restful 0.3.6 and flask-jwt-extended 3.10.0 with flask 1.0.2.
I've set the PROPAGATE_EXCEPTIONS to True but the internal error still jumped out when I launch my app in docker.

Below is the general implementation I made:

- In the init_app.py where I def a `create_app` func:
```
jwt = JWTManager()
```
- In the func `create_app`:
```
app = Flask(__name__)
app.config['PROPAGATE_EXCEPTIONS'] = True
jwt.init_app(app)

@jwt.invalid_token_loader
def invalid_token_callback():
...
# and some other behavior changing func according to the document.
```

I've no idea what's the problem it is.
Actually outside the docker, in my develop env it works well.
But when load it with gunicorn in docker, it fails.

Look forward to any advice and thanks in advance.

**Comment by alexwwang** [comment]
I think I find the reason.
When PROPAGATE_EXCEPTIONS set True, the exception would be propagated until the last func, which means the self-defined one under the behavior decorators.
So the error tracked back finally gave the error that my behavior change func accept no parameter but one given. 
After changed `def self_defined_invalid_token_callback() ` to `def self_defined_invalid_token_callback(*args)`, the problem solved.

**Comment by vimalloc** [comment]
Yep, your callbacks must accept the correct arguments. You can see a list of the callbacks and what args they accept here: https://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.expired_token_loader

**Comment by alexwwang** [comment]
Thank you @vimalloc  

But it seems a bit different with the document shown here: [https://flask-jwt-extended.readthedocs.io/en/latest/changing_default_behavior.html](https://flask-jwt-extended.readthedocs.io/en/latest/changing_default_behavior.html), in which the self-defined sample function accepts no arguments.

**Comment by vimalloc** [comment]
That's because the example in that doc does not have any arguments passed to it, where `invalid_token_loader` does :)

Per the docs
```
Click on the links for a more more details about what arguments your callback functions should expect and what the return values of your callback functions need to be.
```

**Comment by alexwwang** [comment]
Oh my god, it's my fault not noticing that. Thank you for your hint! XD

By the way, it would be better if the needs of each function are formatted, say, listed e.g. Frankly it's really hard to notice them even you show me the link. I've read twice until found them.  '_`

**Comment by vimalloc** [comment]
If you want to submit a pull request to help update the documentation I would be more then willing to work with you to get it merged :+1:

**Comment by alexwwang** [comment]
I am really glad to since I love this module so much. But I'm afraid it would take a bit time for me to figure it out  'cuz I'm not familiar with how to update the document. Hope you would not mind.
