### ISSUE TITLE
Passing token in header at login

### ISSUE THREAD

**Issue by matteli** [vimalloc/flask-jwt-extended#202]
Several fronted framework take the token at login only if present in the headers.

Perhaps, you can present this option in the basic usage doc with : 

```python
@app.route('/login', methods=['POST'])
def login():
    if not request.is_json:
        return jsonify({"msg": "Missing JSON in request"}), 400
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    if not username:
        return jsonify({"msg": "Missing username parameter"}), 400
    if not password:
        return jsonify({"msg": "Missing password parameter"}), 400
    if username != 'test' or password != 'test':
        return jsonify({"msg": "Bad username or password"}), 401
    access_token = create_access_token(identity=username)
    return jsonify(access_token=access_token),  200, {'Authorization': 'Bearer ' + access_token}
```

Thanks for your work

Matt

**Comment by vimalloc** [comment]
Thanks for your feedback.

I'm not sure if I like changing the basic example to work with specific frameworks, I think there is a benefit of keeping the usage examples as simple as possible, and letting people expand on them as needed for their applications.

What if we added a blurb on the bottom of the page instead of changing the basic example? Something along the lines of:

```
If you are using one of <X> frameworks, it expects that the JWT will be returned
as a header instead of a JSON payload. You can do that like this:

return jsonfiy(login=True), 200, {'Authorization: 'Bearer ' + access_token}
```

Thoughts?

**Comment by matteli** [comment]
Perfect.

**Comment by vimalloc** [comment]
It occurs to me that I'm not actually sure what frameworks require the JWT to be sent back as a header. Would you be willing to create a pull request that adds that, or get me a list of frameworks that I can make a note for?

Cheers.

**Comment by matteli** [comment]
I'm using [vue-auth library](https://github.com/websanova/vue-auth) for vue.js framework and with the bearer driver which is the default, the token must be sent back as header.
I don't know if other library works like that.

Best.
