### ISSUE TITLE
examples_redis_blacklist.py

### ISSUE THREAD

**Issue by pingisheng** [vimalloc/flask-jwt-extended#203]
In https://github.com/vimalloc/flask-jwt-extended/blob/master/examples/redis_blacklist.py
line 64 :     return entry == 'true'
 Here is a something wrong , because redis return result is not str

**Comment by vimalloc** [comment]
In that example, redis should be storing a string. We set it and access it like such

```python
# Saving the token in redis when the token is created
revoked_store.set(access_jti, 'false', ACCESS_EXPIRES * 1.2)

# Marking the token as revoken in the logout endpoints
revoked_store.set(jti, 'true', REFRESH_EXPIRES * 1.2)

# Checking if the token is revoked
entry = revoked_store.get(jti)
if entry is None:
    return True
return entry == 'true'
```

What problems are you seeing? Do you have a stacktrace?

**Comment by pingisheng** [comment]
I think I got the real cause, since I used the Python 3.6. Then I got
result type is bytes from redis.

Landon <notifications@github.com> 于2018年11月6日周二 上午3:06写道：

**Comment by vimalloc** [comment]
Ah, a bytes vs string thing, got it. I'm glad you got that figured out. If you want to submit a pull request to update the redis_blacklist.py example with your solution I would be happy to get that merged!

Cheers :+1:
