### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by MandelaK** [vimalloc/flask-jwt-extended#207]
Hello, I get a deprecation error from pytest and I am not sure what it could mean. I am a beginner and was using your library to secure endpoints for an api I am designing ... could you please add more color to what the reason could be? If you need more information I am happy to provide. 

I ran 38 tests and got 92 deprecation warnings that look like/lib/python3.6/site-packages.

`../../jwt/api_jws.py:119: DeprecationWarning: The verify parameter is deprecated. Please use options instead.`

**Comment by vimalloc** [comment]
Interesting, the `verify` parameter still seems to be there in the `pyjwt` docs. Can you tell me what version of `pyjwt` you are using? `pip freeze | grep -i pyjwt`.

Thanks

**Comment by MandelaK** [comment]
version 1.4.2

**Comment by vimalloc** [comment]
It looks like PyJWT is up to version 1.6.4 now. Can you try upgrading your version of PyJWT and see if you’re still getting that warning?

**Comment by MandelaK** [comment]
Thank you ... no warnings now. I know this was not really an issue with your library, but thanks for helping out anyways, really appreciate it. Have a good day

**Comment by vimalloc** [comment]
For sure! Glad that got it fixed up for you :+1:
