### ISSUE TITLE
jwt_refresh_token_required incorrectly failing valid request in specific environment

### ISSUE THREAD

**Issue by wittlesouth** [vimalloc/flask-jwt-extended#209]
Not sure I like the title of the issue I created, because it already suggest this isn't really a but, but it is accurate.

I have a Flask app that eposes a small set of REST APIs, and the project I'm building them in has a set of unit tests. The test process is to start an instance of the API server in a Kubernetes container, then run a set of tests that make requests to the APIs. In my local environment, the tests run from an OS X shell, and make http requests to the server running in a minikube container. In my Jenkins environment, the tests run from one container, and make http requests to the server in another container.

The issue is that the tests all pass in my local environment, but any test that runs against a flask-jwt-extended endpoint in my Jenkins environment fail due to missing access token errors from the flask-jwt-extended decorators. 

Here is the request handler method and decorator for the first test that fails with this symptom.

```
# The /login enpoint with the GET verb is intended to be used by client apps
# to reload the user's application data when needed (e.g. after an application
# refresh, or browser restart)
@jwt_refresh_token_required
def search():
    """Handles GET verb for /login endpoint"""
    return jsonify(hydrate(g.user)), 200
```

I have before_request and after_request logging enabled with the following code:

```
@FAPP.before_request
def before_request():
    """Method to do work before the request"""
    # Ensure there is a database session available for the request
    g.db_session = DBSESSION()

    # Log request headers & body if FLASK_DEBUG > 1
    if 'FLASK_DEBUG' in os.environ and int(os.environ['FLASK_DEBUG']) >= 2:
        LOGGER.debug('Starting request for path %s', request.url)
        LOGGER.debug('Request Headers: %s', request.headers)
        LOGGER.debug('Request Body: %s', request.get_data())
        LOGGER.debug('Request Cookies: ' + str(request.cookies))

```

and

```
@FAPP.after_request
def after_request(resp):
    """Method to do work after the request"""
    # Log request headers & body if FLASK_DEBUG > 1
    if 'FLASK_DEBUG' in os.environ and int(os.environ['FLASK_DEBUG']) >= 2:
        LOGGER.debug('Response Headers: %s', resp.headers)
        LOGGER.debug('Response Body: %s', resp.get_data())

```

Here is a snippet of the logs from the server in the Jenkins test that is failing

```
[2018-12-01 11:59:52,854] DEBUG in server: Starting request for path http://rftw-jenkins-test-server.wittlesouth:8280/api/v1/login
[2018-12-01 11:59:52,854] DEBUG in server: Request Headers: Accept: */*
X-Csrf-Token: 510f5491-8e2c-4c49-add9-b7bcf21de353
Cookie: refresh_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE1NDM2NjU1OTIsImV4cCI6MTU0NjI1NzU5MiwiaWRlbnRpdHkiOiI4ZjkyNGQ4OC0zNzUyLTQzYzYtODhiOC1mNjA0Yzc4MzAyZGMiLCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6IjJjZjYxMTY1LTkxYzQtNDJmYS1iYTk1LWU0Njc0YjY1N2Y1MiIsImNzcmYiOiI1MTBmNTQ5MS04ZTJjLTRjNDktYWRkOS1iN2JjZjIxZGUzNTMiLCJpYXQiOjE1NDM2NjU1OTJ9.Zmaw-Zar1psqzVbGyKnttbQZW9zwbIuOytEkrKpNuYU; access_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE1NDM2NjU1OTIsImV4cCI6MTU0MzY2NzM5MiwidHlwZSI6ImFjY2VzcyIsImp0aSI6ImViMWFmNTA5LTRjOWUtNGQ1MS04Yzg1LWRlMzJmODNlOGU0NCIsImNzcmYiOiJmZjYyOTMyNC02OWI5LTQ0MGMtYTM5ZC1kMWQwNDdiMzFkNzMiLCJmcmVzaCI6ZmFsc2UsImlkZW50aXR5IjoiOGY5MjRkODgtMzc1Mi00M2M2LTg4YjgtZjYwNGM3ODMwMmRjIiwiaWF0IjoxNTQzNjY1NTkyfQ.p1_RVP0rhnzcRvhVxqjtMMa7wpCeM7Ymcvii5A3HN2w; csrf_refresh_token=510f5491-8e2c-4c49-add9-b7bcf21de353; csrf_access_token=ff629324-69b9-440c-a39d-d1d047b31d73
Host: rftw-jenkins-test-server.wittlesouth:8280
User-Agent: python-requests/2.20.1
Connection: keep-alive
Accept-Encoding: gzip, deflate


[2018-12-01 11:59:52,854] DEBUG in server: Request Body: b''
[2018-12-01 11:59:52,854] DEBUG in server: Request Cookies: {'csrf_refresh_token': '510f5491-8e2c-4c49-add9-b7bcf21de353', 'refresh_token_cookie': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE1NDM2NjU1OTIsImV4cCI6MTU0NjI1NzU5MiwiaWRlbnRpdHkiOiI4ZjkyNGQ4OC0zNzUyLTQzYzYtODhiOC1mNjA0Yzc4MzAyZGMiLCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6IjJjZjYxMTY1LTkxYzQtNDJmYS1iYTk1LWU0Njc0YjY1N2Y1MiIsImNzcmYiOiI1MTBmNTQ5MS04ZTJjLTRjNDktYWRkOS1iN2JjZjIxZGUzNTMiLCJpYXQiOjE1NDM2NjU1OTJ9.Zmaw-Zar1psqzVbGyKnttbQZW9zwbIuOytEkrKpNuYU', 'access_token_cookie': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE1NDM2NjU1OTIsImV4cCI6MTU0MzY2NzM5MiwidHlwZSI6ImFjY2VzcyIsImp0aSI6ImViMWFmNTA5LTRjOWUtNGQ1MS04Yzg1LWRlMzJmODNlOGU0NCIsImNzcmYiOiJmZjYyOTMyNC02OWI5LTQ0MGMtYTM5ZC1kMWQwNDdiMzFkNzMiLCJmcmVzaCI6ZmFsc2UsImlkZW50aXR5IjoiOGY5MjRkODgtMzc1Mi00M2M2LTg4YjgtZjYwNGM3ODMwMmRjIiwiaWF0IjoxNTQzNjY1NTkyfQ.p1_RVP0rhnzcRvhVxqjtMMa7wpCeM7Ymcvii5A3HN2w', 'csrf_access_token': 'ff629324-69b9-440c-a39d-d1d047b31d73'}
[2018-12-01 11:59:52,855] DEBUG in server: Response Headers: Content-Type: application/problem+json
Content-Length: 119


[2018-12-01 11:59:52,855] DEBUG in server: Response Body: b'{\n  "detail": "No authorization token provided",\n  "status": 401,\n  "title": "Unauthorized",\n  "type": "about:blank"\n}\n'
10.47.0.13 - - [01/Dec/2018 11:59:52] "GET /api/v1/login HTTP/1.1" 401 -
```

The behavior above seems to indicate that for some reason Flask-JWT-Extended doesn't seem to be detecting the refresh_token_cookie.

Here is the section of the server code where I set the flask JWT configuration.

```
FAPP.config['JWT_TOKEN_LOCATION'] = ['cookies']
if 'RFTW' in os.environ and os.environ['RFTW'] == 'PROD':
    FAPP.config['JWT_COOKIE_SECURE'] = True
else:
    FAPP.config['JWT_COOKIE_SECURE'] = False
FAPP.config['JWT_ACCESS_COOKIE_PATH'] = '/'
FAPP.config['JWT_ACCESS_TOKEN_EXPIRES'] = datetime.timedelta(minutes=30)
FAPP.config['JWT_REFRESH_COOKIE_PATH'] = os.environ['API_PATH']
FAPP.config['JWT_REFRESH_TOKEN_EXPIRES'] = datetime.timedelta(days=30)
FAPP.config['JWT_SESSION_COOKIE'] = False
FAPP.config['JWT_COOKIE_CSRF_PROTECT'] = True
FAPP.config['JWT_CSRF_METHODS'] = ['POST', 'PUT', 'PATCH', 'DELETE', 'GET']
```

The container specs for the server container are not identical for the local environment vs. the Jenkins environment, but base image and python-related packages installed are the same. Here are the key parts of the local test server container spec for each.

Local test environment (where the server application works correctly):

```
FROM ubuntu:16.04
LABEL maintainer="eric@wittlesouth.com" project="ourlifestories.net"
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential mysql-client libmysqlclient-dev curl sudo
ADD requirements.txt /
RUN pip3 install -r /requirements.txt
CMD ["bash", "-c", "${SERVER_COMMAND}"]
```

Jenkins test environment (where the above issue happens):

```
FROM ubuntu:16.04
LABEL maintainer="eric@wittlesouth.com" project="Roadmaps FTW"
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential mysql-client libmysqlclient-dev curl sudo
# Below doesn't seem to work to get time correct on server
# RUN sudo echo "America/New_York" > /etc/timezone
# RUN sudo dpkg-reconfigure -f noninteractive tzdata
ADD requirements.txt /
RUN pip3 install -r /requirements.txt
RUN mkdir /app
ADD src /app/
CMD ["bash", "-c", "${SERVER_COMMAND}"]
```

While it appears there is something in the way the Jenkins environment is set up is the problem, I have another project that uses Flask-JWT extended in the same manner, in the same environment, and that project passes all tests without showing any sign of this problem.

I hate filing this, because the fact that the same source works in one location but not another in project one, and the same testing strategy works in both environments on another project points to a problem in the configuration of the Jenkins environment where I'm having this issue. However, after many days of trying to figure it out, I'm out of ideas. Based on everything I can tell, the sample above shows a valid request with tokens, and I believe the 401 error is coming from the @jwt_refresh_token_required decorator, and I'm looking for help as to what to look for next.

Please help with my future sanity and suggest what I could look for next to find the root cause?

**Comment by vimalloc** [comment]
Hrm. That is interesting for sure, at a glance everything looks reasonable in your configs. It looks like your using a custom `unauthorized_loader`. An error string is passed as an argument to that function, which contains some details on why the `NoAuthorizationError` was raised. Could you log that string as well in your unit tests and see what it says? Maybe it could give us some information on whats going on here.

A more in depth option might be to create a custom decorator and use that in place of the refresh_jwt_required call to get some additional debugging information: Something like this (untested):

```python
def test_jwt_refresh_token_require(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            verify_jwt_refresh_token_in_request()
            return fn(*args, **kwargs)
        except Exception as e:
            logger.exception("test refresh required decorator stacktrace")
            raise
```

**Comment by wittlesouth** [comment]
Thanks for the fast reply. I'd re-read my post right before walking away to reset my brain. The details of the error message struck me; the error message says "no authorization token provided", which seemed in conflict with the decorator that is only checking for refresh token, not authorization token. That was clue one.

Clue two was having looked at the release doc, and seeing the change you made in 3.7.1 in the default setting for PROPAGATE_EXCEPTIONS. I'm not using flask-restful, but I am using zalando/connexion, so I thought I'd check to see if it was using flask-restful under the hood, and maybe the exception I was getting was somehow different than the root issue.

That lead me to noticing that zalando/connexion added OAuth 2 validation in their 2.0 release. My (failing) project is using Connexion 2.0.2; the older project that was working was using 1.1.10. New theory; the error might not be coming from flask-jwt-extended. So I dropped the Connexion version on my new project down to 1.1.10, and the test referenced above now passes in the Jenkins environment.

I haven't tracked down exactly what is happening yet, but it appears that the error is coming from Connexion rather than this project. Thanks for the suggestion above (although I haven't gotten to trying it yet), and when I track down what is really going on, I'll follow up. I'll close once I have something more definitive, but wanted to update this issue as soon as it seemed likely to not be flask-jwt-extended.

**Comment by vimalloc** [comment]
Sounds great, thanks for following up! Good luck getting this sorted :+1:

**Comment by vimalloc** [comment]
It sounds like this got resolved. I'm going to go ahead and close this issue now :+1:
