### ISSUE TITLE
Missing Authorization Header

### ISSUE THREAD

**Issue by guillaumeod** [vimalloc/flask-jwt-extended#21]
Hi,

I'm getting "Missing Authorization Header" when trying to access a jwt_refresh_token_required endpoint.
I'm using 'Authorization': 'Bearer ' with the refresh_token but it tells me "Missing Authorization Header"

`    public getNewJwt() {
        // Get a new JWT from the server
        let refresh_token = localStorage.getItem('access_token');
        let headers = new Headers({ 'Authorization': 'Bearer ' + refresh_token });
        this.result = this.http.post(this.refreshTokenApiUrl, refresh_token, headers)
            .map((response: Response) => response.json)
            .subscribe(result => this.result =result);
        console.log(this.result);
        return this.result;
    }`

What am I doing wrong :) ?

**Comment by vimalloc** [comment]
First thing I see, it looks like you are trying to use the access token as a refresh token, which will not work. You will need to pass in a refresh token here instead

```javascript
let refresh_token = localStorage.getItem('access_token');
```

That said, I would have expected that to return a different error along the lines of
```
Only refresh tokens can access this endpoint
```

Have you modified the ```JWT_HEADER_NAME``` or ```JWT_HEADER_TYPE``` in your app.config at all?

**Comment by vimalloc** [comment]
I had that error message hard coded to say "Missing Authorization Header", even if someone was using a different header name then authorization. I just pushed a new release (1.0.3) which fixes that, so it will instead say "Missing <custom_header_name> Header".

I'm not sure if this is what is causing your issue or not, but if it is, this should give more helpful error messages going forwards. If it isn't, let me know, and I would be more then happy to continue troubleshooting this with you :)

**Comment by vimalloc** [comment]
And one more thing it might be. I'm not really familiar with angular, but doing a quick look at some of their docs (https://angular.io/docs/ts/latest/guide/server-communication.html), I see this:

```javascript
    let headers = new Headers({ 'Content-Type': 'application/json' });
    let options = new RequestOptions({ headers: headers });

    return this.http.post(this.heroesUrl, { name }, options)
```

Is it possible you need to pass the ```RequestOptions``` to ```this.http.post``` instead of the ```Headers```? (I might be totally off the mark here)

**Comment by guillaumeod** [comment]
I think I didn't get the right error since the options were not passed, you were right about RequestOptions.

The endpoint works correctly since I manage to get the new access_token with cUrl.

However, I can't manage to get it with Angular 2, I'm getting a `422 UNPROCESSABLE ENTITY for URL` when trying to subscribe to the post request with the following error message `body: "{msg": "Invalid crypto padding}"`


```
    public getNewJwt() {
        let refresh_token = localStorage.getItem('refresh_token');
        let headers = new Headers({ 'Authorization': 'Bearer ' + refresh_token });
        let options = new RequestOptions({ headers: headers });

        this.newJWT = this.http.post(this.refreshTokenApiUrl, refresh_token, options)
                                .map((response: Response) => response.json());
        return this.newJWT;
    }
```

```
   this.jwtService.getNewJwt().subscribe(
                    (data) => {
                        // save the token in local storage
                        console.log(data);
                        let token = data.access_token;
                        localStorage.setItem('access_token', token);
                    }
                );
```

I'm clearly doing something wrong with the angular request, the extension works perfectly anyway :)

**Comment by vimalloc** [comment]
Glad you got that working! :) I'll keep a note of this in case other users report similar problems.

Cheers.

**Comment by dtytomi** [comment]
@skwidy thanks
