### ISSUE TITLE
Decode expired token

### ISSUE THREAD

**Issue by djk2** [vimalloc/flask-jwt-extended#210]
Hey everyone. 

I have a problem with a manage 'black list'. 
I using Redis as a key value store. 

1. After login, I add user token to list. 
`key_store.setex(access_jti, app.config['JWT_ACCESS_TOKEN_EXPIRES'], 'true')`

2. After when the token was expired and user 'click' on `logout` button I call end point and I try remove token from key store like that:
`
token = decode_token(encoded_token)
key_store.delete(token)
` 
but I can't decod `encoded_token` because I get exception `jwt.exceptions.ExpiredSignatureError: Signature has expired`

Conclusion is: I will never remove this token from store because this token was expired. 

Anybody can help me?
How decode a expired token?

**Comment by vimalloc** [comment]
Based on your code you shouldn't need to remove the token from redis. You are using redis `setex` command (https://redis.io/commands/setex), which will cause the token to be dropped from redis the specific time after it is expired without any manual deletion needing to happen..

**Comment by djk2** [comment]
Yes, I use `setex` but this doesyn't work properly. 
I will try explain the problem:

```python
app = Flask(__name__)
CORS(app)
api = Api(app)
jwt = JWTManager(app)

key_store = redis.StrictRedis(
    host=app.config['REDIS_HOST'],
    port=app.config['REDIS_PORT'],
    db=app.config['REDIS_DB'],
    decode_responses=app.config['REDIS_DECODE_RESPONSES'],
)

@jwt.token_in_blacklist_loader
def check_if_token_is_revoked(decrypted_token):
    jti = decrypted_token['jti']
    entry = key_store.get(jti)
    if entry is None:
        return True
    return entry != 'true'

@jwt.unauthorized_loader
def custom_unauthorized_loader_callback(callback):
    return jsonify({'message': 'No access'}), 401

@jwt.expired_token_loader
def custom_expired_token_loader_callback():
    return jsonify({'message': Session expired'}), 401
```

Endpoints:

```python
class Login(Resource):
    ....
    def post(self):
        ....
        access_token = create_access_token(
            identity=login, 
            expires_delta=app.config['JWT_ACCESS_TOKEN_EXPIRES']
        )
        refresh_token = create_refresh_token(
            identity=login, 
            expires_delta=app.config['JWT_REFRESH_TOKEN_EXPIRES']
        )
        access_jti = get_jti(encoded_token=access_token)
        refresh_jti = get_jti(encoded_token=refresh_token)
        key_store.setex(access_jti, app.config['JWT_ACCESS_TOKEN_EXPIRES'] * 1.1, 'true')
        key_store.setex(refresh_jti, app.config['JWT_REFRESH_TOKEN_EXPIRES'] * 1.1, 'true')
        ......

class Logout(Resource):

    def get(self):
        # Support for tokens and cookies
        token = request.args.get(app.config['JWT_QUERY_STRING_NAME']) 
        jti = get_raw_jwt().get('jti')

        if jti:
            key_store.delete(jti)
        if token:
            raw_token = decode_token(token)
            key_store.delete(token)
 
       ........

```

My env:
JWT_ACCESS_TOKEN_EXPIRES = 5 sec
JWT_REFRESH_TOKEN_EXPIRES = 5 sec

After login, everything work fine.
But when token expired (after 10 sec) and user call `Logout` endpoint then JWT raise ExpiredSignatureError.
I checked token in Redis and I confirm that Redis removed expired key but endpoint `Logout` still return exception ` ExpiredSignatureError`

**Comment by vimalloc** [comment]
Yes, that is by design and has nothing to do with blacklisting. By it's very nature an expired token should *not* be able to access a protected endpoint. At that point, the token is already invalid so the user is in essence already logged out, and in your specific example the token is also removed from redis so there shouldn't be any cleanup to do there.  I think it would make a lot more sense to just treat a 401 on the logout endpoint as an indication that you are, for all intensive purposes, already logged out, and have your front end handle it accordingly. Or alternately you could use a custom decorator https://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html) on just the logout endpoint to catch the `ExpiredSignatureError` and return a 200 instead of a 401 to your frontend.

**Comment by djk2** [comment]
OK, Thanks for reply. 
I will refactor my solution. 
Issue to close.
