### ISSUE TITLE
Multiple values JWT_ACCESS_COOKIE_PATH

### ISSUE THREAD

**Issue by msmicker** [vimalloc/flask-jwt-extended#224]
I am looking into updating a project from Flask-JWT and want to use cookies in flask jwt extended. I serve my API by reverse proxy through nginx under /api/. For my flask routes they are following a v1, v2 etc - e.g. as served from my python app they are /v1 /v2, but from nginx they are /api/v1 /api/v2. How might I handle multiple paths with this config? e.g. I'd like /v1, /v2

JWT_ACCESS_COOKIE_PATH

I tried passing an array but I get strange behavior.

**Comment by vimalloc** [comment]
The JWT_ACCESS_COOKIE_PATH option gets passed directly to the `set_cookie` function in flask: 
https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py#L242

I’m not sure how the same cookie name with different paths with flask behind the scenes, and I’m not seeing any documentation for this in flasks end right off hand. Do you have an example of how this should work using just flask?

**Comment by msmicker** [comment]
Thanks, I realize I should just fix my underlying problem with nginx reverse proxy and then I have no need for the multiple  paths.
