### ISSUE TITLE
CHANGELOG?

### ISSUE THREAD

**Issue by decaz** [vimalloc/flask-jwt-extended#227]
It would be very nice to see what had been changed since the last version to be aware of possible breaking changes.

**Comment by vimalloc** [comment]
I've been documenting all the changes here: https://github.com/vimalloc/flask-jwt-extended/releases

Do you think there would be a benefit to mirror those in a changelog file?

**Comment by decaz** [comment]
Sorry, didn't see it. It's enough for me but maybe someone would have the same problem as me, will leave it at your discretion. Thanks!

**Comment by vimalloc** [comment]
I've re-worded the readme to include a link to the release notes.

Cheers :+1:
