### ISSUE TITLE
get_jwt_identity() returning None

### ISSUE THREAD

**Issue by jcald1** [vimalloc/flask-jwt-extended#231]
I'm using Flask-JWT-Extended to protect my Flask API.  After the Login, in the protected route (add-user), I call get_jwt_identity(), but it's returning None, so I'm not able to get the identity.

    @flask_app.route('/<api_version>/login', methods=['POST'])
    def login(api_version):
        print(f'login', request.form)
        response = None
        try:
            username = request.form['username']
            password = request.form['password']
    
            if not username:
                return jsonify({"msg": "Missing username parameter"}), 400
            if not password:
                return jsonify({"msg": "Missing password parameter"}), 400
    
            user = User.get_with_password(username, password)
    
            if (not user):
                e1 = Unauthorized(
                    'Invalid username or password.  Please try again.')
                e1.status = 401
                raise e1
    
            """ flask_login.login_user(user, remember=True) """
            access_token = create_access_token(identity=username)
            response = json.dumps({"token": access_token}, cls=CustomJSONEncoder)
        except Exception as e:
            errMsg = f'Error Logging in user {username if username else ""}: {e}'
            status = e.status if hasattr(e, 'status') else 500
            print(f'{errMsg}')
            traceback.print_exc()
            return Response(
                json.dumps({"message": errMsg, "status": status, "stack": traceback.format_exc() }), status=status, mimetype='application/json')
            
    
        resp = Response(response, status=200, mimetype='application/json')
        return resp

    @flask_app.route('/<api_version>/add-user', methods=['POST'])
    @jwt_required
    def add_user(api_version):
        print(f'add-user', request)
        response = None
        username = None
        password = None
        allow_admin = None
        try:
            data = request.get_json()
            print(f'add-user data', data)
    
            if 'username' in data:
                username = data['username']
            else:
                return jsonify({"msg": "Missing username parameter"}), 400
            if 'password' in data:
                password = data['password']
            else:
                return jsonify({"msg": "Missing password parameter"}), 400
            if 'allow_admin' in data:
                allow_admin = data['allow_admin']
    
            """ user = User.get_with_password(username, password)"""
            user = get_jwt_identity()
            print('user',user)
    
            if (not user):
                e1 = Unauthorized(
                    'Invalid username or password.  Please try again.')
                e1.status = 401
                raise e1
    
            response = json.dumps({"user": user}, cls=CustomJSONEncoder)
        except Exception as e:
            errMsg = f'Error Adding User {username}: {e}'
            status = e.status if hasattr(e, 'status') else 500
            print(f'{errMsg}')
            traceback.print_exc()
            return Response(
                json.dumps({"message": errMsg, "status": status, "stack": traceback.format_exc() }), status=status, mimetype='application/json')
            
    
        resp = Response(response, status=200, mimetype='application/json')
        return resp

User.py
```
class User():
    @classmethod
    def get_with_password(cls, username, password):
        print(f'User get_with_password {username} with password')
        user_db = account.get_account(username)
        print(f'User returned from DB: {user_db}')

        user = User()
        if not user_db or not len(user_db) or (not 'password' in user_db):
            return None
        user.username = username
        user.id = username

        if bcrypt.check_password_hash(user_db['password'], password):

            user.role = user_db['role']
            #user.is_authenticated = True
            print(
                f'loginUser returning {vars(user)} ')
            return user
        return None

```

**Comment by vimalloc** [comment]
Did you set the identity of your access token to `None`? With this extension it shouldn't be possible to access a `@jwt_required` endpoint unless there is a valid access token, in which case `get_jwt_identity()` will return the identity of that token. If you try printing out `get_raw_jwt()` instead, do you see any data?

If that doesn't help, if you can provide a [minimal,  complete, and verifiable example](https://stackoverflow.com/help/mcve), as well as what versions of flask and flask-jwt-extended you have installed, that would a long way towards being able to troubleshoot this further. :+1:

**Comment by joeflack4** [comment]
I'm having this issue as well. I was also having the issue with Flask-JTW, which is why I switched to Flask-JTW-Extended (thanks for picking it back up!).

## Some code / logs
**Route**
```python
@jwt_required
@api.route('/biometric_data', methods=['POST'])
def create_biometric_data() -> jsonify:
    """Create new biometric data"""
        headers = request.headers  # Will show below
        x = get_current_user()  # None
        y = get_jwt_identity()  # None
        z = get_raw_jwt()  # {}
```

**Headers**
```
Host: localhost:5000
Connection: keep-alive
Content-Length: 46
Pragma: no-cache
Cache-Control: no-cache
Sec-Ch-Ua: Google Chrome 74
Sec-Fetch-Mode: cors
Origin: http://localhost:3000
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTkwMTE4NzksIm5iZiI6MTU1OTAxMTg3OSwianRpIjoiZDY4MDljNjQtMzczYy00MzY5LWI3YjQtNzA5N2E0MDc0ODRhIiwiZXhwIjoxNTU5MDEyNzc5LCJpZGVudGl0eSI6ImpvZWZsYWNrNEBnbWFpbC5jb20iLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ._YM91F-d3x1cwe_pssvQK6x1nk_vD00XqOEuYBDoXog
Content-Type: application/json
Accept: application/json
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Sec-Fetch-User: ?F
Sec-Fetch-Site: same-site
Dnt: 1
Referer: http://localhost:3000/health-record-new
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7,ja-JP;q=0.6,ja;q=0.5
```

## Things I've tried
- Tried double checking that identity was being set correctly. During debugging, it did indeed seem to be.
- Double checked that what was in auth_token supplied was originally the same auth_token originally created for the user session. It was.
- Flipping the decorators. But it wouldn't work. If I put the 'route' decorator above `jwt_required`, I get the following error.
Server:
```
127.0.0.1 - - [27/May/2019 23:09:39] "POST /v1/biometric_data HTTP/1.1" 422 -
```
Client:
```
POST http://localhost:5000/v1/biometric_data 422 (UNPROCESSABLE ENTITY)
```

## Possible solutions I can think of
- Is the issue my decorator order? Why does it show an error when I flip the order as mentioned above?

**Comment by vimalloc** [comment]
Ah, yeah that would absolutely do it. If the `@app.route()` decorator comes before `@jwt_required`, then that would mean that the view function runs first, then the jwt_required call comes second, after your view function has already run. That is why you aren't seeing any data from the `get_current_user()` etc functions, because the data hasn't been processed by flask_jwt_extended prior to your view function being called. 

As for the 422 status code when the decorators are switched, that probably means that the token is invalid for some reason. That is the error code used by default when any invalid token attempts to use access a protected endpoint (https://github.com/vimalloc/flask-jwt-extended/blob/ea98fccf65981ac0516329c0b78bb9a25d7011e3/flask_jwt_extended/default_callbacks.py#L45). If you can look at the JSON body of whatever is making the request to your flask API, is should give you some information about why the token is invalid (malformed, expired, etc).

**Comment by joeflack4** [comment]
{
  "msg": "Missing Authorization Header"
}

**Comment by joeflack4** [comment]
Thanks for the very fast and helpful response! Was not expected. Let me get cracking on this and get back to you.

**Comment by vimalloc** [comment]
Sure thing! That error means the token cannot be found in the headers with the config values specified in flask-jwt-extend:

https://github.com/vimalloc/flask-jwt-extended/blob/67de379bc2184fa042aa4202034f3572fb750293/flask_jwt_extended/view_decorators.py#L173-L175

Make sure that the header name that you are sending the token in as matches up with the `JWT_HEADER_NAME` config option: https://flask-jwt-extended.readthedocs.io/en/latest/options.html

**Comment by joeflack4** [comment]
Actually, I'm getting the `InvalidHeaderError` with the message:

> 'Bad Authorization header. Expected value \\'Bearer <JWT>\\''

I'm in the debugger at line ~186 in the `_decode_jwt_from_headers` function of the `view_decorators` module.

Here's a screenshot from my debugger there:
<img width="451" alt="Screen Shot 2019-05-27 at 11 49 55 PM" src="https://user-images.githubusercontent.com/13045020/58449792-3744ea80-80da-11e9-9a9b-bdbd1abc5eed.png">

**Comment by joeflack4** [comment]
Here's the request I'm making in my client application, if you're interested:
```javascript
    axios.post(
      url,
      this.state, {
      headers: {
        'authorization': authToken,
        'Accept' : 'application/json',
        'Content-Type': 'application/json'
    }})
    .then(function (response) {
      console.log(response);
    })
    .catch(function (error) {
      console.log(error);
    });
```

**Comment by vimalloc** [comment]
By default flask_jwt_extended expects the tokens to be in the format of `Authorization: Bearer <JWT>`. You can either change your frontend to include the `Bearer` there, or set `app.config['JWT_HEADER_TYPE'] = None` to make it expect the format of `Authorization: <JWT>`.

**Comment by joeflack4** [comment]
Thanks. I will try that!

It's a shame neither my client or server are printing out the error message, The client says `POST http://localhost:5000/v1/biometric_data 422 (UNPROCESSABLE ENTITY)`. And the server says `127.0.0.1 - - [27/May/2019 23:43:29] "OPTIONS /v1/biometric_data HTTP/1.1" 200 -`. If it included the raised error message, I could have probably figured it out.

**Comment by vimalloc** [comment]
You normally don't want the server to log messages in responses, it could lead to sensitive information being logged. I can't speak to the javascript though 😛

**Comment by joeflack4** [comment]
Hmm, I think that makes sense in this case since it is not a `500`. Also, it works now!

**Comment by vimalloc** [comment]
For future reference, it looks like you should be doing `console.log(error.response)` to fix that in your javascript, per https://github.com/axios/axios/issues/960 👍

**Comment by joeflack4** [comment]
That's really nice of you to look deeper! I just figured that out a moment ago. Indeed, that worked for me.
