### ISSUE TITLE
flask_jwt_extended.exceptions.JWTDecodeError: Missing claim: fresh

### ISSUE THREAD

**Issue by sraghavan-eqix** [vimalloc/flask-jwt-extended#235]
File "/home/demo/.local/lib/python3.5/site-packages/Flask_JWT_Extended-3.7.2-py3.5.egg/flask_jwt_extended/tokens.py", line 126, in decode_jwt
    raise JWTDecodeError("Missing claim: fresh")
flask_jwt_extended.exceptions.JWTDecodeError: Missing claim: fresh

Getting the above error while hitting an API in flask

This is my requirements.txt for running setup.py in Python
aniso8601==4.0.1
Click==7.0
Flask==1.0.2
flask-restplus==0.12.1
Flask-SQLAlchemy==2.1
gunicorn==19.9.0
itsdangerous==1.1.0
Jinja2==2.10
jsonschema==2.6.0
MarkupSafe==1.1.0
psycopg2==2.7.6.1
pytz==2018.7
six==1.11.0
SQLAlchemy==1.2.14
Werkzeug==0.14.1
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
kubernetes==8.0.1
grpcio>=1.19.0
grpcio-tools==1.19.0
protobuf==3.7.0
supermutes==0.2.5
boto3==1.0.0
botocore==1.0.0
google-auth==1.6.3
pyhelm==0.0.9
helm-charts==1.0.15
certifi>=2017.4.17
logger==1.4
Flask-JWT-Extended==3.7.2
jwt==0.6.1
PyJWT==1.6.1
Flask-JWT==0.2.0

Get the same error even if below are removed from requirements.txt
jwt==0.6.1
PyJWT==1.6.1
Flask-JWT==0.2.0

Method or API:
 @jwt_required
    @app.errorhandler(400)
    def post(self):

**Comment by vimalloc** [comment]
At a glance there looks like there is a lot of old or unnecessary things in your requirements.txt. I would suggest completely removing your virtual environment and recreating a new one, installing the newest version of this extension (currently 3.18.0).

Also, you probably shouldn't have an `@jwt_require` and `@app.errorhandler(400)` on the same function.

**Comment by sraghavan-eqix** [comment]
Thanks, it gets resolved but however I keep getting this error more than often.
except jwt.ExpiredSignatureError:
AttributeError: 'JWTManager' object has no attribute 'ExpiredSignatureError'

This is my requirements.txt now
Flask==1.0.2
flask-restplus==0.12.1
Flask-SQLAlchemy==2.1
psycopg2==2.7.6.1
SQLAlchemy==1.2.14
PyYAML==3.13
requests==2.21.0
kubernetes==8.0.1
certifi>=2017.4.17
Flask-JWT-Extended==3.18.0

This is using a new docker image that am building using the requirements.txt

**Comment by vimalloc** [comment]
How did you generate your requirements.txt? It is missing dependencies needed by flask-jwt-extended, such as six and PyJWT.

**Comment by sraghavan-eqix** [comment]
I am using a python 3.7 image for docker and copying the project folder with requirements.txt(defined) as shown above and running the setup.py to create the distribution.
I had to comment out the part below to stop the exception. The dependancies needed for Flask-JWT are already installed as I can see under site-packages that extra libraries like six-1.12.0-py3.5.egg
 and PYJWT 1.7.1 are also present after the installation.


 # except jwt.ExpiredSignatureError:
        #     return 'Signature expired. Please log in again.'
        # except jwt.InvalidTokenError:
        #     return 'Invalid token. Please log in again.'

**Comment by vimalloc** [comment]
> `AttributeError: 'JWTManager' object has no attribute 'ExpiredSignatureError'

I think you have something funky going on here, that exception comes from pyjwt not JWTManager. Do you have a file called `jwt.py` that might be getting imported instead? If not, can you provide a minimal, complete, and verifiable example so I could help troubleshoot this further?

Thanks.
