### ISSUE TITLE
How to redirect to login when getting "Signature verification failed"?

### ISSUE THREAD

**Issue by kwagdy** [vimalloc/flask-jwt-extended#236]
When testing tampering with access token, the page shows the error "msg": "Signature verification failed"
We'd like to redirect the user to login page instead, we tried using the below decorators as described in the [Changing Default Behaviors docs](https://flask-jwt-extended.readthedocs.io/en/latest/changing_default_behavior.html):
@jwt.**invalid_token_loader** _...raises: "TypeError: invalid_token_callback() takes 0 positional arguments but 1 was given"_
@jwt.**expired_token_loader**
@jwt.**handle_expired_error**
@jwt.**claims_verification_failed_loader**

But non worked

**Comment by carc1n0gen** [comment]
The function you decorate with `@jwt.invalid_token_loader` must accept one argument, which is a string according to the docs: 

https://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.invalid_token_loader

**Comment by kwagdy** [comment]
@carc1n0gen thank you! I overlooked that! It works now :)
Really well done with the extension and documentation
