### ISSUE TITLE
Exception error related to PyJWT version

### ISSUE THREAD

**Issue by abathur** [vimalloc/flask-jwt-extended#238]
I'm not sure if this needs action, but I wanted to report it since it took us a few minutes to figure out and the note might spare someone else. We have a test/preview environment  and recently pushed an update there that moved to a newer version of Flask-JWT-Extended (I'm not certain what this system was running before), and also added an error handler for `InvalidSignatureError`. We started seeing the following error:
```
@api.errorhandler(jwt_exception.InvalidSignatureError)
AttributeError: module 'jwt.exceptions' has no attribute 'InvalidSignatureError'
```

The ultimate issue was a difference between the installed versions of PyJWT; it's running fine in my dev environment with `PyJWT==1.6.4`, and the trouble environment had `PyJWT==1.5.3`. 

I wondered when I bumped into this if any of the other hard-to-reproduce issues that have been reported might also come down to PyJWT version differences.

**Comment by vimalloc** [comment]
Awesome, thanks for the error report! I'll update the required dependencies of this extension to include `PyJWT >= 1.6.4`!
