### ISSUE TITLE
Request: Best practices to secure your application using flask-jwt-extended

### ISSUE THREAD

**Issue by kwagdy** [vimalloc/flask-jwt-extended#239]
This is not an issue but rather a request. Can we work on a guide, step-by-step example, further documentation for a prod scenario (or a few!) on securing the application using flask-jwt-extended? On the top of my mind this could include a quick step by step guide of basic prod-grade setup with a few explanation of different kinds of attacks and how they can be mitigated using the different functions, decorators, configurations.

The reason behind this is that one can find lots of resources on JWT, access token & refresh token, yet they are quite scattered and information doesn't seem to be consolidated in a clear way specially for new to JWT folks who wants the best of both worlds, user experience & security.

I have already went through a few articles (_see below_), but I still find the entire topic daunting to some extent with major worries about different _"what if"_ scenarios.

**Some of the articles I went through about the topic:**
_(in no particular order)_ 
[JWT (JSON Web Token) automatic prolongation of expiration](https://stackoverflow.com/questions/26739167/jwt-json-web-token-automatic-prolongation-of-expiration?rq=1)
[How is a refresh token more secure than a long lived JWT?](https://stackoverflow.com/questions/48508257/how-is-a-refresh-token-more-secure-than-a-long-lived-jwt)
[what's the point of refresh token?](https://stackoverflow.com/questions/10703532/whats-the-point-of-refresh-token?noredirect=1&lq=1)
[Why Does OAuth v2 Have Both Access and Refresh Tokens?](https://stackoverflow.com/questions/3487991/why-does-oauth-v2-have-both-access-and-refresh-tokens)
[How to securely keep my users signed in with refresh tokens?](https://stackoverflow.com/questions/32903312/how-to-securely-keep-my-users-signed-in-with-refresh-tokens?noredirect=1&lq=1)
[Is a Refresh Token really necessary when using JWT token authentication?](https://stackoverflow.com/questions/32060478/is-a-refresh-token-really-necessary-when-using-jwt-token-authentication)
[Your API-Centric Web App Is Probably Not Safe Against XSS and CSRF](http://www.redotheweb.com/2015/11/09/api-security.html)
[Refresh token should provide a new refresh token as well?](https://github.com/vimalloc/flask-jwt-extended/issues/9)
[What Happens If Your JWT Is Stolen?](https://developer.okta.com/blog/2018/06/20/what-happens-if-your-jwt-is-stolen)
[How secure are expiring tokens and refresh tokens?](https://security.stackexchange.com/questions/87119/how-secure-are-expiring-tokens-and-refresh-tokens)
[How does a refresh token help? [duplicate]](https://security.stackexchange.com/questions/113273/how-does-a-refresh-token-help)

**Comment by vimalloc** [comment]
That would be an awesome thing to have. Unfortunately due to time constraints I don't think it's something I would be able to work on in the foreseeable future. If you (or anyone else) wants to throw something together though and make a pull request to the docs I would be more then happy to work with you to get it merged.

Cheers! :+1:

**Comment by kwagdy** [comment]
I'd love to work on this yes, Would you be able to help me at least with the outlines? I can start writing docs with example code if I have some outline, quick bullet points should do the trick

**Comment by vimalloc** [comment]
Sorry I never got back to you here, it slipped through the cracks then I totally forgot about it.

I'm going to close this issue for now, if anyone does want to tackle this and has questions, please come ask in our gitter channel and we will help out as best we can :+1:
