### ISSUE TITLE
Use gunicorn multiple workers and use different secret_key value will have different result

### ISSUE THREAD

**Issue by memory-yancy** [vimalloc/flask-jwt-extended#240]
Thanks your great efforts for flask using JWT easily! I meet issues about `gunicorn` and `flask_jwt_extended`:

```
(python35) [yancy@asus tmp]$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

(python35) [yancy@asus tmp]$ pip freeze |grep -i jwt
Flask-JWT-Extended==3.18.0
PyJWT==1.4.2
(python35) [yancy@asus tmp]$ pip freeze |grep -i gunicorn
gunicorn==19.9.0
(python35) [yancy@asus tmp]$ flask  --version
Flask 1.0.2
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0]
```
```
(python35) [yancy@asus tmp]$ cat nuist.py 
# coding: utf-8

import datetime, os
from flask import Flask, request, jsonify
from flask_jwt_extended import JWTManager, jwt_required, create_access_token, get_jwt_identity

app = Flask(__name__)

####################
# app.secret_key = os.urandom(40)
app.secret_key = 'fixed_value'
####################

app.config.update({'JWT_ACCESS_TOKEN_EXPIRES': datetime.timedelta(days=1)})
jwt = JWTManager(app)

@app.route('/login', methods=['POST'])
def login():
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    if not (username and password):
        return jsonify({"msg": "Missing parameter"}), 422
    access_token = create_access_token(identity=username)
    return jsonify(access_token=access_token), 200

@app.route('/protected', methods=['GET'])
@jwt_required
def protected():
    current_user = get_jwt_identity()
    return jsonify(logged_in_as=current_user), 200
```
* Set `secret_key=os.urandom(40)` :
1. Start flask app `gunicorn --worker-class sync --workers 1 --timeout 120 nuist:app --bind :5000 --reload --log-level debug`, everything is ok(That's say, everytime request is ok using got token)
2. Start flask app `gunicorn --worker-class sync --workers 2 --timeout 120 nuist:app --bind :5000 --reload --log-level debug`, parts of request will fail (That's say, try multiple times using got token).

About second case, if gunicorn workers `>` 1(I have tested 2-5), above issues will be reported. If a flask app errorhandle `DecodeError('Signature verification failed')` error when user want to login in, this will always lead to user login unsuccessfully. 

```
(python35) [yancy@asus tmp]$ http --body GET 127.0.0.1:5000/protected "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY1NTA0NTYsImlhdCI6MTU1NjQ2NDA1NiwianRpIjoiODM4ZjBiMGQtMjRjNy00MTVmLWI4OGUtNGZiNTEzZWUyMWY0IiwidHlwZSI6ImFjY2VzcyIsImlkZW50aXR5IjoidGVzdCIsIm5iZiI6MTU1NjQ2NDA1NiwiZnJlc2giOmZhbHNlfQ.builYWDJnDAwe1BkV9lYrphvKSQp19oCYSoHlpjO0_w"
{
    "msg": "Signature verification failed"
}
```

* Set `secret_key='hardcode_value'`:
1. `gunicorn --worker-class sync --workers 1 --timeout 120 nuist:app --bind :5000 --reload --log-level debug`, everything is ok(everytime request is also ok).

2. `gunicorn --worker-class sync --workers 2 --timeout 120 nuist:app --bind :5000 --reload --log-level debug`, everything is ok(everytime request is also ok)

Since `secret_key` should be changed in production env. So, have any good ideas, thanks again great efforts !

**Comment by vimalloc** [comment]
Using  `secret_key=os.urandom(40)` to generate keys is a bad idea. Not only will it break with multiple processes/server (as you have seen), it will also mean all your users get logged out if you ever need to restart the service. Instead, you should use a dedicated secret key in production, which is shared between all instances of the application. Take a look at the official flask docs for some inspiration on handling configuration in development and production: http://flask.pocoo.org/docs/1.0/config/#development-production

**Comment by memory-yancy** [comment]
@vimalloc   I am curious about `break with multiple processes/server`. Can answer my doubts about some request will fail when I use `os.urandom(40) and workers number > 1`

According to my understanding, since flask app is started, `secret_key=os.urandom(40)` will be stored in memory. If I do not generate it again, `secret_key` value will changed(I do not restart my flask app in above test case). If I use `os.urandom(40) and workers number > 1`, test will fail, why???

 (**NOTE: my flask app is always running, I do not restart it.** That's to say, I start my flask app in Linux terminal 001 tab(flask app is OK), I use `http` to test API in Linux terminal 002 tab. Sometimes, some request will fail in 002 tab)

> it will also mean all your users get logged out if you ever need to restart the service

About it, I can go through your source code callback to understand deeply about JWT. `(def _verify_signature)`

> it break with multiple processes/server (as you have seen)

About it, can you provides any tips or guide ? From flask app debug info, I do not see any restart app info are printed using gunicorn DEBUG mode. So, it is curious. Real thanks for your help !
```
... ...
[2019-05-05 23:04:12 +0800] [18679] [DEBUG] POST /login
[2019-05-05 23:04:41 +0800] [18679] [DEBUG] GET /protected
[2019-05-05 23:04:44 +0800] [18679] [DEBUG] GET /protected
[2019-05-05 23:04:45 +0800] [18680] [DEBUG] GET /protected
[2019-05-05 23:04:52 +0800] [18680] [DEBUG] GET /protected
[2019-05-05 23:04:53 +0800] [18680] [DEBUG] GET /protected
[2019-05-05 23:04:55 +0800] [18679] [DEBUG] GET /protected
```

**Comment by memory-yancy** [comment]
Suddenly find some tips from PID :)

Since I have gotten token in `18679` PID, some request is OK if PID == 18679. Yes, I have tested it, result is OK!
```
[2019-05-05 23:04:12 +0800] [18679] [DEBUG] POST /login
[2019-05-05 23:04:41 +0800] [18679] [DEBUG] GET /protected
```
If some request's PID == 18680, result will fail. Because I do not get token from PID == 18680
```
[2019-05-05 23:04:53 +0800] [18680] [DEBUG] GET /protected
```
