### ISSUE TITLE
Default cookie expiration way too long

### ISSUE THREAD

**Issue by allen-cook** [vimalloc/flask-jwt-extended#243]
When you set 
`JWT_SESSION_COOKIE = False` to enable permanent cookies, the expiration date set by default is way too long and the browser will sometimes treat it as invalid and set the cookie as a session cookie anyway.

Expiration dates on permanent cookies typically need to be before 2038 since it's specified in a UNIX epoch format.

**Comment by vimalloc** [comment]
I was not aware of that, great find! Do you want to put together a pull request to get that fixed up? Should be as simple as changing the value here (https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/config.py#L280) then adding/updating a unit test for the config value.

**Comment by vimalloc** [comment]
Released in version 3.18.2. Cheers!
