### ISSUE TITLE
Valid way to raise exception in callbacks

### ISSUE THREAD

**Issue by michaeltoohig** [vimalloc/flask-jwt-extended#245]
Is there a way I can raise an exception in invalid_token_loader and others? I use some exceptions to return messages via flask error handlers.

I could just rewrite my exception response in the callback but I was hoping to avoid doing that.

Thanks.

**Comment by vimalloc** [comment]
The `invalid_token_loader` et all are actually just flask error handlers behind the scenes. I'm unsure if an exception raised from one error handler will go through the error handler logic again and be caught by another error handler. If that isn't the case, you could use a custom view decorator instead for handling errors, something along these lines:

```python
from flask_jwt_extended import verify_jwt_in_request

def custom_jwt_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            verify_jwt_in_request()
            return fn(*args, **kwargs)
        except InvalidTokenError:
            raise YouCustomExceptionHere
    return wrapper

# Using it in a route
@app.route('/foobar', methods=['POST'])
@custom_jwt_required
def foobar():
    return jsonify(foo='bar')
```

The documentation for custom decorators can be found here (https://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html), and you can see the exceptions that we are registering flask error handlers for here (https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/jwt_manager.py#L84).
