### ISSUE TITLE
missing CRFS Tokens

### ISSUE THREAD

**Issue by jasonkolodziej** [vimalloc/flask-jwt-extended#247]
from `examples/csrf_protection_with_cookies.py`
...
```
@app.route('/token/refresh', methods=['POST'])
@jwt_refresh_token_required
def refresh():
    # Create the new access token
    current_user = get_jwt_identity()
    access_token = create_access_token(identity=current_user)

    # Set the access JWT and CSRF double submit protection cookies
    # in this response
    resp = jsonify({'refresh': True})
    set_access_cookies(resp, access_token)
    return resp, 200
```
When using Postman, I try placing a POST request on "localhost:5000/token/refresh" and I receive an error saying

>{"msg":"Missing CSRF token in headers"}

I am fairly new to messing with JWT could someone please correct my actions and perhaps an explanation?

I would greatly appreciate it (^:

**Comment by vimalloc** [comment]
In order for the csrfprotection to work, you need to grab the csrf token using javascript in your frontend and include it as an additional header when making requests to your flask backend. See this for some more details: https://github.com/vimalloc/flask-jwt-extended/issues/150#issuecomment-387613243

**Comment by andreixk** [comment]
what is the name of the header that needs to be sent?

**Comment by vimalloc** [comment]
@andreixk it defaults to `X-CSRF-TOKEN`, and can be changed via `*_CSRF_HEADER_NAMES` options outlined here: https://flask-jwt-extended.readthedocs.io/en/stable/options/#cross-site-request-forgery-options
