### ISSUE TITLE
create_access_token() 

### ISSUE THREAD

**Issue by maei1337** [vimalloc/flask-jwt-extended#250]
hi all,

its really confusing i changed nothing in the code, but create_access_token() doesnt work anymore. refresh token works fine.

any suggestions? just changed from macos to windows 10...but the code is deployed in a docker container, so dont know what is happening. on my old mac lap the docker and the create_access_token works fine...

**Comment by vimalloc** [comment]
I'm not doing anything OS specific in this library, so I don't know why it would be working in one place and not the other for you. If you can give some more information, such as a minimal complete and verifiable example that shows this issue, and/or the stacktrace of the error you are seeing, that would go a long way towards being able to help more with this.
