### ISSUE TITLE
nginx + uwsgi + flask + flask-jwt-extended issue when posting larger bodies/files

### ISSUE THREAD

**Issue by Panaetius** [vimalloc/flask-jwt-extended#253]
So I ran into an issue when running a flaks app with flask-jwt-extended in nginx with wsgi.

I'll try to be as verbose an exhaustive as possible so people might find this post in the future, as it cost me ~3 days to figure all the parts that lead to this issue.

This issue happens when sending a large POST request to an endpoint that requires JWT authorization but when the corresponding token is expired. 

The ultimate symptom of this is that nginx will return the correct 401 status code, but without sending the `{"msg": "The token expired"}` body, which would, for instance, cause an XmlHTttpRequest in javascript to fail with a `Network Error` instead of actually getting a response with the 401 status code, making it impossible to automatically react to expired tokens in the client by logging out/refreshing the token etc.

In the nginx log this is shown by the (not very helpful) error message:
```16#16: *35 readv() failed (104: Connection reset by peer) while reading upstream, client: 172.18.0.1, server: , request: "POST /Audiofile.create HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "localhost:8081", referrer: "http://localhost:8080/"```

What's causing this/steps that happen to cause this:

-  User send a POST request to a jwt protected endpoint in flask with a POST body (or file) larger than the uwsgi `buffer-size` (max of 64kb)
- nginx receives the request and passes it on to uwsgi in chunks/buffered. The first chunk contains all the request headers and some initial data from the POST body, but not all. The connection is kept open to continue sending the rest of the data
- uwsgi receives the first chunk and passes it to flask
- flask passes this first chunk to the flask-jwt-extended handler that reads the headers and determines the token is invalid/missing/revoked/etc.
- flask-jwt-extended return a Status of 401 with a body of `{"msg": "token is invalid"}` (Or corresponding message) to uwsgi, **without consuming the rest of the post body that nginx is still waiting to send**
- uwsgi opens a connection to nginx with the response body
- nginx receives the response, but as it still has a connection for the request open that hasn't finished, it concludes that uwsgi crashed or isn't reacting, leading to the `Connection reset by peer` error seen above. nginx only send the status code but doesn't read the response body from uwsgi
- the client receives the empty response from nginx, which causes most clients (Postman, XmlHttpRequest) to fail.

There is an easy workaround that I found which is to force uwsgi to consume the whole POST body before passing a request to flask, this can be done by setting `post-buffering` as mentioned here: https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html 
But this might not work in all scenarios, as it may break things. From the uwsgi docs: "enabling it breaks websockets, chunked input, upload progress, iceast streaming and so on."

Another way to fix this is to change the flask-jwt-extended handlers to consume the post body. This is as simple as calling `request.form` on a separate line (forcing flask to access the body) before returning the 401 response.

A workaround using this would be:

```
from flask_jwt_extended import JWTManager
from flask import request, Flask
from flask_jwt_extended.default_callbacks import (
    default_revoked_token_callback,
    default_expired_token_callback,
    default_invalid_token_callback,
    default_unauthorized_callback
)

app = Flask(__name__)
jwt = JWTManager(app)

# fix handling of large post bodies when running in flask/uwsgi by using custom handlers that consume
# the post body. See: https://stackoverflow.com/questions/3970495/nginx-connection-reset-response-from-uwsgi-lost


@jwt.expired_token_loader
def expired_token_callback(expired_token):
    request.form
    return default_expired_token_callback(expired_token)


@jwt.invalid_token_loader
def invalid_token_callback(error_string):
    request.form
    return default_invalid_token_callback(error_string)


@jwt.unauthorized_loader
def unauthorized_token_callback(error_string):
    request.form
    return default_unauthorized_callback(error_string)


@jwt.revoked_token_loader
def revoked_token_callback():
    request.form
    return default_revoked_token_callback()

```

Another solution I saw is passing `Expire: 100-continue` headers with the POST request, but this is not suppoerted in all clients and not recommended.

There might be a way for nginx to  successfully deal with the prematurely terminated connection, but I haven't found a solution that works, though there are several stackoverflow answer that suggest solutions. But as I said, none of them work.

And easy way to reproduce this issue would be to use the https://github.com/tiangolo/uwsgi-nginx-flask-docker docker image and to host a flask app there with a jwt-protected POST endpoint and a file upload, and uploading a file larger than ~1mb.

This post is mostly as a post-mortem in case someone runs into the same issue, though it might be nice to add the fix mentioned above to flask-jwt-extended, just to prevent it from happening and saving users the hassle of solving it.

This might also be the cause of #174

**Comment by vimalloc** [comment]
Ugh, yeah the uwsgi stuff can be a right pain. Nice job figuring that out, and thanks for documenting it here, hopefully that can help someone else in the future. For documentation sake in case anyone else runs into this, you might want to consider using `request.data` instead of`request.form`, which would make this work for any mimetype in the requests body.

Another option that I think would work that might be more future proof then modifying the loader calls like you did in your resolution would be to use a flask `before_request` to read the `request.data` prior to any protected endpoints being called. That would have the benefit of working even if new callbacks were added to this extension in the future. I am unsure if that would have consequences for any other part of your application though.

**Comment by Panaetius** [comment]
Thank you for your reply!

I can confirm that consuming `request.data` in `before_request` works, as in:

```
    @app.before_request
    def consume_request_body():
        """ Consumes the request body before handling a request to fix uwsgi+nginx problems
        See https://github.com/vimalloc/flask-jwt-extended/issues/253#issuecomment-505222118
        for more details """
        request.data
```

**Comment by vimalloc** [comment]
With the issue resolved I'm going to go ahead and close this. I'll make sure to link to this issue for any similar problems that show up in the future.

Thanks again for extensive details documented here here! :+1:
