### ISSUE TITLE
How to use the JWT of another application?

### ISSUE THREAD

**Issue by Jonyorker** [vimalloc/flask-jwt-extended#259]
Hi,

I am building a API for a project that uses thingsboard.io.

Their JWT has an ISS value, and from what I understand, the ISS values must match in order to decode.

Is it possible to set the ISS in the flask app to match that of our front end?

Thanks!

**Comment by vimalloc** [comment]
There is not currently a way to do that, but it would be completely trivial to add a config option for the issuer, similar to how `JWT_DECODE_AUDIENCE` works. If you want to make a pull request for that I would be happy to get it merged and a new release cut. I can also add this when I can find some time, probably within the next week. 

Cheers :+1:
