### ISSUE TITLE
Getting a "Missing claim: identity" message when using RS256 with jti present

### ISSUE THREAD

**Issue by durchgedreht** [vimalloc/flask-jwt-extended#264]
Hi,
I was following the tutorial for creating and consuming JWT tokens using jwt_extended:
https://codeburst.io/jwt-authorization-in-flask-c63c1acf4eeb
https://github.com/oleg-agapov/flask-jwt-auth
(Kudos for these docs - they worked perfectly and gave a quick intro!)

I now modified the code to adapt our use-case: We want to use SSO from Laravelle Framework to Flask. So tokens are generated from Laravelle and used by jwt_extended only using HTTP header with bearer token. HS256 works, but we need to use RS256 (given requirement). The changes work so far, but I always get a "Missing claim: identity" message.

The token has jti set and also in https://jwt.io/#debugger-io?... I can verify it's there. Also decoding works as I just fixed the audience claim and now have the JTI issue. My decrypted JWT payload in dev looks like follows 
 `{
  "aud": "1",
  "jti": "c08997d33657aaeffb77968f724db7aa878c025006b69e56cf4ec04df49562870992a76cb33d42e6",
  "iat": 1564745708,
  "nbf": 1564745708,
  "exp": 1596368108,
  "sub": "1",
  "scopes": [],
  "user": {
    "id": 1,
    "account_id": 1,
    "creator_id": null,
    "login": "admin@email.com",
    "status": "created",
    "archived_at": null,
    "created_at": "2019-07-24 09:52:55",
    "updated_at": "2019-08-02 11:19:35"
  }
}` 

Any hint would be appreciated. Although not optimal a workaround like declaring the claim optional would do it for now. THX.

Environment Infos:
OsX 10.14
venv Python 3.6.5
Package            Version
------------------ -------
aniso8601          7.0.0  
asn1crypto         0.24.0 
cffi               1.12.3 
Click              7.0    
cryptography       2.7    
Flask              1.1.1  
Flask-JWT-Extended 3.20.0 
Flask-RESTful      0.3.7  
Flask-SQLAlchemy   2.4.0  
itsdangerous       1.1.0  
Jinja2             2.10.1 
MarkupSafe         1.1.1  
passlib            1.7.1  
pip                19.2.1 
pyasn1             0.4.6  
pycparser          2.19   
PyJWT              1.7.1  
pytz               2019.1 
rsa                4.0    
setuptools         41.0.1 
six                1.12.0 
SQLAlchemy         1.3.6  
Werkzeug           0.15.5 
wheel              0.33.4

**Comment by durchgedreht** [comment]
After reading the RFC and then the sourcecode this did the trick:
`app.config['JWT_IDENTITY_CLAIM'] = 'jti'
`
Didn't know it's configurable. Might be a good idea to fallback to the standard if it's not optional (Convention Over Configuration). Any thoughts? It seems it falls back to identity instead of jti as decribed in https://tools.ietf.org/html/rfc7519#section-4.1.7

**Comment by vimalloc** [comment]
The `JWT_IDENTITY_CLAIM` should actually be `'sub'` per the spec. By default, this extension looks for it as `identity` because that's how I originally had it and didn't want to cause a breaking change for users by changing it, but I do mention it in the docs that it is recommended to change it to `sub`.

You can do so via `app.config['JWT_IDENTITY_CLAIM'] = 'sub'` and I expect this would work for you.

**Comment by durchgedreht** [comment]
Hi,
thanks for answering though I'm not sure if standardisation should have precedence, but I understand the issue. So all good with me.

But to my knowledge sub and jti are different identities (JWT vs principal) and I didn't find any info underlying to the "sub is jti" statement. If anyone stumbles across this and can point me to the change, that would be great. (Don't want to be nitpicking, just out of interest to not implement things upside down - the jwt_extended lib is really awesome, thanks for all the work!).

Wikipedia (might be good to change this if not accurate):
sub (Subject) - Identifies the subject of the JWT.
jti (JWT Id) Case sensitive unique identifier of the token even among different issuers.

Cite from the spec (https://tools.ietf.org/html/rfc7519#section-4.1.2):

4.1.2.  "sub" (Subject) Claim

   The "sub" (subject) claim identifies the principal that is the
   subject of the JWT.  The claims in a JWT are normally statements
   about the subject.  The subject value MUST either be scoped to be
   locally unique in the context of the issuer or be globally unique.
   The processing of this claim is generally application specific.  The
   "sub" value is a case-sensitive string containing a StringOrURI
   value.  Use of this claim is OPTIONAL.

4.1.7.  "jti" (JWT ID) Claim

   The "jti" (JWT ID) claim provides a unique identifier for the JWT.
   The identifier value MUST be assigned in a manner that ensures that
   there is a negligible probability that the same value will be
   accidentally assigned to a different data object; if the application
   uses multiple issuers, collisions MUST be prevented among values
   produced by different issuers as well.  The "jti" claim can be used
   to prevent the JWT from being replayed.  The "jti" value is a case-
   sensitive string.  Use of this claim is OPTIONAL.

**Comment by vimalloc** [comment]
The official wording of the JTI spec is certainly not the most clear thing is it :P

As I understand it, the `subject` should be unique for tokens of the same subject. For example, if I was `user3@foo.com`, and ended up making a JWT for my desktop, laptop, and mobile phone, all of them would be different tokens but have the subject (`user3@foo.com`) as long as no other user had the same email as me. A unique identifier for the user if you will.

Alternately, the `jti` claim must be unique for every token. So in the same scenario above where I have three tokens on three different devices, they must all have a different jti, or unique global identifier. In this extension we are specifically using the `jti` claim so that we can blacklist a single token based on its `jti` without blacklisting all tokens for a user.

Does this help clarify things?

**Comment by igorkf** [comment]
In [](https://auth0.com/docs/tokens/concepts/jwt-claims) explains the different claims:
Reserved claims

The JWT specification defines seven reserved claims that are not required, but are recommended to allow interoperability with third-party applications. These are:

    - iss (issuer): Issuer of the JWT
    - sub (subject): Subject of the JWT (the user)
    - aud (audience): Recipient for which the JWT is intended
    - exp (expiration time): Time after which the JWT expires
    - nbf (not before time): Time before which the JWT must not be accepted for processing
    - iat (issued at time): Time at which the JWT was issued; can be used to determine age of the JWT
    - jti (JWT ID): Unique identifier; can be used to prevent the JWT from being replayed (allows a token to be used only once)
