### ISSUE TITLE
Flask-restplus errorhandler workaround possibly not working in python3.7

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#265]
@engmsaleh I want to continue the conversation here to keep the other issue easier to navigate. If you could provide a complete *minimal* and verifiable example here that shows the issue you are seeing, as well as the versions of all packages you are using, that could be very helpful in digging further into this.

**Comment by vimalloc** [comment]
As an update, this seems to still be working for me:

# app.py
```python
from flask import Flask, jsonify, request
from flask_jwt_extended import JWTManager, jwt_required, create_access_token
from flask_restplus import Resource, Api

app = Flask(__name__)
app.config['JWT_SECRET_KEY'] = 'super-secret'  # Change this!
jwt = JWTManager(app)
api = Api(app)
jwt._set_error_handler_callbacks(api)


@api.route('/hello')
class HelloWorld(Resource):
    @jwt_required
    def get(self):
        return {'hello': 'world'}


if __name__ == '__main__':
    app.run(debug=True)
```

# Server logs
```
(venv) $ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Aug/2019 21:51:56] "GET /hello HTTP/1.1" 401 -
```

# Client logs
```
(venv) $ http GET :5000/hello
HTTP/1.0 401 UNAUTHORIZED
Content-Length: 39
Content-Type: application/json
Date: Thu, 08 Aug 2019 03:52:35 GMT
Server: Werkzeug/0.15.5 Python/3.7.4

{
    "msg": "Missing Authorization Header"
}
```

# Python version
```
(venv) $ python --version
Python 3.7.4
```

# Package versions
```
(venv) $ pip freeze
aniso8601==7.0.0
attrs==19.1.0
Click==7.0
Flask==1.1.1
Flask-JWT-Extended==3.21.0
flask-restplus==0.12.1
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.2
MarkupSafe==1.1.1
PyJWT==1.7.1
pyrsistent==0.15.4
pytz==2019.2
six==1.12.0
Werkzeug==0.15.5
```

To troubleshoot this further I will need more information on how to reproduce the issue.

**Comment by vimalloc** [comment]
@Jonyorker I think this is the same thing that was affecting you as well. Sorry about the delay in looking into this, I spaced it until seeing a similar issue report pop up today as well. Having this in a separate ticket should help keep me organized going forward with this :+1:

If you can provide any additional insight in how to trigger the issue, that would go a long way towards being able to figure out what's going on.

**Comment by manattersa** [comment]
Hi, I've running with this issue and the workaround is working for me. 
The project has almost the same dependencies as commented above (python 3.7.0). The only difference is that I'm using blueprints. 
Checked with production, development, debug True/False combinations.

**Comment by vimalloc** [comment]
@manattersa awesome, thank you for the data point. I really appreciate it! :+1:

**Comment by vimalloc** [comment]
As there have been no further reports of this being an issue and I cannot reproduce it I am going to close this issue. If anyone can provide a way to duplicate this let me know and I would be happy to dig into it further.
