### ISSUE TITLE
Problems using the UserLoaderCallback  

### ISSUE THREAD

**Issue by durchgedreht** [vimalloc/flask-jwt-extended#268]
Hi,

I'm using Superset and am a bit tied to the config and securitymanager configuration points/classes. So no plain Flask app build from scratch. Token reading and verification works, also additional claims etc. Only issue is the user_loader_callback that simply is not executed at all. My CustomSecurityManager is instantiated ok, init method is called, jwt is instantiated ok and I can debug jwt_manager as it's there (in Wewrkzeug debugger). So I guess it's 'simply' a loader attachment issue. 

Any help is appreciated.
Thanks!

`
class CustomSecurityManager(SupersetSecurityManager):
    authdbview = CustomAuthDBView
    jwt = JWTManager()

    def __init__(self, appbuilder):
        jwt = JWTManager(appbuilder.app)
        super(CustomSecurityManager, self).__init__(appbuilder)

    @jwt.user_loader_callback_loader
    def user_loader_callback(identity):

        user = self.appbuilder.sm.find_user_by_username(identity)

        return UserObject(
            username=identity,
            foo='bar'
        )
`

The Flask Trace looks like follows:

<img width="819" alt="Screenshot 2019-08-16 at 11 30 44" src="https://user-images.githubusercontent.com/4490840/63158510-af57e800-c019-11e9-9ac3-5f77dd70808c.png">
ValueError: invalid literal for int() with base 10: 'demo@foobar.com'

**Comment by vimalloc** [comment]
Looks like the flask app builder default callbacks are still being used instead of your custom one:  https://github.com/dpgaspar/Flask-AppBuilder/blob/f669d8c553a76cdc8186fa3e9252cabc69ace9d9/flask_appbuilder/security/manager.py#L285 and https://github.com/dpgaspar/Flask-AppBuilder/blob/f669d8c553a76cdc8186fa3e9252cabc69ace9d9/flask_appbuilder/security/manager.py#L1577

Based on the docs on this page (https://flask-appbuilder.readthedocs.io/en/latest/rest_api.html) it looks like you can change that behavior via

```python
@appbuilder.sm.jwt_manager.user_loader_callback_loader
def alternate_user_loader(identity):
    # find the user by it's identity
    ...
    return user
```

**Comment by durchgedreht** [comment]
Hi,
thanks for the hint - after looking into the code I changed the load_user function which seems to work ok as tge sql statement generated is ok and user loads like expected.

I still have a strange behaviour where the login redirects in a circle (user is loaded from DB ok at the beginning, but the redirect handling seems to be broken).

`
import logging
from flask import redirect, g, flash, request
from flask_appbuilder.security.views import UserDBModelView, AuthDBView
from superset.security import SupersetSecurityManager
from flask_appbuilder.security.views import expose
from flask_appbuilder.security.manager import BaseSecurityManager
from flask_login import login_user, logout_user
import requests
import sys
import json

from flask_jwt_extended import JWTManager
from flask_jwt_extended import (create_access_token, create_refresh_token, jwt_required, jwt_refresh_token_required, get_jwt_identity, get_raw_jwt)

class CustomAuthDBView(AuthDBView):

    @jwt_required
    @expose('/login/', methods=['GET', 'POST'])
    def login(self):
        logger = self.appbuilder.app.logger
        logger.info("CustomAuthDBView.login)

        jwt_json = get_raw_jwt()
        logger.info(jwt_json)
        jwt_aud = jwt_json['aud']  # sample value: '1',
        jwt_user = jwt_json['user']

        account_id = jwt_user['account_id']
        login = jwt_user['login']

        redirect_url = self.appbuilder.get_url_for_index
        logger.debug("redirect_url = {}".format(redirect_url))

        if request.args.get('redirect') is not None:
            redirect_url = request.args.get('redirect')
            print("Redirect URL found in request", flush=True)

        user = self.appbuilder.sm.find_user(username = login)
        if user is None:
            logger.info("create user")
            user = self.appbuilder.sm.add_user(
                username = login,
                first_name = "First",
                last_name = "Last",
                email = login,
                role='Alpha'
                #role=self.appbuilder.sm.find_role(self.appbuilder.sm.auth_user_registration_role)
            )
        #self.appbuilder.sm.update_user_auth_stat(user, True)
        login_user(user, remember=True)

        redirect_url = "/dashboard/list/"
        return redirect(redirect_url)

class CustomSecurityManager(SupersetSecurityManager):
    print("load sCustomSecurityManager)
    authdbview = CustomAuthDBView

    def load_user(self, user_id):
        logger = self.appbuilder.app.logger
        logger.info("load user {}".format(user_id))
        user = self.find_user(username=user_id)
        return user

    def __init__(self,  appbuilder):
        jwt = JWTManager(appbuilder.app)
        super(CustomSecurityManager, self).__init__(appbuilder)
`
