### ISSUE TITLE
create_refresh_token ignores identity

### ISSUE THREAD

**Issue by konradzuwala** [vimalloc/flask-jwt-extended#27]
Hello,
there is a bug in create_refresh_token. It ignores identity parameter - function  for @user_identity_loader is not called, like in access token. Thus, you have to use here user nickname/id / whatever is JSON serializable. Or it is intentional?

**Comment by vimalloc** [comment]
Good catch, that is not intended at all. Give me just a sec here and I'll get that fixed up, and push a new release out.

Thanks!

**Comment by konradzuwala** [comment]
Hehe okey, thanks :)

**Comment by vimalloc** [comment]
Released as 1.2.1, it should be on pypi soon. Thanks for the report! :+1:

**Comment by konradzuwala** [comment]
super thanks, btw great library :)
