### ISSUE TITLE
FEATURE: Add custom fields in JWT header

### ISSUE THREAD

**Issue by iamajay** [vimalloc/flask-jwt-extended#271]
Hi, I am using flask-jwt-extended in my production app but recently have come across with a blocker for adding a custom field in the header of jwt, I searched the code and implementation of this repo and found out according to current implementation it is not possible to do so. So I am suggesting that we can add this feature as well. Just like [https://pyjwt.readthedocs.io/en/latest/usage.html#specifying-additional-headers](url) which is provided in pyjwt library.

**Comment by vimalloc** [comment]
That sounds like a totally reasonable feature to add to me. Would you like to take a stab at adding it to this extension and creating a pull request? If not I can look at adding it when I have some time, but it's been a hectic recently so it might be a few weeks before I could look at it.

Cheers

**Comment by ajayoo7** [comment]
Yes sure, I'd love to work on this, will create a pull request as soon I will finish this.

**Comment by ajayoo7** [comment]
@vimalloc I have created the pull request for the same: https://github.com/vimalloc/flask-jwt-extended/pull/276

Best AJ

**Comment by vimalloc** [comment]
Released in version 3.24.0. Thanks for contributing!
