### ISSUE TITLE
JWT in headers + CSRF in cookie

### ISSUE THREAD

**Issue by Korhm** [vimalloc/flask-jwt-extended#279]
Hello,

I would like to put JWT in headers and CSRF in cookie, but this seems not possible reading the document.
By this way, my frontend will be able to get some information from user_claims, and I will avoid to store this in a cookie

Currently, I have to add this kind of information on /login response. 

Is there a way to achieve it ? If not, why ?

**Comment by vimalloc** [comment]
If your JWT is being passed in via headers then you are not susceptible to a CSRF attack and do not need to pass in the CSRF double submit tokens at all. Here is some more in depth information about this: https://security.stackexchange.com/a/170414
