### ISSUE TITLE
How to call @admin_required like @jwt_required

### ISSUE THREAD

**Issue by tatdatpham** [vimalloc/flask-jwt-extended#281]
I followed in this docs [custom_decorators](https://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html)
I have question. How to call @admin_required decorator in another file, namespace ... like @jwt_required

Look like this
```
from flask_jwt_extended import (jwt_required admin_required)
````

Thank!

**Comment by vimalloc** [comment]
You need to import admin_required from whatever file you defined it in, not from flask_jwt_extended.
