### ISSUE TITLE
Gitter vs Slack vs Discord

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#283]
I've been having a lot of issues with the mobile and desktop clients for Gitter for a while now. I'm thinking about moving the support channel over to Slack or Discord instead. I don't want to go back to IRC just because of the amount of infrastructure I need to manage there, IE push notifications, bouncers, searchability, etc. 

I'm wondering if anyone has strong opinions about gitter vs slack vs discord (vs ????) before I start making changes?

Thanks! :+1:

**Comment by carc1n0gen** [comment]
I personally like discord over slack because discord servers are actually discoverable, and have voice channels which could come in handy

**Comment by vimalloc** [comment]
Thanks for the input @carc1n0gen. It looks like flask/pocoo proper is on discord these days as well, which is another point in it's favor. I'll working on getting stuff moved over to discord in the coming days.

Cheers :+1:

**Comment by vimalloc** [comment]
The new home for flask-jwt-extended chatting is https://discord.gg/EJBsbFd. I'll continue to monitor the gitter channel for a few months during the transition.

**Comment by gsbhasin123** [comment]
@vimalloc You can also try a https://matrix.org/ channel, it can be bridged with discord
