### ISSUE TITLE
Incomplete docs

### ISSUE THREAD

**Issue by LucaTabone** [vimalloc/flask-jwt-extended#287]
Hey guys :),

I love the work you have done with this package. Thank You!
Unfortunately the doc-page https://flask-jwt-extended.readthedocs.io/en/stable/blacklist_and_token_revoking.html is not available.
Could you have a look into this issue?

Best regards from Berlin,
Luca

**Comment by vimalloc** [comment]
We recently changed how the urls work for docs to fix a redirect issue. You can now find that page at https://flask-jwt-extended.readthedocs.io/en/stable/blacklist_and_token_revoking/ 👍

**Comment by vimalloc** [comment]
And I just added a redirect so that the old urls should continue working! Thanks for getting this on my radar!

**Comment by LucaTabone** [comment]
Awesome, thank you so much for your quick response :)
