### ISSUE TITLE
Missing an auto-refresh example

### ISSUE THREAD

**Issue by beasteers** [vimalloc/flask-jwt-extended#289]
What I can't find in the docs is how to automatically refresh the token (w/ cookies) when the access token expires - and to refresh it entirely within the backend (the frontend/user does not have to take any action to parse/refresh the token). 

The closest I am is this, but if someone's token expires as they're sending a POST request for example, it won't work because you can't reconstruct a POST request with `url_for`

```python
@expired_token_loader
def maybe_refresh_token():
    return redirect(url_for(
        'refresh_token', # refreshes like in the docs, redirects back to `next`
        next=url_for(request.endpoint, **request.view_args) # original request
    ))
```

The other thought is to do something like:

```python
@auth.before_app_request
def maybe_refresh_token():
    try:
        verify_jwt_in_request()
    except ...:
        _refresh_token()
```

But that won't update the current request object.

It would be nice if there were a helper/decorator that will work regardless of the request and would be able to update the cookie before `jwt_required` is run.

Maybe I'm just missing something and the answer is obvious?

**Comment by vimalloc** [comment]
You could probably set something up a custom decorator (https://flask-jwt-extended.readthedocs.io/en/stable/custom_decorators/) where you grab the response from your view function and modify it accordingly. Or something jimmied together with an `@app.before_request` in conjunction with `flask.g` and `@app.after_this_request`, but I'm not sure this is really the best way to approach this problem. If you are sending an access and refresh token during every request, you aren't really getting any benefits for using a refresh token compared to just using a longer lived access token. For practical purposes, settings your access token to the expires time that you are using for the refresh token would be the same in terms of security as sending in both the refresh token and access token in each request.

**Comment by beasteers** [comment]
I'm not thinking of sending a new token on every request, I'm just trying to refresh the access token in the background if the access token is expired and the refresh token hasn't. 

Since it's being stored in cookies, the frontend isn't having to manage the token so refreshing an access token isn't going to affect any of their queries and I think should therefore be done in the background, instead of having error handling throughout the javascript.

You're right in that I can probably just make do without the refresh token though, so that's what I'll probably do.

But for cookie-based JWT refreshing, I'm just not sure how refreshing is expected to be done, because the snippets in the docs don't mention it. Is refreshing meant to be done through the frontend? Or could we have an extra callback that will refresh the access token if the refresh token is available? (it could probably be called inside `jwt_required`, or like `verify_jwt_in_request(refresh_expired=True)`)

**Comment by vimalloc** [comment]
> I'm not thinking of sending a new token on every request, I'm just trying to refresh the access token in the background if the access token is expired and the refresh token hasn't.

I wasn't suggesting that, I was thinking you would only refresh the token if it was expired and there was a valid refresh token present. But like I was saying, I think that would be needlessly complicated and not really provide any benefits compared to just having a longer lived access token, because you would need to include the refresh token in every request for that to work. You would not want to refresh an expired token without some valid token present because then any token created in the past could be used to create a new valid token, and if a JWT is ever leaked it will be valid forever.

You might want to read this, it has a lot of information about options for refreshing tokens: https://stackoverflow.com/a/46284627/272689. In your case, you might want to consider doing something like automatically refreshing a JWT if it is near expiring, without using a refresh token. Something like this (untested)

```python
@app.after_request
def refresh_jwt_if_near_expiring(response):
    expires_time = get_raw_jwt().get('exp')
    if not expires_time:
        return response

    target_time = datetime.datetime.utcnow() + datetime.timedelta(hours=1)
    if (target_time > expires_time):
        access_token = create_access_token(identity=get_jwt_identity())
        set_access_cookies(response, access_token)

    return response
```
