### ISSUE TITLE
Modified auth-token works?

### ISSUE THREAD

**Issue by hossow** [vimalloc/flask-jwt-extended#294]
Hello Everybody,
i found that a modified auth token can autenticate a user too. It can be reproduced with the basic-usage example (https://flask-jwt-extended.readthedocs.io/en/stable/basic_usage/). Here's what I did:

1) Copy and paste the the code and run it.
2) login as testuser
```
$ curl -i -X POST -H "Content-Type: application/json" -d '{"username":"test","password":"test"}' http://127.0.0.1:5000/login

{"access_token":"eyJ0eXAiOiJKV1Qi [--snip--] V6cH1D763BZG0aSj3GY"}
```
Then I changed the last letter from "Y" to "Z" and tried to access the protected function:
```
$ curl -H "Authorization: Bearer eyJ0eXAiOiJKV1Qi [--snip--] V6cH1D763BZG0aSj3GZ" http://localhost:5000/protected
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24  100    24    0     0    109      0 --:--:-- --:--:-- --:--:--   109{"logged_in_as":"test"}

```
BTW: When I changed the last letter from 'Y" to "X" I got an error in the example-code an my own app.

Maybe I missed somtehing or need to do things to "harden" my own application and the example is just a "basic usage",  (as the name says) but IMHO it might be a security issue if a (slightly) modified token works, since it is not the token i got from the application.

But flask-jwt-extended is a great helper - so I'll use it anyway!
Greetings

**Comment by vimalloc** [comment]
You can compare this token on https://jwt.io and observe the same effect. It has something to do with how the hmac and base64 decoding of a token works, but shouldn't affect the security of the token. If you tried to modify any of the json contents of the token it would properly be marked as invalid.

If you want to dig more into why this happens, I would suggest opening a ticket over at the pyjwt github page. That is the underlying jwt library we are using in this extension :+1:
