### ISSUE TITLE
After logout and unset cookies the "token/refresh" path is still available

### ISSUE THREAD

**Issue by saasforge** [vimalloc/flask-jwt-extended#295]
My configuration:

```
    app.config['JWT_COOKIE_SECURE'] = False 
    app.config['JWT_COOKIE_CSRF_PROTECT'] = False

    app.config['JWT_TOKEN_LOCATION'] = ['cookies']
    app.config['JWT_ACCESS_COOKIE_PATH'] = '/app'
    app.config['JWT_REFRESH_COOKIE_PATH'] = '/api/auth'
```

The code:

```
@jwt_api.route('/api/auth/logout')
def post(self):
        response = jsonify({'result': True})
        unset_jwt_cookies(response)
        return make_response(response, 200)

# Not available after logout
@test_blueprint.route('/app/api/jwttest', methods=['GET'])
@jwt_required
def get_test():
    return jsonify({'message': 'Protected works', 'result': True})

# Available after logout
@jwt_api.route('/api/auth/token/refresh')        
@jwt_refresh_token_required
def post(self):
        email = get_jwt_identity()
        access_token = create_access_token(identity = email)
        response = jsonify({'result': True})
        set_access_cookies(response, access_token)
        return make_response(response, 200)
```

Maybe app settings are wrong?

**Comment by saasforge** [comment]
I found the problem was with multiple cookies attached to the every request (I'm not sure why they are from but after I cleared cookies everything started working fine).

**Comment by kacpekwasny** [comment]
https://stackoverflow.com/a/76208974/12069832

My issue was, that I had a function (@Blueprint.after_app_request - that was run right before the response was sent back to client) that set a header on the response to refresh the cookie.

So my logout function added the header to expire the cookie, and the refreshing function refreshed my cookie.

So the response had following headers:
  1. Expire the cookie.
  2. Refresh the cookie.

Maybe this will help somone one day.
