### ISSUE TITLE
Allow passing arguments to jwt_required

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#297]
This would allow us to clean up the API usage a bit, IMO. Still need to finalize how the API should look, but I think something like this would allow for an easier interface to consume, and make it easier to add options in the future as needed.

`@jwt_required(fresh=False, optional=False, refresh=False)`

I'm still unsure if having every option as part of `jwt_required` or still having separate `jwt_optional`, `fresh_jwt_required`, etc would be better. I think having everything be an option for `jwt_required` might be cleaner in the long run, but it is a more severe breaking change.

**Comment by lan17** [comment]
I like this idea.

It would be useful to also either force or disable CSRF in options, regardless of whether CSRF was set globally.

For example `@jwt_required(csrf=False)` for endpoints that should require a logged-in user but should disable CSRF protection.

An example use-case would be callbacks for OAuth flows.  OAuth allows to pass `state` in a callback which can function as CSRF protection.  Thus `flask-jwt` CSRF protection can be disabled for the callback, while still requiring a logged-in user.

**Comment by vimalloc** [comment]
That's a good point @lan17. I've done the initial work of moving the existing view decorators into a single `jwt_required()`. Once I get some more work done towards the 4.0.0 release, I'll circle back around here to add some additional arguments to the jwt_required decorator, such as the csrf flag you suggested :+1:

**Comment by vimalloc** [comment]
I'm going to close this out for now, just getting the 4.0.0 branch out is proving to be more time consuming then I anticipated. I'll look into adding additional fields to `@jwt_required` in a non-breaking later version once I get 4.0.0 out the door.
