### ISSUE TITLE
Add type hinting

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#299]
With python3.5 being the new minimum supported version, we can take advantage of the fancy type hinting syntax throughout this extension

**Comment by iamajay** [comment]
seems like a good to have feature, would like to contribute for this feature.

**Comment by vimalloc** [comment]
@iamajay Awesome! Let me finish making the rest of the breaking changes I want to get to for the 4.0.0 release, then I'll ping back in here and we can start adding the type hints :+1:

**Comment by vimalloc** [comment]
4.0.0 has officially been released. Python 3.6 is the minimum supported version now, and type hinting can be added in piecemeal chunks :+1:

**Comment by TwiKeySen** [comment]
Would love to contribute !
