### ISSUE TITLE
Missing authorization header when deployed

### ISSUE THREAD

**Issue by Seluj78** [vimalloc/flask-jwt-extended#301]
Hi,

I love your extension, but I'm having a problem. I've deployed my app on my staging server and I get the `Missing Authorization Header` error when I do a request on any protected route even though it is there (Tried many things and even in postman). Any guess why that would be ?

<img width="1676" alt="Screenshot 2019-11-22 at 14 56 52" src="https://user-images.githubusercontent.com/4641317/69431586-572b3300-0d38-11ea-85dc-16465b687981.png">

**Comment by Seluj78** [comment]
Can it have something to do with CORS or something, that makes it that the header doesn't make it through on my staging server ?

**Comment by vimalloc** [comment]
Are you using a web server (such as Apache or Nginx) on your staging server? If I recall correctly there is a a setting for at least Apache that is needed to have it pass the auth header to your WSGI application. If I can get some more information on how your app is deployed I might be able to give you some more specific advice

**Comment by Seluj78** [comment]
Thanks for the quick reply !

I do not know what it is using, my app is deployed on AWS ElasticBeansTalk :/

**Comment by Seluj78** [comment]
Looks like it is indeed CORS on AWS https://forums.aws.amazon.com/thread.jspa?threadID=161108

**Comment by vimalloc** [comment]
This might also related: https://stackoverflow.com/questions/22279301/authorization-credentials-stripped-django-elastic-beanstalk-oauth

**Comment by Seluj78** [comment]
I'm trying something like this right now https://stackoverflow.com/a/34292480

It's currently deploying, will keep you updated ! 🎉

**Comment by Seluj78** [comment]
It doesn't seem to work, I'll try and force redeploy (like re build the whole thing)

**Comment by Seluj78** [comment]
Trying https://forums.aws.amazon.com/message.jspa?messageID=376244

**Comment by Seluj78** [comment]
Seems like it is working in postman now, but my request code doesn't seem to work... WTF ? I'll keep trying

Thanks a lot for your reactivity ! Have a wonderful day ! 🚀

**Comment by Seluj78** [comment]
FFS apparently I just forgot a F'IN `/` at the end of my request... That's weird and it might be a bug report for you !

A request on `/v1/users` gives me a missing auth token but works on `/v1/users/` (my route is `user_bp.route("/users/")` so it is my fault but yeah)
