### ISSUE TITLE
get_jwt_identity return => "msg": "Missing Authorization Header"

### ISSUE THREAD

**Issue by engmsilva** [vimalloc/flask-jwt-extended#302]
I can retrieve the token identity value when sent by the postman header.

However when I use string query is returning the error message:

`api/protected?jwt=<access_token>`

```
{
   "msg": "Missing Authorization Header"
}
```

My recovery code looks like this:
```
class User_Confirm(Resource):
    @jwt_required
    def get(cls):       
        user_id = get_jwt_identity()
        return print(user_id)
```

I'm using flask_restful to do routing.

 Is there anything else that should be parameterized?

```
aniso8601==8.0.0
blinker==1.4
Click==7.0
Flask==1.1.1
Flask-Cors==3.0.8
Flask-JWT-Extended==3.24.1
Flask-Mail==0.9.0
Flask-RESTful==0.3.7
Flask-SQLAlchemy==2.4.1
itsdangerous==1.1.0
Jinja2==2.10.3
MarkupSafe==1.1.1
psycopg2-binary==2.8.4
PyJWT==1.7.1
python-dotenv==0.10.3
pytz==2019.3
six==1.13.0
SQLAlchemy==1.3.11
Werkzeug==0.16.0
```

**Comment by vimalloc** [comment]
Make sure you set the JWT_TOKEN_LOCATION option accordingly  For example, `app.config[‘JWT_TOKEN_LOCATION’] = [‘headers’, ‘query_string’]`

**Comment by engmsilva** [comment]
@vimalloc 
Thanks for the feedback. Below are my settings, but it seems that you are only accepting the token by the header.
```
app.config['JWT_TOKEN_LOCATION'] = ['headers', 'query_string']
app.config['JWT_SECRET_KEY'] = os.getenv("JWT_SECRET_KEY")
app.config['JWT_BLACKLIST_ENABLED'] = True
jwt = JWTManager(app)
```

**Comment by engmsilva** [comment]
Please disregard the previous answer when adding the settings:
`app.config['JWT_TOKEN_LOCATION'] = ['headers', 'query_string']`
The token for the string query worked.

Thank you @vimalloc

**Comment by vimalloc** [comment]
Awesome, glad to hear it :+1:

**Comment by Sangkibet-netsh** [comment]
"msg": "Missing JWT in headers or query_string (Missing Authorization Header; Missing 'jwt' query paramater)"
i got this error in the process

**Comment by mark-baumann** [comment]
> "msg": "Missing JWT in headers or query_string (Missing Authorization Header; Missing 'jwt' query paramater)" i got this error in the process

I have the same error

**Comment by MarrekNozka** [comment]
This is because The FlaskApp recive not token. The request for the FlaskServer must contain token. See [JWT Locations](https://flask-jwt-extended.readthedocs.io/en/stable/token_locations.html) in docs.

For example I want JWT auth  on Flask-Admin App. I must use 'cookies' in 'JWT_TOKEN_LOCATION' or decorage by `@jwt_required(locations=['headers', 'cookies'])` or use `verify_jwt_in_request(locations=[ 'cookies' ])`.

This work's for me.

**Comment by elbroandrew** [comment]
Adding `app.config["JWT_TOKEN_LOCATION"] = ["headers", "cookies"]` worked for this error: `"msg": "Missing JWT in headers or query_string (Missing Authorization Header; Missing 'jwt' query paramater)"`. Thanks.
