### ISSUE TITLE
Blacklist a token assigned to a deleted database user

### ISSUE THREAD

**Issue by engmsilva** [vimalloc/flask-jwt-extended#304]
What is the best way to invalidate an active user token that has been deleted from the database?

The fastest and not very smart way would be to put an active user check on all routes, but I think that would not be the best practice.

Any way to list all active token to which the deleted user belongs?

**Comment by vimalloc** [comment]
This could be handled a couple of ways.

The easiest is using a `@jwt.user_loader_callback_loader` to check for the existence of the user in your database. It would load the user on every request for you (accessed via `current_user` in your endpoints), and return an error if the user was not found in the database. An example of that can be seen here: https://flask-jwt-extended.readthedocs.io/en/stable/complex_objects_from_token/

The second would be to store all your created and revoked tokens in a database, that can then be queried and managed in events like when a user was deleted. A basic example of that can be seen here: https://github.com/vimalloc/flask-jwt-extended/tree/master/examples/database_blacklist
