### ISSUE TITLE
Issue with @jwt_required - Signature verification failed

### ISSUE THREAD

**Issue by rodrigorodrigues** [vimalloc/flask-jwt-extended#305]
Hi,

I'm trying to validate a JWT using `@jwt_required` but always getting error `422 - UNPROCESSABLE ENTITY - {
    "msg": "Signature verification failed"
}`.

I thought the issue was with some missing claims then I changed my JWT to be as close as possible for the example from the creation token but still same error.

Does anyone have any clue on how to solve that please?

Following piece of my code for better understanding.

.env

	JWT_SECRET_KEY = 'secret-key'

	JWT_DECODE_ALGORITHMS = ['HS512', 'RS256']

	JWT_IDENTITY_CLAIM = 'sub'

	JWT_USER_CLAIMS = 'authorities'

	PROPAGATE_EXCEPTIONS = True

app.py

	from flask import Flask, jsonify
	from flask_jwt_extended import JWTManager

	app = Flask(__name__)
	app.config['MONGODB_SETTINGS'] = {
	    'host': 'mongodb://localhost/docker'
	}
	app.config.from_envvar('ENV_FILE_LOCATION')
	jwt = JWTManager(app)

	if __name__ == "__main__":
	    initialize_db(app)

	    api = Api(app)

	    initialize_routes(api)

	    run_simple(hostname="localhost", port=app.config['SERVER_PORT'], application=dispatcher)

	    app.run(debug=True, host='0.0.0.0', port=app.config['SERVER_PORT'])

JWT decoded

	{
	  "typ": "JWT",
	  "alg": "HS512"
	}

	{
	  "sub": "admin@gmail.com",
	  "auth": "ROLE_ADMIN",
	  "name": "admin@gmail.com",
	  "type": "access",
	  "fresh": true,
	  "authorities": [
	    "ROLE_ADMIN"
	  ],
	  "jti": "129e90bc-0023-47a6-afbd-eb95461cfa46",
	  "exp": 1577759781,
	  "iat": 1577673381,
	  "nbf": 1577673381
	}

Resource

	class ProductsApi(Resource):
	    @jwt_required
	    def get(self):
		query = Products.objects()
		movies = Products.objects().to_json()
		return Response(movies, mimetype="application/json", status=200)

PS: I'm newbie in Python sorry if my question is stupid

**Comment by vimalloc** [comment]
How are you creating the JWTs that you are passing to a protected endpoint? That error normally means that the tokens were created with a different secret key then the one being used to decode them.

**Comment by rodrigorodrigues** [comment]
Hi @vimalloc thanks for your reply.

The JWT is created by another service written in Java using Spring Oauth2 and the secret key is right as I use the same in other services.

I'm thinking it  can be some issue with the algorithm that I'm using `HS512`, following stacktrace error.

	[2019-12-30 19:01:05,998] ERROR in app: Exception on /api/products [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
	    rv = self.dispatch_request()
	  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
	    return self.view_functions[rule.endpoint](**req.view_args)
	  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
	    resp = resource(*args, **kwargs)
	  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 89, in view
	    return self.dispatch_request(*args, **kwargs)
	  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
	    resp = meth(*args, **kwargs)
	  File "/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
	    verify_jwt_in_request()
	  File "/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
	    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
	  File "/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request
	    decoded_token = decode_token(encoded_token, csrf_token)
	  File "/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/utils.py", line 118, in decode_token
	    allow_expired=allow_expired
	  File "/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/tokens.py", line 140, in decode_jwt
	    leeway=leeway, options=options, issuer=issuer)
	  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 92, in decode
	    jwt, key=key, algorithms=algorithms, options=options, **kwargs
	  File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 156, in decode
	    key, algorithms)
	  File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 223, in _verify_signature
	    raise InvalidSignatureError('Signature verification failed')
	jwt.exceptions.InvalidSignatureError: Signature verification failed
	127.0.0.1 - - [30/Dec/2019 19:01:05] "GET /api/products HTTP/1.1" 500 -

Thanks

**Comment by vimalloc** [comment]
As long as your algorithm is the same when a token is created, it should be fine, `HS512` is a supported algorithm. The only time the `InvalidSignatureError` is raised is if PyJWT (the underlying jwt implementation that this extension relies on) fails to verify the token with the given key: https://github.com/jpadilla/pyjwt/blob/11ac89474b1179925c76450fcc4b3d2042c45f19/jwt/api_jws.py#L241

I would double check that you are using the same secret to create the token as you are when decoding the token in your flask app, and that they are using the same algorithm. It might also be worth verifying that the secret string is encoded the same way between your java service and your flask one (utf-8, ascii, byte string, etc).

**Comment by rodrigorodrigues** [comment]
You are right @vimalloc the issue was with encoding I'm using base64.

To solve that I added the following piece of code based on comment https://github.com/vimalloc/flask-jwt-extended/issues/86#issuecomment-510204993

	import base64
	...
	app.config['JWT_SECRET_KEY'] = base64.b64decode(app.config['JWT_SECRET_KEY'])

Thanks a million appreciate your help
