### ISSUE TITLE
Failure of POST request to a Flask Restful API using Jwt Extended keep getting 403 and 401

### ISSUE THREAD

**Issue by yehonadav** [vimalloc/flask-jwt-extended#309]
while using verify_jwt_in_request()
this seems to be quite a pickle, i've seen #174 and #253 but even after removing flask-cors and implementing the workaround to get the entire post body this function fails, even on a simple flask development server and python requests:

Flask Traceback (most recent call last):
  File "C:\myproject\auth.py", line 26, in user_token
    verify_jwt_in_request()
  File "C:\myproject\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "C:\myproject\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 293, in _decode_jwt_from_request
    encoded_token, csrf_token = get_encoded_token_function()
  File "C:\myproject\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 277, in <lambda>
    lambda: _decode_jwt_from_cookies(request_type))
  File "C:\myproject\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 232, in _decode_jwt_from_cookies
    raise CSRFError("Missing CSRF token")
flask_jwt_extended.exceptions.CSRFError: Missing CSRF token

my requests.post code:

r = requests.post(
  url+JWT_ACCESS_COOKIE_PATH+'edit_user',
   json={'first_name':'name'},
  // {'access_token_cookie': 'ey...', 'csrf_access_token': '48...', 'csrf_refresh_token': '3e...'}
  cookies=user['cookies'],  
)
my response:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

running on python 3.6 with:
Flask==1.1.1
Flask-Cors==3.0.8
Flask-JWT-Extended==3.24.1
PyJWT==1.7.1
requests==2.22.0
six==1.13.0
Werkzeug==0.16.0

flask_jwt_extended.exceptions.CSRFError: Missing CSRF token
is weird because im definitely seeing csrf_access_token before calling verify_jwt_in_request:

@app.route(JWT_ACCESS_COOKIE_PATH+'edit_user', methods=['POST'])
def edit_user():
    request.date
    request.form
    print(request.cookies)
    verify_jwt_in_request()

not sure what im doing wrong as i follow the documentation steps and got everything else working properly

**Comment by yehonadav** [comment]
after some investigation i found that _decode_jwt_from_cookies
is looking for the wrong csrf_field_key => 'csrf_token' instead of 'csrf_access_token'
i made a temporary workaround in the function:

```python
def _decode_jwt_from_cookies(request_type):
    if request_type == 'access':
        cookie_key = config.access_cookie_name
        csrf_header_key = config.access_csrf_header_name
        csrf_field_key = config.access_csrf_field_name
    else:
        cookie_key = config.refresh_cookie_name
        csrf_header_key = config.refresh_csrf_header_name
        csrf_field_key = config.refresh_csrf_field_name

    encoded_token = request.cookies.get(cookie_key)
    if not encoded_token:
        raise NoAuthorizationError('Missing cookie "{}"'.format(cookie_key))

    if config.csrf_protect and request.method in config.csrf_request_methods:
        csrf_value = request.headers.get(csrf_header_key, None)
        if not csrf_value and config.csrf_check_form:
            csrf_value = request.form.get(csrf_field_key, None)
        if not csrf_value:
            csrf_value = request.cookies.get(csrf_field_key, None)
        if not csrf_value:
            csrf_value = request.cookies.get('csrf_access_token', None)
        if not csrf_value:
            raise CSRFError("Missing CSRF token")
    else:
        csrf_value = None

    return encoded_token, csrf_value
```

also i found out that i forgot to set 
JWT_COOKIE_SECURE = True
and left it as False, maybe this brought up some yet to be tested functionality

hope this helps and issue will be fixed soon
this is an awesome library!

**Comment by vimalloc** [comment]
I think you are misunderstanding how the CSRF protection is happening with this extension. If you grab the CSRF token from the cookie, which is automatically sent to the browser with every request, then there is no CSRF protection happening and you would be wide open to those style of attacks. This misconception has happened before, and has some disussion around it you that you might find useful here:

https://github.com/vimalloc/flask-jwt-extended/issues/150#issuecomment-387613243

I do have this this documented here (https://flask-jwt-extended.readthedocs.io/en/stable/tokens_in_cookies/) but it obviously easy to miss or overlook, as several people have run into the same issue. Do you have any suggestions on how to make this more apparent in the documentation? I would like to do whatever I can to make this as clear as possible in the documentation.

**Comment by yehonadav** [comment]
thank you for enlightening me
so after some more reading i see im a huge novice in all regards of CSRF protection.
it is easy to overlook and i would suggest a more complete example usage in the documentation because I in particular did not understand and might still be wrong about the client implementation for sending the requests.

as far as I understand this should be the server side:
```python
from flask import Flask, jsonify, request

from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token,
    jwt_refresh_token_required, create_refresh_token,
    get_jwt_identity, set_access_cookies,
    set_refresh_cookies, unset_jwt_cookies,
    get_csrf_token  # we need this for posting 
)

app = Flask(__name__)

# Configure application to store JWTs in cookies
app.config['JWT_TOKEN_LOCATION'] = ['cookies']

# Only allow JWT cookies to be sent over https. In production, this
# should likely be True
app.config['JWT_COOKIE_SECURE'] = False

# Set the cookie paths, so that you are only sending your access token
# cookie to the access endpoints, and only sending your refresh token
# to the refresh endpoint. Technically this is optional, but it is in
# your best interest to not send additional cookies in the request if
# they aren't needed.
app.config['JWT_ACCESS_COOKIE_PATH'] = '/api/'
app.config['JWT_REFRESH_COOKIE_PATH'] = '/token/refresh'

# Enable csrf double submit protection. See this for a thorough
# explanation: http://www.redotheweb.com/2015/11/09/api-security.html
app.config['JWT_COOKIE_CSRF_PROTECT'] = True

# Set the secret key to sign the JWTs with
app.config['JWT_SECRET_KEY'] = 'super-secret'  # Change this!

# we want this to be disabled when posting requests right ? 
app.config['JWT_CSRF_IN_COOKIES'] = False

jwt = JWTManager(app)


# By default, the CRSF cookies will be called csrf_access_token and
# csrf_refresh_token, and in protected endpoints we will look for the
# CSRF token in the 'X-CSRF-TOKEN' header. You can modify all of these
# with various app.config options. Check the options page for details.


# With JWT_COOKIE_CSRF_PROTECT set to True, set_access_cookies() and
# set_refresh_cookies() will now also set the non-httponly CSRF cookies
# as well
@app.route('/token/auth', methods=['POST'])
def login():
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    if username != 'test' or password != 'test':
        return jsonify({'login': False}), 401

    # Set the JWTs and the CSRF double submit protection cookies
    # in this response
    resp = jsonify({'login': True})
    
    # Create the tokens we will be sending back to the user
    access_token = create_access_token(identity=username)
    refresh_token = create_refresh_token(identity=username)
    
    # client side will have to use these values when posting with X-CSRF-TOKEN header 
    resp.headers['csrf_access_token'] = get_csrf_token(access_token)
    resp.headers['csrf_refresh_token'] = get_csrf_token(refresh_token)
    
    # we still need to set the cookies
    set_access_cookies(resp, access_token)
    set_refresh_cookies(resp, refresh_token)
    return resp, 200


@app.route('/token/refresh', methods=['POST'])
@jwt_refresh_token_required
def refresh():
    # Create the new access token
    current_user = get_jwt_identity()
    access_token = create_access_token(identity=current_user)

    # Set the access JWT and CSRF double submit protection cookies
    # in this response
    resp = jsonify({'refresh': True})
    set_access_cookies(resp, access_token)
    return resp, 200


# Because the JWTs are stored in an httponly cookie now, we cannot
# log the user out by simply deleting the cookie in the frontend.
# We need the backend to send us a response to delete the cookies
# in order to logout. unset_jwt_cookies is a helper function to
# do just that.
@app.route('/token/remove', methods=['POST'])
def logout():
    resp = jsonify({'logout': True})
    unset_jwt_cookies(resp)
    return resp, 200


@app.route('/api/example', methods=['GET'])
@jwt_required
def protected():
    username = get_jwt_identity()
    return jsonify({'hello': 'from {}'.format(username)}), 200


@app.route('/api/post_example', methods=['POST'])
@jwt_required
def protected_post():
    username = get_jwt_identity()
    msg = request.json['message']
    return jsonify({username: msg}), 200


if __name__ == '__main__':
    app.run()
```

now if i want to test this as a client:
```python
from requests import Session

url = 'http://localhost:5000'
session = Session()


class request:
    headers = {'Content-Type': 'application/json'}
    post_headers = {**headers, 'X-CSRF-TOKEN': None}
    csrf_access_token = None
    csrf_refresh_token = None
    cookies: dict = None


def test_login():
    response = session.post(url + '/login', json={
        'username': 'test',
        'test': 'test'})
    response.raise_for_status()
    print(response.cookies)
    print(response.headers)
    print(response.json())

    request.cookies = response.cookies
    request.csrf_access_token = response.headers['csrf_access_token']
    request.csrf_refresh_token = response.headers['csrf_refresh_token']
    request.post_headers['X-CSRF-TOKEN'] = response.headers['csrf_access_token']


def test_protected_get():
    response = session.get(url+'/api/example')
    response.raise_for_status()


def test_protected_post():
    response = session.post(
        url+'/api/post_example',
        json={
            'message': 'says hi',
        },
        headers=request.post_headers
    )
    response.raise_for_status()


if __name__ == "__main__":
    test_login()
    test_protected_get()
    test_protected_post()
```

i think the first thing we need to see in the docs is a working example with no suprises, most new comers are ignorant like myself and would want a copy paste magic solution to a very hard problem
there should also be a warning about #253 and a recomendation to send the token in the request headers

most of these points are in the docs but i seemed to miss the mark =(
if im still doing something incorrectly please highlight

**Comment by yehonadav** [comment]
refresh should also be handled like login
```python
@app.route('/token/refresh', methods=['POST'])
@jwt_refresh_token_required
def refresh():
    # Create the new access token
    current_user = get_jwt_identity()
    access_token = create_access_token(identity=current_user)

    # Set the access JWT and CSRF double submit protection cookies
    # in this response
    resp = jsonify({'refresh': True})
    set_access_cookies(resp, access_token)

    # client side will have to use these values when posting with X-CSRF-TOKEN header
    resp.headers['csrf_access_token'] = get_csrf_token(access_token)
    return resp, 200


def test_refresh():
    response = session.post(url + '/token/refresh', json={'refresh': True})
    response.raise_for_status()
    print(response.cookies)
    print(response.headers)
    print(response.json())

    request.cookies = response.cookies
    request.csrf_access_token = response.headers['csrf_access_token']
    request.post_headers['X-CSRF-TOKEN'] = response.headers['csrf_access_token']
```

**Comment by vimalloc** [comment]
You are close. A few things.

```python
# we want this to be disabled when posting requests right ? 
app.config['JWT_CSRF_IN_COOKIES'] = False
```

This value only controls if the CSRF token that you need to grab from your javascript can be gotten from a cookie. By default this setting is `True`, and that is totally fine. This leads to this in your example, which is not needed:

```python
    # client side will have to use these values when posting with X-CSRF-TOKEN header 
    resp.headers['csrf_access_token'] = get_csrf_token(access_token)
    resp.headers['csrf_refresh_token'] = get_csrf_token(refresh_token)
```

With the above `JWT_CSRF_IN_COOKIES` setting being true, you do not need to send any additional headers with the login response. The `set_access_cookie` and `set_refresh_cookie` calls will store the JWT in a cookie that *cannot* be read by javascript, then set an additional cookie with the name `csrf_access_token` or `csrf_refresh_token` which *can* be accessed by your javascript. These cookies only contain the CSRF double submit string.

Putting this all together, when you make a request to your API, you will need to parse the CSRF token from the cookie in your javascript, and include it as a header in your request. Something like this(untested):

```javascript
// https://stackoverflow.com/a/15724300/272689
function getCookie(name) {
  var value = "; " + document.cookie;
  var parts = value.split("; " + name + "=");
  if (parts.length == 2) return parts.pop().split(";").shift();
}

post("http://localhost:3000/api/foo", {}, {
    headers: { 'X-CSRF-TOKEN': getCookie('csrf_access_token`)}
})
```

**Comment by yehonadav** [comment]
ok so as far as i can tell your code example from the docs is perfect!
the misconception is my failure to understand how to handle csrf protection in the client.

you should add a use case for protected methods and include the axios example.
I think I understand much better now, thanks!

**Comment by vimalloc** [comment]
Awesome, thanks for the feedback. I'll get those examples added to the documentation when I find some free time :+1:

**Comment by Mohan-3410** [comment]
everything is working fine if i use frontend url as localhost:3000 and backend url as localhost:5000 but cookies in not set if i use 127.0.0.1:5000. same i am not able to set cookie in deployed link. why this is so..
