### ISSUE TITLE
If the default user loader is called but not defined by the user, raise an exception

### ISSUE THREAD

**Issue by cal97g** [vimalloc/flask-jwt-extended#310]
I have just spent a lot of time debugging an issue where the extension did not register the user loader with JWTManager.

Therefore my routes could not identify which user was trying to use them / were not able to retrieve any information about them; even with @jwt_required decorator.

By returning `None` we are hiding the real issue from users. Where we try to use a feature we have not enabled we should raise an exception - something like `NotImplementedError("You have not registered this loader, please ensure it is registered with the extension").`

**Comment by vimalloc** [comment]
Thanks for the feedback. I'll look into adding this as a breaking change into the forthcoming 4.0.0 release :+1:

**Comment by cal97g** [comment]
Thanks. I think this will improve usability.

**Comment by vimalloc** [comment]
This has been fixed in the 4.0.0-dev branch, and will be going out when I get the rest of this major release finished. Thanks again for the feedback, I think this will be a very good change! :+1:
