### ISSUE TITLE
@jwt.user_identity_loader not found

### ISSUE THREAD

**Issue by jocelindegni** [vimalloc/flask-jwt-extended#312]

**Comment by vimalloc** [comment]
I'm guessing you imported the wrong `jwt` somewhere, importing either `PyJWT` or a local `jwt.py` file that exists rather then the `JWTManager` instance, but without seeing what you are doing I could not say for certain. If you are still having problems and want some help, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) :+1:

**Comment by jocelindegni** [comment]
Thanks.
