### ISSUE TITLE
Missing example: how to protect blueprints

### ISSUE THREAD

**Issue by saasforge** [vimalloc/flask-jwt-extended#314]
I'm trying to protect some routes for SaaS application, even if it's a single page, there are several "single page apps" and want to make sure that a non-authorized user will not be able even hit this route. So, I do something like that:

```
@admin_dashboard_blueprint.route('/admin', methods=['GET'])
@admin_dashboard_blueprint.route('/admin/<path:path>', methods=['GET'])
@jwt_required
def index(path = None):
    return render_template('index.html')
```
To redirect a user I do this:

```
@jwt.unauthorized_loader
def unauthorized_loader_handler(callback):
    return redirect('/login')
```

The problem is when the access token is expired I can't control it. The server just returns me the error message.  I implement the same logic for Ajax API calls and it's done via axiom interceptors, so the request to refresh the access token is sent by the frontend and I can handle all responses and all. But here it's a different situation. I have a browser and the server-side and it's not clear what should I do. I tried to implement something like that:

```
@jwt.expired_token_loader
def expired_token_handler(callback):
    refresh_url = request.host_url + 'api/auth/token/refresh'
    resp = requests.post(refresh_url)
    return make_response(redirect(request.base_url, 200))
```

But it doesn't look good to me and it doesn't work. First of all, as soon as I make this request I'm hitting the @jwt.unauthorized_loader and have the corresponding error (Missing cookie "refresh_token_cookie"). Secondly, I don't want this wrapper to work with API calls, only with non-API ones.

How to handle this situation? Is there any working example? Thanks!

**Comment by vimalloc** [comment]
So it sounds like there are two basic questions here if I'm understanding everything right. First, can you use a different responses from the callback functions based on if it is an API call or not, and second, what is some good patterns for refreshing an expired token. Do I have that right?

For the first case, you can access the `flask.Request` object from within your error handlers. So you could do something like check the URL in your callback funciton, and return a different reponse based on that. For example (untested):

```python
from flask import Request

@jwt.unauthorized_loader
def unauthorized_loader_handler(error):
    if Request.path.startswith('/api/'):
        return jsonify(err="missing JWT"), 401
    else:
        return redirect('/login')
```

For the second case, if using cookies I actually find it significantly easier to automatically refresh the JWT in an `@app.after_request` block if the current JWT is `X` amount of time away from expiring, and not using a refresh token at all. There is some more in depth discussions around there here, which might be useful for you: https://github.com/vimalloc/flask-jwt-extended/issues/289#issuecomment-553453693.

Let me know if this helps, or if you have further questions.

**Comment by saasforge** [comment]
Thanks for your response. I'm going to dig into another issue you gave me but before I would like to mention that I don't want a user to be redirected to login page every time when the access token is expired - it would look strange :-\ I just want to refresh it and return the normal response. I can't figure out how to do it, that's the problem.

And yes, I want the behavior to be different for API and non-API calls. But in a case of API calls I want just to ignore this custom wrapper at all and it's still not clear for me how to do that.
Thanks!

**Comment by vimalloc** [comment]
You should _never_ automatically refresh an expired token, otherwise you will have tokens that can effectively be used forever. This is dangerous from a security standpoint. If a malicious actor got their hands on an old token from 2 years ago, they would be able to use that expired token to get an active token and then do whatever they wanted with it. If this is what you want (which again, I don't recommend), you could create a token that never expired via `create_access_token(identity, expires_delta=False)`. 

Instead, you should either either regenerate the token *before* it expires (like in that comment I linked above with an `@app.after_request`), or use a refresh token to generate a new access token once the access token is expired. This might be helpful for you: https://stackoverflow.com/questions/46197050/flask-jwt-extend-validity-of-token-on-each-request/46284627#46284627

**Comment by saasforge** [comment]
> 
> 
> You should _never_ automatically refresh an expired token, otherwise you will have tokens that can effectively be used forever. This is dangerous from a security standpoint. If a malicious actor got their hands on an old token from 2 years ago, they would be able to use that expired token to get an active token and then do whatever they wanted with it. If this is what you want (which again, I don't recommend), you could create a token that never expired via `create_access_token(identity, expires_delta=False)`.
> 
> Instead, you should either either regenerate the token _before_ it expires (like in that comment I linked above with an `@app.after_request`), or use a refresh token to generate a new access token once the access token is expired. This might be helpful for you: https://stackoverflow.com/questions/46197050/flask-jwt-extend-validity-of-token-on-each-request/46284627#46284627

I probably was not clear enough. When I said "refresh" I mean "generate a new access token using a refresh token" what I'm doing successfully for API calls (in practice there are 2 calls, the second one is for "refreshing" (again it's not actual refreshing)).  But I can't figure out how to do it transparently for the blueprint calls.
