### ISSUE TITLE
LDAP + JWT Question

### ISSUE THREAD

**Issue by joehoeller** [vimalloc/flask-jwt-extended#315]
Do you have any resources on how to generate a JWT token to send (RESTfully) to a front end GUI, upon successful login with LDAP with Flask-JWT-Extended?

**Comment by vimalloc** [comment]
Nope, ldap is something entirely outside of the scope of this extension. All of the documentation should still apply if you are using ldap to check username and passwords though: https://flask-jwt-extended.readthedocs.io/en/stable/basic_usage/

IE, you could have a method that looks like:

```python
@app.route('/login', methods=['POST'])
def login():
    username = request.json.get('username', None)
    password = request.json.get('password', None)

    # Do whatever ldap check you want to here in order to verify the
    # username and password are valid

    # Create and return the jwt after validating the username/password
    access_token = create_access_token(identity=username)
    return jsonify(access_token=access_token), 200
