### ISSUE TITLE
How do I add more to the payload?

### ISSUE THREAD

**Issue by gumatias** [vimalloc/flask-jwt-extended#317]
Hi! I need to add more things to the payload, for instance:

```
{
  aud: environmentId,
  sub: 'user-123',
  user: {
    email: 'joe.doe@example.com',
    name: 'Joe Doe'
  },
  auth: {
    'collaboration': {
      '*': {
        'role': 'writer'
      }
   }
}
```

How do I accomplish that? I'm only seeing options to add use claims and set a few other preconfigured properties, but not add new ones such as `auth` or `aud` in my example above. 

Thanks!

**Comment by vimalloc** [comment]
Currently you can only add custom claims under the `user_claims` key, using the `@jwt.user_claims_loader` or `create_access_token(identity, user_claims=your_claims)` (see: https://flask-jwt-extended.readthedocs.io/en/stable/add_custom_data_claims/).

I am however working on a breaking changing for the upcoming 4.0.0 release that will store all the custom claims the root level of the JWT, which would let you easily add `aud`, etc.

**Comment by gumatias** [comment]
awesome @vimalloc ! I'd love to try that out. Is there a WIP branch I could play with?

**Comment by vimalloc** [comment]
Yep! The commit is https://github.com/vimalloc/flask-jwt-extended/commit/bcb9459b94da80bd4abcc6f24f53787d6d030b3a and it's on the `4.0.0-dev` branch. I'm not sure how stable that branch is right now, things are still in flux, but I would love to have some people test it out and let me know if they run into any issues! :+1"

**Comment by newarifrh** [comment]
> Yep! The commit is [bcb9459](https://github.com/vimalloc/flask-jwt-extended/commit/bcb9459b94da80bd4abcc6f24f53787d6d030b3a) and it's on the `4.0.0-dev` branch. I'm not sure how stable that branch is right now, things are still in flux, but I would love to have some people test it out and let me know if they run into any issues! 👍

Hi @vimalloc, thank you for making this useful extension.

I have a web service that uses flask_restplus & flask_jwt_extended. On the stable flask_jwt_extended version there are no constraints, but I need a claim that is at the root. And you explained that it would be in version 4.0.0-dev. Then I tried flask_restplus & flask_jwt_extended version 4.0.0-dev, but I have an error like this:

`TypeError: wrapper() got an unexpected keyword argument 'username'`

my code :

```
from flask import Flask
from flask_restplus import Resource, Api
from flask_jwt_extended import (
    JWTManager, jwt_required, get_jwt_claims
)

app = Flask(__name__)
app.config['JWT_SECRET_KEY'] = 'abc123!'
jwt = JWTManager(app)
api = Api(app)

class RecommendationUser(Resource):
@jwt_required
    def get(self, username, type_of_reference, limit):
        return get_jwt_claims()['email']

api.add_resource(RecommendationUser, '/User/Recommendation/<string:username>/<string:type_of_reference>/<int:limit>')
```

thank you

**Comment by newarifrh** [comment]
> > Yep! The commit is [bcb9459](https://github.com/vimalloc/flask-jwt-extended/commit/bcb9459b94da80bd4abcc6f24f53787d6d030b3a) and it's on the `4.0.0-dev` branch. I'm not sure how stable that branch is right now, things are still in flux, but I would love to have some people test it out and let me know if they run into any issues! 👍
> 
> Hi @vimalloc, thank you for making this useful extension.
> 
> I have a web service that uses `flask_restplus `& `flask_jwt_extended`. On the `stable flask_jwt_extended` version there are `no constraints`, but I need a claim that is at the root. And you explained that it would be in version `4.0.0-dev`. Then I tried `flask_restplus `& `flask_jwt_extended `version `4.0.0-dev, but` I have an error like this:
> 
> `TypeError: wrapper() got an unexpected keyword argument 'username'`
> 
> my code :
> 
> ```
> from flask import Flask
> from flask_restplus import Resource, Api
> from flask_jwt_extended import (
>     JWTManager, jwt_required, get_jwt_claims
> )
> 
> app = Flask(__name__)
> app.config['JWT_SECRET_KEY'] = 'abc123!'
> jwt = JWTManager(app)
> api = Api(app)
> 
> class RecommendationUser(Resource):
> @jwt_required
>     def get(self, username, type_of_reference, limit):
>         return get_jwt_claims()['email']
> 
> api.add_resource(RecommendationUser, '/User/Recommendation/<string:username>/<string:type_of_reference>/<int:limit>')
> ```
> 
> thank you

Hi, sorry for my problem, I just found the `get_raw_jwt()` function which is to get all the payload data.
