### ISSUE TITLE
Validate token without authoration headers

### ISSUE THREAD

**Issue by pjshu** [vimalloc/flask-jwt-extended#318]
Hello,thank you to create this wonderful library

i want generator token to validate email like this:

```python
@app.route('/register', methods=["GET", "POST"])
def register_view():
    if request.method == 'POST':
        email = request.form.get('email')
        user = create_new_user()
        send_email(
            to=form.email.data,
            content=url_for('admin.auth_email_view', token=create_token(identity=user.id))
        )
        user.update(form.data)
        return generate_res()
    return {}


@app.route('/auth/register/<string:token>')
def auth_email_view(token):
    confirm_token(token)
    identify = get_jwt_identity()
    user = User.query_by_id(identify)
    if user:
        return {'status': 'success'}
    return {'status': 'failed'}
```

just use confirm_token without http headers to validate token,
Is there any way to do this?

**Comment by vimalloc-mavenlink** [comment]
You could use the JWT in the query string (https://flask-jwt-extended.readthedocs.io/en/stable/tokens_in_query_string/) to get the full callback chain (verify token is not blacklisted, run any user loaders, etc), or if you just want to verify a token you could use `decode_token` (https://flask-jwt-extended.readthedocs.io/en/stable/api/#flask_jwt_extended.decode_token) to make sure the token is valid, not expired, etc.

**Comment by pjshu** [comment]
> You could use the JWT in the query string (https://flask-jwt-extended.readthedocs.io/en/stable/tokens_in_query_string/) to get the full callback chain (verify token is not blacklisted, run any user loaders, etc), or if you just want to verify a token you could use `decode_token` (https://flask-jwt-extended.readthedocs.io/en/stable/api/#flask_jwt_extended.decode_token) to make sure the token is valid, not expired, etc.

solve my problem,thank you!!!
