### ISSUE TITLE
Get api call is working without CSRF token in Double submit verification 

### ISSUE THREAD

**Issue by PadiAditya** [vimalloc/flask-jwt-extended#319]
When we use jwt in cookies, i am storing an access token cookie in cookies and csrf token is sent as user response but without passing the csrf token in header get api call is working

**Comment by vimalloc** [comment]
As long as you are not modifying state in a  GET request, they are not vulnerable to csrf attacks. See this for a detailed explanation: https://security.stackexchange.com/a/115810

If you are not using it idiomatic rest and modifying state in your GET requests, you can change the `JWT_CSRF_METHODS` config option to include GET requests.

**Comment by PadiAditya** [comment]
Thank you @vimalloc  issue is resolved
