### ISSUE TITLE
(Question) Support for Sanic

### ISSUE THREAD

**Issue by qwexvf** [vimalloc/flask-jwt-extended#32]
Hi, i've been using the awesome extension for my flask app since its released.
now i decided to move onto Sanic which is pretty new but is there some how this extension has supports for sanic?

Thanks.

**Comment by vimalloc** [comment]
As it currently stands this obviously wont work with sanic as is, but I imagine it could be ported over. Most of the code in here doesn't do any blocking, so it shouldn't be hard to get it working with asyncio (at least, as far as I understand it). We would want to look at the underlying pyJWT library to make sure there isn't anything potentially blocking in there, but I doubt there would be.

The one except to this would be the token blacklisting functionality in this extension. This uses simplekv to access an underlying store (redis, memcache, sqlalchemy, etc), and afaik that does block and doesn't have an non-blocking/asyncio api that could be used. If you dropped the token blacklist feature, I think this would get much easier to port over. I'm not sure what exactly would need to be done if that feature were to be kept, but if I had to guess I think the easiest thing might be to only allow one of the stores to be allowed (for example redis) and utilize an existing asyncio library for interacting with it.

The last thing would be the actual interfacing with sanic. Stuff like ```init_app`` (if they have that), or storing data on whatever their equivalent of the application context / flask.g is so that it can be accessed later in the endpoints. I wouldn't expect that to be too difficult, but I haven't used sanic so I couldn't say for sure.

At present I'm not using sanic myself, and am pretty strapped for time, so I couldn't really port this over. But if someone wanted to fork this and try to get it ported over, I would be more then happy to work with them in getting everything up and running, plus making sure improvements from this library make its way over there, and vice versa.

Cheers.
