### ISSUE TITLE
What is the best way of reseting password with flask_jwt_extended?

### ISSUE THREAD

**Issue by wajeehulhassanvii** [vimalloc/flask-jwt-extended#320]
I saw a comment on stackoverflow that currently Flask_jwt_extended does not allow password reset, is it true? 
I was developing my application using flask_jwt_extended and now I will be implementing password reset. Thanks

**Comment by vimalloc** [comment]
The Flask-JWT-Extended does not deal with passwords at all. You can make an endpoint for resetting passwords using whatever password technology is being utilized by your application, and protect that endpoint with Flask-JWT-Extended if you want, but anything is outside of the scope for this extension.
