### ISSUE TITLE
JWT Multiple session invalidation

### ISSUE THREAD

**Issue by kmani314** [vimalloc/flask-jwt-extended#322]
Is there a canonical way to force a log out across multiple sessions when using a token blacklist? I want to implement this for a SPA that has password reset, which would force logout of other active sessions. I can think of a way that stores the last time the password was reset in a column and checks the IAT in token_blacklist_loader so that tokens issued before the password reset would be treated as blacklisted without having to explicitly store them, but this seems to defeat the purpose of JWT because it requires an extra database hit. Is there a better way? Sorry if this is not really pertinent to the library, but I thought that you guys would having something to say about it.

**Comment by vimalloc** [comment]
I don't think there is really a canonical way, it will be mostly tailored to the needs of your application. An extra lookup to some storage engine will almost certainly be required for this scenario. Checking the `IAT` and comparing it to a timestamp in the database seems like a very reasonable way to accomplish this :+1:

**Comment by kmani314** [comment]
Alright, thanks!
