### ISSUE TITLE
Where does the token data store on the server?

### ISSUE THREAD

**Issue by ahmadazizi** [vimalloc/flask-jwt-extended#324]
When a token has been created(or blacklisted etc), there should be a mechanism to store the token data on the server to be working consistant upon multiple requests.
It look likes the flask-jwt-extended handles this in the background. How does this mechanism work in flask-jwt-extended?

**Comment by vimalloc** [comment]
It does not. JWTs are part of the class known as stateless authentication. In broad terms, it works by hashing the contents of your token with a secret key or passphrase, and adding that as a signature to the JWT. A good overview of this can be seen here (https://jwt.io/introduction/), but in practice this means is that as long as your servers have the same secret key, and that secret key actually remains a secret, then they are able to validate that a JWT was created by you and hasn't been tampered with, without the need for storing any information on the server.

**Comment by golyalpha** [comment]
For the sake of the original question: 

What about the blacklisted tokens though? You can't exactly trust the token at that point, because it might not have been updated yet to reflect it's status, and someone also might have used the old token, untainted, version later to fool the server into thinking that the token is not blacklisted. 

Unless of course, there is some sort of a blacklist containing the token IDs which aren't valid anymore.

**Comment by vimalloc-mavenlink** [comment]
For blacklisting, you are responsible for the storage mechanism to store blacklisted token information, you can read more about it here: https://flask-jwt-extended.readthedocs.io/en/stable/blacklist_and_token_revoking/. You can see some links to more complete examples (using redis or sqlalchemy) at the bottom of that page.

> You can't exactly trust the token at that point, because it might not have been updated yet to reflect it's status

To be clear, a token will never be updated. Once a token is created, the only way to change it is to replace it with a new token.

**Comment by golyalpha** [comment]
>To be clear, a token will never be updated. Once a token is created, the only way to change it is to replace it with a new token.

Yeah, I was more so pointing to the fact that you have to store state when it comes to blacklisting tokens, and backing that with an example as to why that wouldn't work.
