### ISSUE TITLE
Explictly pass `jwt_header` and `jwt_data` to callback functions

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#327]
Currently, if you want to get some token data, you can use `get_raw_jwt()` in *some* situations. Not only is it inconsistent on when you can do that, but it's not at all apparently that this is allowed since it's relying on global state. In this new release, we will instead explicitly pass in `jwt_headers` and `jwt_data` to these callback functions whenever possible, and only store the decoded jwt in `_app_ctx_stack.top` once all of the validations have finished.

We can see how this looks in 62fe7836f9d014f4d0ee84b2f82e86b66d449557.

**Comment by torotil** [comment]
Does it make sense to pass these parameters also to the `user_lookup()` function?

**Comment by vimalloc** [comment]
Good call, I like that.

**Comment by vimalloc** [comment]
The only cases where we are not passing tokens back to the callback are when there is no token in the request (duh) or when the token is invalid (does not decode without error, invalid audience, csrf protection failed, etc). I feel like not exposing data for an invalid token makes sense, but would be open to feedback on that.
