### ISSUE TITLE
Use request context instead of app context.

### ISSUE THREAD

**Issue by torotil** [vimalloc/flask-jwt-extended#328]
flask-jwt-extended uses the app context to store the `current_user` for no good reason*. This is rather unexpected. The major version bump could be used to change this to the request context instead.

*The reason for using the app context given in #176 was:

> … the only reason I used the application context when creating this extension was because all the documentation and other extensions I looked at did the same thing.

flask-security-too uses the request context for its `current_user` implementation.

**Comment by vimalloc** [comment]
Great call, I forgot all about that. I’ll make sure it’s updated in the 4.0.0 release. Thanks a bunch!

**Comment by vimalloc** [comment]
Done in b39eb82330aa7fec422cc195544ce1994198901a :+1:
