### ISSUE TITLE
Flask JWT Extended Missing Authorization Custom Response?

### ISSUE THREAD

**Issue by abhishtagatya** [vimalloc/flask-jwt-extended#329]
Hi there, I was wondering how I can change the message given when authorization bearer token is empty:

`{
    "msg": "Missing Authorization Header"
}`

with something custom like :

```json
{
    "meta": {
        "message": "Unauthorized : Invalid Authorization Token",
        "code": 401
    }
}
```
Is it possible? Thanks in advance

**Comment by vimalloc-mavenlink** [comment]
Yep, you can do something like this:

```python
@jwt.unauthorized_loader
def custom_unauthorized_response(error_message)
    result = {
        "meta": {
           "message": error_message,
           "code": 401
        }
    }
    return jsonify(result), 401
```

You can see a full list of things that can be customized here: https://flask-jwt-extended.readthedocs.io/en/stable/changing_default_behavior/

**Comment by abhishtagatya** [comment]
@vimalloc-mavenlink thank you!
