### ISSUE TITLE
Adopt more inclusive language

### ISSUE THREAD

**Issue by msdcanderson** [vimalloc/flask-jwt-extended#331]
Adopt more inclusive language by deprecating the terms whitelist and blacklist into more descriptive terms,

Such as allowlist and blocklist.
Or allowlist and denylist

Examples:

- https://bugs.chromium.org/p/chromium/issues/detail?id=981129#c16
- https://www.techspot.com/news/85080-uk-cyber-security-agency-stop-using-racist-blacklist.html

**Comment by vimalloc** [comment]
Love it! I’ll incorporate this into the upcoming 4.0.0 release.
