### ISSUE TITLE
RSA with multiple providers?

### ISSUE THREAD

**Issue by rith87** [vimalloc/flask-jwt-extended#332]
First off, thanks for the awesome library! The jwt_optional feature was pretty clutch.

I was thinking about making a PR to handle the case where a developer is using this library to handle JWT from multiple OIDC providers (e.g. Google, Salesforce, etc). This scenario isn't supported today since the JWT_PUBLIC_KEY only expects a single public key. Or is there some other way to accomplish this that I'm missing?

**Comment by vimalloc** [comment]
I think people have handled this before by using the `decode_key_loader` to dynamically grab the correct public key. The API looks something like:

```python
# Note that this will probably slightly change in the 4.0.0 release.
# The claims and headers arguments will be switch to stay consistent
# with the rest of the app.
@jwt.decode_key_loader
def find_decode_key(claims, headers):
    # Your code here
```

If there is a better way to handle this I would by all means love a PR! If so, could you make it against the 4.0.0-dev branch? Thanks!
