### ISSUE TITLE
Better packaging and dependency management for library 

### ISSUE THREAD

**Issue by iamajay** [vimalloc/flask-jwt-extended#334]
It would be better if version 4.0.0 can be upgraded for a better tool like [poetry](https://python-poetry.org/) for dependency management and packaging. It is much better than the existing process used in the current library and most of the recent and new projects already started adopting poetry.

**Comment by vimalloc** [comment]
I think the current workflow works fine for me. I'm sure there are better options out there, but this is a simple extension that only has 2 dependencies, and I don't really want to complicate my process around releasing this on PyPI. Thanks for letting me know about poetry though, I'll make sure sure to give that a look next time I work on a flask project :+1:
