### ISSUE TITLE
Docs could use a list of ways to use JWT in a header.

### ISSUE THREAD

**Issue by stonecharioteer** [vimalloc/flask-jwt-extended#339]
It is not clear from the docs how to pass the refresh token. As you have a list of pages for cookies and json body requests, there could be a page for the header body as well. I know you've documented how to send a curl request with the header containing the access token, but how do I send a refresh token?

If someone could let me know here, I will gladly send a PR with an updated curl command in the Refresh Tokens page.

**Comment by vimalloc-mavenlink** [comment]
It's the same as the access token:

```
curl -H "Authorization: Bearer $REFRESH_TOKEN" -X POST http://localhost:5000/refresh
```
