### ISSUE TITLE
is there a way to auto change the JWT_HEADER_TYPE base 

### ISSUE THREAD

**Issue by roxic8** [vimalloc/flask-jwt-extended#340]
i have this kind of endpoint **api/admin/user** 
i want to change the **header_type** to site_admin instead of Bearer.
but if the requested endpoint/api is not admin it will set to the default the Bearer

**Comment by vimalloc** [comment]
There is not currently, it can only be set to one thing throughout the application. I'm curious why you want to change the header type for the admin endpoint? From a security point of view, there shouldn't be any concerns with using `Bearer` across the application.

**Comment by roxic8** [comment]
> There is not currently, it can only be set to one thing throughout the application. I'm curious why you want to change the header type for the admin endpoint? From a security point of view, there shouldn't be any concerns with using `Bearer` across the application.
https://github.com/auth0/angular2-jwt
Im using this library in angular and in this library, you can specify what header type is needed to each endpoint
   ```
authScheme: (request) => {
       if (request.url.includes("foo")) {
        return "Basic ";
      }

      return "Bearer ";
    },
```

**Comment by vimalloc** [comment]
I understand that you can do that, but I don't understand why you would want to use that. Is there any reason you don't want to use `Bearer` (or whatever) consistently across your application?

**Comment by roxic8** [comment]
@vimalloc there's no particular reason i just want to change header type for each endpoint base on the user roles

**Comment by roxic8** [comment]
@vimalloc  thanks man for the response . I think i should use the default Header Type
