### ISSUE TITLE
Differentiate between an access token and refresh token

### ISSUE THREAD

**Issue by icyphox** [vimalloc/flask-jwt-extended#341]
Hi, is there a way for me to differentiate between an access token and refresh token just by the token that's sent in the request? Once a token is revoked / blacklisted, there's nothing stopping the client from sending the refresh token in place of the access token (it has a longer lifetime)—this poses a security threat.

**Comment by vimalloc** [comment]
Two things:

1) Anything protected by `@jwt_required` will not accept refresh tokens, and anything marked as `@jwt_refresh_token_required` will not accept access tokens, so if a client did send a refresh token in place of an access token it shouldn't cause a problem.
2) You can look at `get_raw_jwt()['type']` if you really need to see if the token is an access or refresh token.
