### ISSUE TITLE
Incompatibility with Nuxt out-of-the-box

### ISSUE THREAD

**Issue by ThiNepo** [vimalloc/flask-jwt-extended#342]
Hello, 

I was implementing a **Nuxt** frontend using **flask-jwt-extended** at the backend. **Nuxt** has automatic Token management, login, refresh, and so on. 

The problem comes when Nuxt was trying to refresh the token, after some debugging, I discovered that Nuxt sends Content-Type **application/json;charset=UTF-8**, but  **flask-jwt-extended** expect it plain 'application/json' without anything else. Could you please change it to include 'application/json'?

I think that **_decode_jwt_from_json** function should change:

Old
```
def _decode_jwt_from_json(request_type):
    if request.content_type != 'application/json':
        raise NoAuthorizationError('Invalid content-type. Must be application/json.')
```

New
```
def _decode_jwt_from_json(request_type):
    if (request.content_type is None) or (request.content_type and 'application/json' not in request.content_type):
        raise NoAuthorizationError('Invalid content-type. Must be application/json.')
```

**Comment by vimalloc** [comment]
Seems great to me. I'll get that changed merged into the `4.0.0` dev branch shortly :+1:

**Comment by vimalloc** [comment]
It turns out if content_type doesn't start with `application/json` then flask wont load the json from the request body. I changed to to check `if not content_type.startswith("application/json"):` which should fix the issue you're seeing :+1:

**Comment by ThiNepo** [comment]
Perfect. Thanks!
