### ISSUE TITLE
JWT Header options

### ISSUE THREAD

**Issue by anandraj285** [vimalloc/flask-jwt-extended#344]
I have developed a micro services using Flask and deployed in WSO2 API manager. 

WSO2 sends JWT token to micro services. I have used the flask-jwt-extended to validate the JWT token which comes from WSO2 by using jwt_required decorator with the following setting. It working fine. 

                "JWT_DECODE_ALGORITHMS": "RS256",                
		"JWT_HEADER_NAME": "JWT-Header",
                 JWT_PUBLIC_KEY: WSO2-public-key

Now, i  have a different requirement that micro service will be used in Azure application directly without wso2. Azure app will send the JWT token in different header name and it has different public key. Kindly suggest, is there any way available in jwt-extended to validate the JWT token where request comes from two different header.

**Comment by vimalloc-mavenlink** [comment]
It is not currently possible to handle this use case with Flask-JWT-Extended unfortunately.

**Comment by anandraj285** [comment]
Thanks for your reply.  Is this use case will be implemented in future

**Comment by vimalloc** [comment]
Super late follow up, but in case you or anyone else see this issue in the future, you can probably do something with the `decode_key_loader` (https://flask-jwt-extended.readthedocs.io/en/stable/api/#flask_jwt_extended.JWTManager.decode_key_loader) to handle this.
