### ISSUE TITLE
How to expose jwks url

### ISSUE THREAD

**Issue by thuitaw** [vimalloc/flask-jwt-extended#346]
Flask JWT extended supports asymmetric key signing algorithms. See here. https://flask-jwt-extended.readthedocs.io/en/stable/options/
A lot of applications expose a jwks url which can be used to validate a jwt token.  https://auth0.com/docs/tokens/concepts/jwks
Is there any way to expose this endpoint via flask-jwt-extended?

**Comment by vimalloc** [comment]
Currently this extension does not automatically create any endpoints for you. You could absolutely create your own endpoint that exposes the same option that is present in the JWT_PUBLIC_KEY config option though.

**Comment by thuitaw** [comment]
@vimalloc Thank you. I'll see if i can come up with a simple recipe for this and share it here.
