### ISSUE TITLE
Sending a JWT token followed by comma raises IndexError

### ISSUE THREAD

**Issue by svidela** [vimalloc/flask-jwt-extended#347]
Hi,

I found that if the user sends the JWT token followed by a comma (,) an IndexError is raised. Is this the expected behaviour? You should be able to reproduce this using the basic example from the docs. It appears that the exception is raised executing `s.split()[0]` in https://github.com/vimalloc/flask-jwt-extended/blob/5bd8b1ed08ea64d23869a629af3c3c868816b8a8/flask_jwt_extended/view_decorators.py#L190

Regards,

**Comment by vimalloc** [comment]
Sounds like a bug to me. Thanks for the report!

**Comment by vimalloc** [comment]
Fixed in v4.2.0!
