### ISSUE TITLE
[Question] JWT Cookies CSRF Protection

### ISSUE THREAD

**Issue by ngetahun** [vimalloc/flask-jwt-extended#348]
Hi @vimalloc,
Before I get into my problem I want to say that it's an awesome and comprehensive library you've made here, thanks :).

My issue right now is JWT in Cookies and the CSRF protection. I have a flask api server which communicates with a vue.js client over RESTful APIs. I have enabled JWT CSRF protection for keys in the cookie. The problem is with double submit and javascript not being able to access `Secure` cookies. As far as I know, it's not possible to access Secure Cookies via `document.cookie`. On the other hand, it might be a configuration problem from my side. Here's what my JWT configuration looks like:

``` 
    JWT_TOKEN_LOCATION = ["cookies"]
    JWT_COOKIE_SECURE  = True
    JWT_COOKIE_CSRF_PROTECT = True
    JWT_CSRF_IN_COOKIES = True
    JWT_ACCESS_COOKIE_PATH = "/api/v1/"
    JWT_ACCESS_TOKEN_EXPIRES = 86400
    JWT_REFRESH_TOKEN_EXPIRES = 2592000
    JWT_REFRESH_COOKIE_PATH = "/api/v1/user/token/refresh"
    JWT_ACCESS_CSRF_HEADER_NAME = "X-CSRF-ACCESS-TOKEN"
    JWT_REFRESH_CSRF_HEADER_NAME = "X-CSRF-REFRESH-TOKEN"
    JWT_BLACKLIST_ENABLED = True
    JWT_BLACKLIST_TOKEN_CHECKS = ("access", "refresh")
```

Any help would be appreciated 🙏

**Comment by vimalloc** [comment]
You should be able to access secure cookies, that only insures that they are only sent over `https` and not `http`. There are `http-only` cookies that javascript cannot access, those are the cookies that actually contain the JWT. But there should also be a set of cookies, `csrf_access_token` and `csrf_refresh_token`, that are not `http-only` and should be accessible via javascript. Those are the cookies that have the double submit token you will want to use for CSRF protection.

If you are still running into problems, you might want to make sure that the backend and frontend are being served from the same domain. If not, browsers will not set the cookies for security reasons.

Let me know if that helps!

**Comment by ngetahun** [comment]
Thanks! I missed that. My api server is under a `service.` subdomain. That might explain the problem.

**Comment by vimalloc** [comment]
If they are under the same top level domain, you can look at the `domain` option when settings cookies (https://flask.palletsprojects.com/en/1.1.x/api/#flask.Response.set_cookie) which has it's value controlled via the `JWT_COOKIE_DOMAIN` option in this extension :+1:

**Comment by ngetahun** [comment]
I will give that a try

**Comment by ngetahun** [comment]
Solved!
