### ISSUE TITLE
Change default error messages in responses

### ISSUE THREAD

**Issue by muhammad-amhan** [vimalloc/flask-jwt-extended#349]
Hey, so this is my first time using this library with Flask instead of re-inventing the wheel. I'm still discovering the features it provides, and it's pretty cool so far. What I couldn't find on the documentation is a way to customize/change the default error messages such as:

`
{
  "msg": "Missing Authorization Header"
}
`

I'd very much like to change the key and value, is that by any chance possible? Thanks.

**Comment by vimalloc** [comment]
Yep. This is well documented here: https://flask-jwt-extended.readthedocs.io/en/stable/changing_default_behavior/

**Comment by muhammad-amhan** [comment]
@vimalloc Thanks for the reference (no idea how I've missed this page). It seems like it's not actually possible to change the key "msg" though, right?

**Comment by vimalloc** [comment]
If you want to change both the key and message you should use the links referred in that documentation, it allows you to completely control the response structures on errors. If you only want to change the key (`msg`) and keep the value the same, you can do so with the `JWT_ERROR_MESSAGE_KEY` option.

**Comment by muhammad-amhan** [comment]
@vimalloc Perfect, thank you!
