### ISSUE TITLE
samesite value of `None` does not work

### ISSUE THREAD

**Issue by novdov** [vimalloc/flask-jwt-extended#350]
Hi,

According to [IETF proposal on changing default samesite attribute](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00), cookies without a SameSite attribute will be treated as `SameSite=Lax`, which means cookies must be set `SameSite=None; Secure` explicitly.

Following above proposal, werkzeug's `dump_cookie` behavior changed in `1.0.0` to accept ["Strict", "Lax", "None"] as samesite (all string), which makes `set_access_cookies` and `set_refresh_cookies` do not work properly.

However this project uses werkzeug version 0.16.0 which does not set `SameSite=None` explicitly, eventually makes cookie does not work as expected on current browsers.

I think we should upgrade werkzeug to 1.x, and change default value of `JWT_COOKIE_SAMESITE` to `"none"`.

- Related resources
    - [SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) (MDN docs)
    - [SameSite value of 'None' not supported](https://github.com/pallets/werkzeug/issues/1549) (issue on werkzeug)
    - https://github.com/pallets/werkzeug/blob/53d5b16f8ef6c47880152f1f37623ef681609682/tests/test_http.py#L546

**Comment by vimalloc** [comment]
Sounds good to me! 👍

**Comment by novdov** [comment]
If it's ok, can I work on this? And which branch should I start to work (master or 4.0.0)?

**Comment by vimalloc** [comment]
That would be lovely! The 4.0.0 branch would be great, I’m going to try my best to get that finalized (sans documentation) done in the next couple weeks and get an alpha build out so the new features can start being utilized.

**Comment by taystack** [comment]
Is there a workaround for those of us who are locked-in to v3? The migration is a bit heavy atm and this is a key functionality for our CORS project.
