### ISSUE TITLE
flask cors not working when use @jwt_required in before_request

### ISSUE THREAD

**Issue by nirob07** [vimalloc/flask-jwt-extended#357]
i am working if flask i have a api folder which is a __init_.py where i add a authentication.py file

from flask import Blueprint,current_app
from flask_cors import CORS
api = Blueprint('api', __name__)
from . import authentication, errors
from .v1 import users,admin,shipstation,godaddy

in authentication i have before request method where i check jwt_required which will be called before every method of api folder file
from flask import g, jsonify
from flask_httpauth import HTTPBasicAuth
from . import api
from .errors import unauthorized, forbidden
from ..models import User
from flask_login import current_user, login_user
from flask_jwt_extended import (
    jwt_required,
    jwt_refresh_token_required,
    get_jwt_identity, get_raw_jwt
)
from .. import auth

@api.before_request
#@jwt_required
def before_request():
    u = get_jwt_identity()
    if(u):
        user = User.query.filter_by(id=u).first()
    else:
        return forbidden('Not Log In')
    g.current_user = user
    if g.current_user.is_anonymous:
        return forbidden('Not Log In')
    if 'current_user' not in g:
        return forbidden('Current user not found')

i have a version 1 api which folder name is v1 and in v1 i have many files like users.py, admin.py .when i use jwt token in header for api then any method in admin or user flask cors not working 
from flask import jsonify, request, current_app, url_for,g,abort
from .. import api
from ...models import ProcessListMaster,Permission,SubProcessListMaster
from ... import db
from .. import authentication
#from .. errors import bad_request, unauthorized, forbidden 
from sqlalchemy import text
from ... decorators import admin_required, permission_required,custom_jwt_required
from flask_sqlalchemy import get_debug_queries
from .. errors import bad_request, unauthorized, forbidden, error_happen
from flask_jwt_extended import (
    jwt_required,
    jwt_refresh_token_required,
    get_jwt_identity, get_raw_jwt
)

### Admin Onboarding Section  ====================

@api.route('/onboarding-process-list-master', methods=['GET'])
# @custom_jwt_required
@permission_required(Permission.WRITE)
@admin_required(Permission.ADMIN)
def onboarding_process_list():
    # list_masters = ProcessListMaster.query.all()
    # return jsonify([list_master.to_json() for list_master in list_masters])
    page = request.args.get('page', 1, type=int)
    pagination = ProcessListMaster.query.paginate(
        page, per_page=current_app.config['ITEMS_PER_PAGE'],
        error_out=False)
    itemlist = pagination.items
    prev = None
    if pagination.has_prev:
        prev = url_for('api.onboarding_process_list', page=page-1)
    next = None
    if pagination.has_next:
        next = url_for('api.onboarding_process_list', page=page+1)
    return jsonify({
        "Message": "", 
        "Status":True, 
        "Data":{
        'items': [post.to_json() for post in itemlist],
        'prev': prev,
        'next': next,
        'count': pagination.total
    }})

when i am not using jwt_required then flsak cors work as it no problem
please solve the issue as soon as possible. i think it is a big issue because when i use jwt_required directly in function then it is working

Thanks
Nirob

**Comment by vimalloc-mavenlink** [comment]
You provided way too much unrelated (and unformatted) code to understand what problem you are seeing. If you are running into an error, please provide a minimal, complete, and verifiable example outline the issue you are seeing and what you expect to be seeing. Thanks.

**Comment by Lax-odoo-1077** [comment]
@vimalloc-mavenlink https://fictitious-cal.github.io/xFfcUccEl5s/
