### ISSUE TITLE
CSRF and CSRF REFRESH Cookie sets to Secure by default, Nothing Happens even if i change config manually.

### ISSUE THREAD

**Issue by jdk-lab** [vimalloc/flask-jwt-extended#358]
I have a development stage Flask App running.
For now, I don't want my cookies to be secure and as per docs, it's false by default (I even tried it setting manually) but still the same error.

JWT_COOKIE_CSRF_PROTECT = True
JWT_COOKIE_SECURE = False

my access_token and access_token_refresh is not getting secure attribute i.e it is working as expected but the same is not true for csrf cookies.

any suggestion or fix suggested.

PFA: Screen Shot of cookie storage`
![Screenshot from 2020-09-28 21-31-44](https://user-images.githubusercontent.com/70265793/94458089-13644e00-01d3-11eb-8413-f5376b96f363.png)
`

**Comment by vimalloc-mavenlink** [comment]
Huh that's very strange, the CSRF cookie and the JWT cookie should be using the same config option for setting the secure flag: https://github.com/vimalloc/flask-jwt-extended/blob/5bd8b1ed08ea64d23869a629af3c3c868816b8a8/flask_jwt_extended/utils.py#L279-L299

If you manually delete those cookies from your browser and refresh everything are they still showing up as `secure`? Is there anything else besides a basic example needed to see this behavior?

**Comment by mishraamrish** [comment]
Yes, I tried deleting and repopulating it, but still same problem.

This is my real id, that account is only for development purpose. I raised this issue from that account and from here after I ll be here from this account.

**Comment by vimalloc-mavenlink** [comment]
I'm not able to reproduce this locally. My test server:

```python
from flask import Flask, jsonify, request

from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token,
    create_refresh_token, get_jwt_identity,
    set_access_cookies, set_refresh_cookies
)

app = Flask(__name__)
app.config['JWT_TOKEN_LOCATION'] = ['cookies']
app.config['JWT_COOKIE_CSRF_PROTECT'] = True
app.config['JWT_COOKIE_SECURE'] = False
app.config['JWT_SECRET_KEY'] = 'super-secret'
jwt = JWTManager(app)

@app.route('/login', methods=['POST'])
def login():
    access_token = create_access_token(identity='batman')
    refresh_token = create_refresh_token(identity='batman')
    resp = jsonify({'foo': 'bar'})
    set_access_cookies(resp, access_token)
    set_refresh_cookies(resp, refresh_token)
    return resp

@app.route('/viewer', methods=['GET'])
@jwt_required
def protected():
    return jsonify({'username': get_jwt_identity()})
```

And the resulting calls (notice no `Secure` flag in any of the `Set-Cookie` headers):

```
± http POST :5000/login
HTTP/1.0 200 OK
Content-Length: 14
Content-Type: application/json
Date: Tue, 29 Sep 2020 02:25:48 GMT
Server: Werkzeug/1.0.1 Python/3.7.7
Set-Cookie: access_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDEzNDYzNDgsIm5iZiI6MTYwMTM0NjM0OCwianRpIjoiOTExZTk4NzgtNmZlMy00MDg0LWEwODktNjk5MTc0N2Q5ZTYxIiwiZXhwIjoxNjAxMzQ3MjQ4LCJpZGVudGl0eSI6ImJhdG1hbiIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsImNzcmYiOiI3MzQzMmE1Yy0wNzk1LTQ0ZjgtODU1Ny01MTA1MGEwOWRlNTMifQ.9kB3jr7cYmOETv3s6s8rMzVsqkJu9BU4Q6KRyWBgdMU; HttpOnly; Path=/
Set-Cookie: csrf_access_token=73432a5c-0795-44f8-8557-51050a09de53; Path=/
Set-Cookie: refresh_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDEzNDYzNDgsIm5iZiI6MTYwMTM0NjM0OCwianRpIjoiOWFiMGQxZTUtNDE2MS00ZTRmLTgyZDktYjNiODI2ZGY1YTBlIiwiZXhwIjoxNjAzOTM4MzQ4LCJpZGVudGl0eSI6ImJhdG1hbiIsInR5cGUiOiJyZWZyZXNoIiwiY3NyZiI6IjEzMmY0N2EyLWYyZjAtNDIyNC1iZWQ1LTNkOWQzMDkzZWI4MCJ9.a-F93TE3Wj6eqsSLm0WSdImeQeArS9JYAr0rQ-NYoF0; HttpOnly; Path=/
Set-Cookie: csrf_refresh_token=132f47a2-f2f0-4224-bed5-3d9d3093eb80; Path=/

{
    "foo": "bar"
}
``` 

If I change `JWT_COOKIE_SECURE` to `True` then I see the `Secure` flag on all the cookies, like we would expect:

```
Set-Cookie: access_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDEzNDY0NzQsIm5iZiI6MTYwMTM0NjQ3NCwianRpIjoiOTljYWU2ZmUtZTljMS00MWI0LWEzMTMtY2FiNDg3NmRjZmE4IiwiZXhwIjoxNjAxMzQ3Mzc0LCJpZGVudGl0eSI6ImJhdG1hbiIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsImNzcmYiOiI0ZDU1YzY0Yi03YjVmLTQxZTAtYTFjNi0xMzA3MjY3ZDRiMjUifQ.cqdgimPjNMqcdh4yQDO_vTtkNaPD5jweREa_R4u0OMQ; Secure; HttpOnly; Path=/
Set-Cookie: csrf_access_token=4d55c64b-7b5f-41e0-a1c6-1307267d4b25; Secure; Path=/
Set-Cookie: refresh_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDEzNDY0NzQsIm5iZiI6MTYwMTM0NjQ3NCwianRpIjoiMGMwOWNkZTAtMjFhMS00OTZjLWIyNzEtYTEwNTYyYThmOGMzIiwiZXhwIjoxNjAzOTM4NDc0LCJpZGVudGl0eSI6ImJhdG1hbiIsInR5cGUiOiJyZWZyZXNoIiwiY3NyZiI6ImZkNjJjNjcyLTA1OTUtNGYxMi05ZmRlLTQyZjM1Mzc1OTU3MyJ9.yQvn_a4YpphMOrPs8QMMelIt29anOSRzweBFtc2YK0U; Secure; HttpOnly; Path=/
Set-Cookie: csrf_refresh_token=fd62c672-0595-4f12-9fde-42f353759573; Secure; Path=/
```

Can you provide a minimal and complete code example that reproduces this behavior? And include what version of Flask-JWT-Extended, Flask, and Python are you seeing this on?

Thanks

**Comment by mishraamrish** [comment]
I too did a bit of digging in it and noticed, code should work fine.
I feel like it might be a new policy being imposed by chrome or maybe, earlier I use to have SSL, that might be creating this issue.
My configuration is as follow:

from flask import Flask
from flask_restful import Api, Resource
from flask import request, jsonify, current_app, make_response
from flask_jwt_extended import (JWTManager, create_access_token, create_refresh_token,
                                set_access_cookies, verify_jwt_in_request,
                                set_refresh_cookies, get_jwt_claims)


app = Flask(__name__)

JWT_TOKEN_LOCATION = [
    'cookies',
]
JWT_ACCESS_TOKEN_EXPIRES = timedelta(days=1)
JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=15)
JWT_IDENTITY_CLAIM = "sub"
JWT_HEADER_NAME = "Authorization"
JWT_HEADER_TYPE = "Token"
JWT_SESSION_COOKIE = False
JWT_ERROR_MESSAGE_KEY = "message"
JWT_ACCESS_COOKIE_PATH = "/"
JWT_REFRESH_COOKIE_PATH = "/token/refresh"
JWT_COOKIE_DOMAIN = ".xyz.co"
JWT_COOKIE_CSRF_PROTECT = True
JWT_COOKIE_SAMESITE = "Lax"

jwt = JWTManager()

def user_loader_callback(identity):
    return User.objects.get(id=identity)


def custom_user_loader_error(identity):
    ret = {
        "msg": "User {} not found".format(identity)
    }
    return jsonify(ret), 404

jwt.init_app(app)
jwt.user_loader_callback_loader(user_loader_callback)
jwt.user_loader_error_loader(custom_user_loader_error)

api = Api()

def response_with_token_cookies(res_data, status_code, user=None, identity=None):
    if not user:
        user = current_app.user.get_user(identity)
    response = make_response(jsonify(res_data), status_code)
    access_token = create_access_token(identity=user, fresh=True)
    refresh_token = create_refresh_token(identity=user)
    set_access_cookies(response, access_token)
    set_refresh_cookies(response, refresh_token)
    return response


class UserLogin(Resource):

    def post(self):
        data = request.get_json()
        schema = UserLoginSchema()
        data = schema.load(data)
        user, error = self.validate_user(**data)
        if not error:
            user = self.__update_trackable(user)
            return response_with_token_cookies({"message": "Logged in successfully"}, 200, user)
        raise response_data({"message": error}, 401)

    @staticmethod
    def validate_user(**kwargs):
        error_messages = []
        user = current_app.user.get_user(kwargs.get("email"))
        if user is None:
            error_messages.append(get_message('USER_DOES_NOT_EXIST')[0])
        if not verify_and_update_password(kwargs.get("password"), user):
            error_messages.append(get_message('INVALID_PASSWORD')[0])
        if requires_confirmation(user):
            error_messages.append(get_message('CONFIRMATION_REQUIRED')[0])
        if not user.is_active:
            error_messages.append(get_message('DISABLED_ACCOUNT')[0])
        return user, error_messages

    @staticmethod
    def __update_trackable(user):
        remote_addr = request.remote_addr or None  # make sure it is None
        old_current_login, new_current_login = user.current_login_at, datetime.now()
        old_current_ip, new_current_ip = user.current_login_ip, remote_addr
        user.last_login_at = old_current_login or new_current_login
        user.current_login_at = new_current_login
        user.last_login_ip = old_current_ip
        user.current_login_ip = new_current_ip
        user.login_count = user.login_count + 1 if user.login_count else 1
        return current_app.user.put(user)


api.add_resource(auth_apis.UserLogin, '/token')



Using python requests I do get this response but don't know why it becomes secure in case of browser

**Comment by mishraamrish** [comment]
I found this,

https://stackoverflow.com/questions/52763345/browsers-ignore-set-cookie-response-header-if-we-try-to-set-a-cookie-which-was-s
This is the exact problem, I guess.

**Comment by vimalloc** [comment]
Ugh. Well that's really dumb and annoying. I guess you could try changing the cookie names via the `JWT_ACCESS_CSRF_COOKIE_NAME` and `JWT_REFRESH_CSRF_COOKIE_NAME` options to get around that, but it feels like a pretty brittle band-aid for the issue at hand. I don't know what else to do for this situation thoug. Sorry! 😞
