### ISSUE TITLE
Type annotations / type hints / stub files for mypy

### ISSUE THREAD

**Issue by MartinThoma** [vimalloc/flask-jwt-extended#364]
Are there plans to add type annotations or stub files for mypy?

In case you need some more information about type annotations: https://medium.com/analytics-vidhya/type-annotations-in-python-3-8-3b401384403d

**Comment by vimalloc** [comment]
Yep, we have a ticket for it already in #299. I need to 4.0.0 released first, which is basically done sans documentation. One day I'll find time to really dive into that 😞 

If you want to help with this effort you are more then welcome to start adding type annotations on the 4.0.0 branch!
