### ISSUE TITLE
I want to secure all routes

### ISSUE THREAD

**Issue by nikoloskid** [vimalloc/flask-jwt-extended#365]
Hello!
I want to secure all routes with jwt_requried or verify_jwt_in_request. Please point me in how to achieve this.
Will appreciate any help!

**Comment by vimalloc** [comment]
You will want to use `@app.before_request` and `verify_jwt_in_request()`, something like this (untested):

```python
from flask_jwt_extended import verify_jwt_in_request

@app.before_request
def before_request():
    verify_jwt_in_request() 
```
