### ISSUE TITLE
Token expires time calculated from request connection begin

### ISSUE THREAD

**Issue by luzik** [vimalloc/flask-jwt-extended#371]
I have an issue with token that expires while uploading big files. Upload can take as long as 30 minutes, and time is calculated not from the connection start. 
1. Is there any way to change this behavior ?
2. Any workaround ?

**Comment by vimalloc-mavenlink** [comment]
The token will only be validated right before your application endpoint code is hit. Is it taking 30 minutes to upload the file prior to the flask protected endpoint being hit? If that's the case you could make your token be valid for longer, or re-work your approach into a multi action approach (e.g. hit an endpoint to say you want to upload a file, that returns a url or whatever to actually do the file upload, then do the file upload to that second endpoint). Regardless I think this falls outside of the context of this library.
