### ISSUE TITLE
Update to pyjwt 2.0.1

### ISSUE THREAD

**Issue by MartinThoma** [vimalloc/flask-jwt-extended#386]
https://pyjwt.readthedocs.io/en/2.0.1/changelog.html#v2-0-0
 - Python 2 support has been dropped
 - Tokens are returned as string instead of a byte string (!)

**Comment by MartinThoma** [comment]
See also: https://github.com/jpadilla/pyjwt/issues/529

**Comment by vimalloc** [comment]
This is already done in the 4.0.0 branch, which will be released once I finish writing documentation. In the mean time upgrade to flask jwt extended 3.25.1 that has the PyJWT dependency correctly pinned.
