### ISSUE TITLE
Object of type function is not JSON serializable - Flask (Flask rest x)

### ISSUE THREAD

**Issue by sleonte0182** [vimalloc/flask-jwt-extended#389]
Hi, today I have noticed that my Docker running a Flask REST service was failing, so I investigated a little bit and I'm getting the following trace (provided below) and I saw it's because some changes in the library, 3.25.0 was working fine.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 271, in handle
>     keepalive = self.handle_request(req, conn)
>   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 638, in error_router
>     return original_handler(f)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 636, in error_router
>     return self.handle_error(e)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 638, in error_router
>     return original_handler(f)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 636, in error_router
>     return self.handle_error(e)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 379, in wrapper
>     return self.make_response(data, code, headers=headers)
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 402, in make_response
>     resp = self.representations[mediatype](data, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/flask_restx/representations.py", line 25, in output_json
>     dumped = dumps(data, **settings) + "\n"
>   File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
>     return _default_encoder.encode(obj)
>   File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type function is not JSON serializable
> 
> 

A little bit of our test environment:

requirements.txt:

> flask_restx
> flask_jwt_extended
> py-healthcheck

Dockerfile:

> FROM python:3.7-buster
> ENV APP_HOME /app
> ENV PORT 8080
> WORKDIR $APP_HOME
> COPY . ./
> 
> 
> RUN pip install -r ./requirements.txt
> RUN pip install gunicorn
> 
> CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app
> 

And app.py being any example found at https://flask-restx.readthedocs.io/en/latest/example.html that is using @flask_jwt_extended.jwt_required to access any REST method.

I hope I've provided you the info your need to look into it, but if you need more please don't hesitate to contact me as I'm willing to help and reproduce this for you if needed!

Thank you!

**Comment by vimalloc** [comment]
That’s to be expected if you don’t have flask-jwt-extended pinned to a major version. Version 4.0.0 was just released, which as indicated by the major version bump includes breaking changes. You can see all of those changes here:  https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/
