### ISSUE TITLE
Where is the version 3 documentation? 

### ISSUE THREAD

**Issue by pedrolucasl** [vimalloc/flask-jwt-extended#396]
Where is the version 3 documentation? Despite going to 4 many people are still in version 3 and have to keep supporting it even if there are new versions. And in the read the docs all the documentation points to v4

**Comment by vimalloc** [comment]
Good call. Version 3 documentation should now show up as an available option when selecting versions on the stable documentation page (might need a browser cache clear, looks like RTD does some pretty aggressive caching), or can be viewed directly by going to https://flask-jwt-extended.readthedocs.io/en/3.0.0_release/
