### ISSUE TITLE
Version 4.0.2 breaks blueprints

### ISSUE THREAD

**Issue by zrajna** [vimalloc/flask-jwt-extended#398]
After updating to 4.0.2 and fixing all "breaking changes" from doc like jwt_optional => jwt_required(optional=True), the app still fails to run, because it cannot register [blueprint_page_name].wrapper since a function with that name already exists. Was this version tested with blueprints? I will try to get together a minimal failing example soon, for now I needed to revert my project to 3.25.1.

**Comment by vimalloc** [comment]
Blueprints seem to still work fine for me. An simple app that uses a blueprint:

```python
from flask import Blueprint
from flask import Flask
from flask import jsonify

from flask_jwt_extended import create_access_token
from flask_jwt_extended import jwt_required
from flask_jwt_extended import JWTManager

test_bp = Blueprint('test', __name__)


@test_bp.route("/login", methods=["POST"])
def login():
    access_token = create_access_token(identity='example_user')
    return jsonify(access_token=access_token)


@test_bp.route("/protected")
@jwt_required()
def protected():
    return jsonify(foo="bar")


if __name__ == "__main__":
    app = Flask(__name__)
    jwt = JWTManager(app)
    app.config["JWT_SECRET_KEY"] = "super-secret"  # Change this!
    app.register_blueprint(test_bp)
    app.run()
```

And seeing that it works as expected:

```bash
$ http POST :5000/login
HTTP/1.0 200 OK
Content-Length: 299
Content-Type: application/json
Date: Sat, 20 Feb 2021 21:28:22 GMT
Server: Werkzeug/1.0.1 Python/3.8.6

{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYxMzg1NjUwMiwianRpIjoiZWM2OGQxMmMtODI0Mi00MWQ0LThiNWMtMGYwN2RkYTlkYzNjIiwibmJmIjoxNjEzODU2NTAyLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoiZXhhbXBsZV91c2VyIiwiZXhwIjoxNjEzODU3NDAyfQ.CoxZvFr7AgdUz2Wrz8Mrq_iaO89mpEaL7WcHOkl3n9A"
}


$ export JWT="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYxMzg1NjUwMiwianRpIjoiZWM2OGQxMmMtODI0Mi00MWQ0LThiNWMtMGYwN2RkYTlkYzNjIiwibmJmIjoxNjEzODU2NTAyLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoiZXhhbXBsZV91c2VyIiwiZXhwIjoxNjEzODU3NDAyfQ.CoxZvFr7AgdUz2Wrz8Mrq_iaO89mpEaL7WcHOkl3n9A"


$ http GET :5000/protected Authorization:"Bearer $JWT"
HTTP/1.0 200 OK
Content-Length: 14
Content-Type: application/json
Date: Sat, 20 Feb 2021 21:28:45 GMT
Server: Werkzeug/1.0.1 Python/3.8.6

{
    "foo": "bar"
}
```



 Are you sure you have everything setup correctly in your application? If you provide a minimal complete and verifiable example I would be happy to look and see if anything stands out.

**Comment by Rukeith** [comment]
I got the same issue.
@vimalloc If you have two routes and have the same @jwt_required then you will get the error.

**Comment by vimalloc** [comment]
What do you mean two routes that have the same @jwt_required?? Can you provide a code example please?

**Comment by Rukeith** [comment]
Sorry, it's my bad description. Here is the error while I upgrade `flask-jwt-extended` to 4.0.2.
I will try to add the example later.

```
Traceback (most recent call last):
  File "./flasky.py", line 62, in <module>
    app = create_app(config=config)
  File "./loupe/__init__.py", line 35, in create_app
    app.register_blueprint(alerting_blueprint)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1168, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/local/lib/python3.8/site-packages/flask/blueprints.py", line 256, in register
    deferred(state)
  File "/usr/local/lib/python3.8/site-packages/flask/blueprints.py", line 294, in <lambda>
    self.record(lambda s: s.add_url_rule(rule, endpoint, view_func, **options))
  File "/usr/local/lib/python3.8/site-packages/flask/blueprints.py", line 81, in add_url_rule
    self.app.add_url_rule(
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1282, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: alerting.wrapper
```

**Comment by vimalloc** [comment]
I really need a code example to troubleshoot this further. That error you are seeing comes from core flask when you try to decorate two functions that have the same name, like:

```python
from flask import Blueprint
from flask import Flask
from flask import jsonify
    
app = Flask(__name__)

@app.route("/baz")
def test1():
    return jsonify(foo="bar")


@app.route("/foo")
def test1():
    return jsonify(foo="bar")


if __name__ == "__main__":
    app.run()
```

I have not had any luck triggering any unexpected behaviors around this while using flask-jwt-extended.

**Comment by kraglalbert** [comment]
@vimalloc I just ran into this issue as well. In my case I have an app with a single blueprint, in which the `views.py` file for that blueprint has multiple routes with the `@jwt_extended` decorator. If I leave only a single route with the `@jwt_extended` decorator then the app runs fine, but as soon as I protect 2 or more routes with the `@jwt_extended` decorator the app fails to run with the following error:
```
AssertionError: View function mapping is overwriting an existing endpoint function: main.wrapper
```

Here's what my `views.py` file looks like:
```python
from flask import Blueprint

main = Blueprint("main", __name__)


@main.route("/", methods=["GET"])
def index():
    return "Welcome!"


@main.route("/mentors", methods=["GET"])
@jwt_required
def get_all_mentors():
    # route logic omitted


@main.route("/mentors/<id>", methods=["GET"])
# if this line below is commented out, the app works and it errors otherwise
@jwt_required
def get_mentor_by_id(id):
    # route logic omitted

# additional routes also omitted
```

Hopefully that helps. If you need anything else let me know and I can try to give you more info!

**Comment by c-simpson** [comment]
@kraglalbert   Does it work if you use `@jwt_required()`  as per  
 https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/#api-changes ?

**Comment by kraglalbert** [comment]
> @kraglalbert Does it work if you use `@jwt_required()` as per
> https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/#api-changes ?

That fixed it, thanks!

**Comment by vimalloc-mavenlink** [comment]
Thanks @c-simpson! :+1:

**Comment by zrajna** [comment]
That's it, thanks @c-simpson!
The changes doc could point out this clearlier that *all* decorators need to be changed for v4.

**Comment by vimalloc** [comment]
> The changes doc could point out this clearlier that _all_ decorators need to be changed for v4.

I mean, it’s right there, I’m not sure what else you want...

```
All view decorators have been moved to a single decorator:
@jwt_required is now @jwt_required()
@jwt_optional is now @jwt_required(optional=True)
@fresh_jwt_required is now @jwt_required(fresh=True)
@jwt_refresh_token_required is now @jwt_required(refresh=True)
```

But if you feel this could be worded in a clearer way, feel free to open a pull request with any improvements. Updates are always welcome.

**Comment by zrajna** [comment]
I'm wondering too how to put it, because I have read those lines and did not realize the parentheses. :) Sent a pull request now.
