### ISSUE TITLE
TypeError: jwt_required() missing 1 required positional argument: 'fn'

### ISSUE THREAD

**Issue by Deep-sea-boy** [vimalloc/flask-jwt-extended#399]
![image](https://user-images.githubusercontent.com/37582640/109094576-2add3e00-7755-11eb-89f9-f822718c102b.png)
![image](https://user-images.githubusercontent.com/37582640/109094666-52340b00-7755-11eb-9509-141baf6a5e52.png)

sometimes i use @jwt_required without error ,sometims i should use @jwt_required() 
What's causing this？ is python version ？or in windows and linux？

**Comment by vimalloc** [comment]
A new major version of flask-jwt-extended, 4.0.0, was recently released. See here for a list of all the breaking changes (including `@jwt_required` becoming `@jwt_required()`). https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/

**Comment by Deep-sea-boy** [comment]
Thank you so much. I thought I'd wait a few days for a reply. You are my Idol

**Comment by vimalloc** [comment]
No worries, always happy to help! 👍
