### ISSUE TITLE
Error in running implicit_refresh.py

### ISSUE THREAD

**Issue by shahkshitij15** [vimalloc/flask-jwt-extended#400]
Hey!
I keep getting the following error every time I run implicit_refresh.py.
ImportError: cannot import name 'get_jwt' from 'flask_jwt_extended' 

I have installed flask_jwt_extended. Please help!

**Comment by vimalloc** [comment]
`get_jwt` is renamed from `get_raw_jwt` in version 4.x.x. Make sure you upgrade your application to the newest version of flask-jwt-extended. See the documentation for a list of all the breaking changes in that version: https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/
