### ISSUE TITLE
Flask_jwt_extended is not recognized 

### ISSUE THREAD

**Issue by pmopedro** [vimalloc/flask-jwt-extended#403]
I'm trying to import Flask-JWT-Extended but I keep facing this error on my vs-code: 

Import "flask_jwt_extended" could not be resolved (PylancereportMissingImports)

I'm running a virtual env and there are these packages installed:
click   7.1.2
Flask    1.1.2
Flask-Cors    3.0.10
Flask-JWT-Extended 4.1.0
Flask-SQLAlchemy   2.4.4
itsdangerous       1.1.0
Jinja2             2.11.3
MarkupSafe         1.1.1
pip                21.0.1
PyJWT              2.0.1
setuptools         47.1.0
six                1.15.0
SQLAlchemy         1.3.23
Werkzeug           1.0.1

`from flask_jwt_extended import create_access_token
`
Every time I try to use it it turns into an error. I don't know if it's an issue related to an extension on my vs-code or a compatibility problem.
Thanks
Pedro

**Comment by pmopedro** [comment]
> I'm trying to import Flask-JWT-Extended but I keep facing this error on my vs-code:
> 
> Import "flask_jwt_extended" could not be resolved (PylancereportMissingImports)
> 
> I'm running a virtual env and there are these packages installed:
> click 7.1.2
> Flask 1.1.2
> Flask-Cors 3.0.10
> Flask-JWT-Extended 4.1.0
> Flask-SQLAlchemy 2.4.4
> itsdangerous 1.1.0
> Jinja2 2.11.3
> MarkupSafe 1.1.1
> pip 21.0.1
> PyJWT 2.0.1
> setuptools 47.1.0
> six 1.15.0
> SQLAlchemy 1.3.23
> Werkzeug 1.0.1
> 
> `from flask_jwt_extended import create_access_token `
> Every time I try to use it it turns into an error. I don't know if it's an issue related to an extension on my vs-code or a compatibility problem.
> Thanks
> Pedro

**Comment by c-simpson** [comment]
Does it import if you just have `import flask_jwt_extended` ?

**Comment by pmopedro** [comment]
I tried both...
import flask_jwt_extended
and 
import  flask-jwt-extended

**Comment by pmopedro** [comment]
I have uninstalled and installed VS code again and now everything seams to work fine

**Comment by juanmad** [comment]
If someone finds it useful I had the same problem, what I did was, delete virtual environment, reinstall requirements.txt without having flask-jwt-extended or jwt there. then pip install flask-jwt-extended jwt and it worked.
