### ISSUE TITLE
`You must call `@jwt_required()` or `verify_jwt_in_request` before using this method`

### ISSUE THREAD

**Issue by maggie0002** [vimalloc/flask-jwt-extended#404]
When executing the code taken from the docs (https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens/?highlight=refresh_expiring_jwts) to refresh tokens, I'm getting errors back:

`You must call '@jwt_required()' or 'verify_jwt_in_request' before using this method`. 

`Flask-JWT-Extended==4.1.0`

And a few other things that may have relevance:
```
Flask-RESTful==0.3.8
Flask-Cors==3.0.10
```

I see from the breaking changes something on this (https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/?highlight=verify_jwt_in_request), although when I add either the verify_ or jwt_required in the errors still occur. 

I'm using @current_app.after_request instead of @app.after_request as the app is built in a create_app function like the 'Flask factory' method. 

```
@current_app.after_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError) as ex:
        # Case where there is not a valid JWT. Just return the original respone
        print(inspect.stack()[0][3] + " - "
              + str(ex))
        return response
```

I'm going around in circles on this one, can't seem to work it out. I have changed `timedelta(minutes=30)` to  `timedelta(seconds=1)` in order to test the refresh, and it doesn't seem to get into the 'if' statement to refresh the token. 

Some other config related settings here too:

        # Flask variables #
        # JWT Auth
        JWT_TOKEN_LOCATION = ["headers", "cookies"]
        JWT_COOKIE_SECURE = False
        JWT_SECRET_KEY = get_secret_key()
        JWT_ACCESS_TOKEN_EXPIRES = timedelta(hours=1)
        PROPAGATE_EXCEPTIONS = True
        # Set below to False to prevent needing to pass additional header
        JWT_COOKIE_CSRF_PROTECT = False

**Comment by vimalloc** [comment]
I'm almost positive that you can't use `current_app` like that. From the docs:

> Flask automatically pushes an application context when handling a request. View functions, error handlers, and other functions that run during a request will have access to current_app.

I think current_app only exists in the context of a request, so if you try to do  a `@current_app.after_request` just hanging out in your code, the current app wont point to something that can actually store that after request for later use.

There are a couple ways you could fix this. The easiest is probably registering the `@app.after_request` directly in your `create_app()` function. Alternatively, if you are using blueprints, you could do a `@blueprint.after_request` to register that on a per-blueprint basis, but that would probably be annoying if you have a bunch of different blueprints that all needed to register the same after_request function.

**Comment by maggie0002** [comment]
What you are saying makes some sense. I pulled the current_app idea from here: https://stackoverflow.com/a/13754387

Not really following what you mean by 'registering the @app.after_request directly in your create_app()'.

**Comment by vimalloc** [comment]
Something like:

```python
def create_app():
    app = Flask(__name__)

    @app.before_request
    def refresh_expiring_jwts(response):
        # Do the thing

    app.register_blueprint(auth)
    return app
```

But I actually forgot about a way that's probably better, the `after_app_request` that can be used by a blueprint to register a callback that happens on any request, even ones that don't come to that specific blueprint. Something like:

```python
auth = flask.Blueprint('auth', __name__)

@auth.after_app_request
def do_something():
        def refresh_expiring_jwts(response):
        # Do the thing

def create_app():
    app = Flask(__name__)
    app.register_blueprint(auth)
    return app
```

**Comment by maggie0002** [comment]
Brilliant, thanks!

I'm not using blueprints, you think it's worth using the second method over the first one anyway?

**Comment by maggie0002** [comment]
Original code:

run.py

```
# Create Flask app instance and required databases
def create_app(config):
    # Initalise and configure Flask
    app = Flask(__name__)
    app.config.from_object(config)

    # Allow CORS
    CORS(app)

    # Setup Flask-JWT-Extended
    jwt = JWTManager(app)

    # Import database and migration process
    db.init_app(app)
    migrate.init_app(app, db)

    # Enable Flask-Restful API
    api = Api(app)
    return app, api, jwt
```

resources/auth_routes.py

```
# Refresh token on each authorised request
@current_app.after_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError):
        # Case where there is not a valid JWT. Just return the original respone
        return response
```

**Comment by maggie0002** [comment]
If I add the verify_jwt in I do see a different response. Using my original pattern, it now looks like this:

```
@current_app.after_request
def refresh_expiring_jwts(response):
    try:
        verify_jwt_in_request(optional=True)
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(seconds=1))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError) as ex:
        # Case where there is not a valid JWT. Just return the original respone
        print(ex)
        return response
```

And while the error messages keep repeating, I do get an alternate response on occasion (see the 'exp' being returned below).

```
127.0.0.1 - - [18/Mar/2021 10:46:02] "OPTIONS /v1/hostname HTTP/1.1" 200 -
127.0.0.1 - - [18/Mar/2021 10:46:02] "GET /v1/hostname HTTP/1.1" 200 -
You must call `@jwt_required()` or `verify_jwt_in_request` before using this method
127.0.0.1 - - [18/Mar/2021 10:46:09] "OPTIONS /v1/logout HTTP/1.1" 200 -
127.0.0.1 - - [18/Mar/2021 10:46:09] "POST /v1/logout HTTP/1.1" 200 -
You must call `@jwt_required()` or `verify_jwt_in_request` before using this method
127.0.0.1 - - [18/Mar/2021 10:46:09] "OPTIONS /v1/settingsui HTTP/1.1" 200 -
'exp'
```
127.0.0.1 - - [18/Mar/2021 10:46:09] "GET /v1/settingsui HTTP/1.1" 200 -

**Comment by vimalloc-mavenlink** [comment]
I mean, you are still doing `@current_app.after_request` which just isn't going to work.
You either need to use `@app.after_request` wherever you are creating your  `app`, or use blueprints with `@blueprint.after_app_request`. 

Blueprints are considered better practice when using the flask application factory, but how you decide to register routes depends entirely on your application. If I were building an app, I would do it with blueprints. Here is an example that might point you in the right direction. Do note that this isn't tested, and is more of just a general idea of how it might look like:

### extensions.py
```python
from flask_jwt_extended import JWTManager
jwt = JWTManager()
```

### auth_blueprint.py
```python
from flask import Blueprint
# All your other imports here

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.after_app_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError):
        # Case where there is not a valid JWT. Just return the original respone
        return response

@auth_blueprint.route('/login', methods=['POST'])
def login()
    response = jsonify({"msg": "login successful"})
    access_token = create_access_token(identity="example_user")
    set_access_cookies(response, access_token)
    return response
```

### app.py
```python
from extensions import jwt

from auth_blueprint import auth_blueprint

def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    jwt.init_app(app)
    return app
```


I don't use flask-restful, but it looks like they are fully compatible with blueprints as well: https://flask-restful.readthedocs.io/en/latest/intermediate-usage.html#use-with-blueprints

**Comment by maggie0002** [comment]
I tried:

**run.py**

```
from resources.auth_routes import auth_blueprint
...

jwt = JWTManager()

# Create Flask app instance and required databases
def create_app(config):
    # Initalise and configure Flask
    app = Flask(__name__)
    app.config.from_object(config)

    # Allow CORS
    CORS(app)

    # Setup Flask-JWT-Extended
    jwt.init_app(app)

    # Import database and migration process
    db.init_app(app)
    migrate.init_app(app, db)

    # Enable Flask-Restful API
    api = Api(app)

    # Register blueprint
    app.register_blueprint(auth_blueprint)

    return app, api

```

** auth_routes.py **

```
from flask import Blueprint
...


auth_blueprint = Blueprint('auth', __name__)

# Refresh token on each authorised request
@auth_blueprint.after_app_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(seconds=1))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError) as ex:
        # Case where there is not a valid JWT. Just return the original respone
        print(ex)
        return response

```

I also tried just adding it in directly, which I was sure would work, but still getting the same error:

```
# Create Flask app instance and required databases
def create_app(config):
    # Initalise and configure Flask
    app = Flask(__name__)
    app.config.from_object(config)

    # Allow CORS
    CORS(app)

    # Setup Flask-JWT-Extended
    jwt.init_app(app)

    # Import database and migration process
    db.init_app(app)
    migrate.init_app(app, db)

    # Enable Flask-Restful API
    api = Api(app)

    @app.after_request
    def refresh_expiring_jwts(response):
        try:
            exp_timestamp = get_jwt()["exp"]
            now = datetime.now(timezone.utc)
            target_timestamp = datetime.timestamp(now + timedelta(seconds=1))
            if target_timestamp > exp_timestamp:
                access_token = create_access_token(identity=get_jwt_identity())
                set_access_cookies(response, access_token)
            return response
        except (RuntimeError, KeyError) as ex:
            # Case where there is not a valid JWT. Just return the original respone
            print(ex)
            return response
    return app, api
```

I also tried the second approach under `with app.app_context():`

**Comment by vimalloc-mavenlink** [comment]
I think you're actually seeing that somewhere totally different. `You must call '@jwt_required()' or 'verify_jwt_in_request' before using this method` is raised as a runtime error, and in the `@app.after_request` you are catching that runtime error, so it has to be somewhere else in your code that you are running into the problem. Probably in a route function somewhere. Check the stack trace carefully and see if it points you to another location.

**Comment by maggie0002** [comment]
It seems like it has been working all along, but I have suffered from a severe case of the cookie ignorance. 

The message are expected, as it is running on the endpoints without the authentication set. That much was expected.
https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/?highlight=verify_jwt_in_request

It was in fact running on the endpoints with authentication enabled ok. Rather embarrassingly though, to test it I was changing the time delta to one second in the @after_request, not the config file. I should have been changing the @after_request value up not down. Doh. 

On the plus side, it seems I am able to confirm that it does work with the @current_app.after_request function. 

Really appreciate your input on this, and your time.

**Comment by ralf-t** [comment]
Hello, I think im having the same problem but im using .before_request() instead. I tried using .after_request this time but it still doesn't seem to work. Both approaches seem to ignore the response/header/cookie that's when I do print(verify_jwt_in_request()) it returns None even if the function is declared after bp registration and within the create_app function (that means I should be in the app context right?)

How were you able to make it work with the after_request function? I also want to refresh tokens before every request made on my API.

I hope I'm not misunderstanding things discussed here.
