### ISSUE TITLE
throwing 401 error for flask jwt extended refresh token

### ISSUE THREAD

**Issue by venkatn7** [vimalloc/flask-jwt-extended#412]
I am using @jwt_required(refresh=True) decorator to get new access_token, I can successfully get access_token and refresh_token when user logins, but when I send a post call from axios I get 401 error saying "Missing Authorization header".
my flask code:
```
@app.route("/refresh", methods=["POST"])
@jwt_required(refresh=True)
def refresh():
    identity = get_jwt_identity()
    print(identity)
    access_token = create_access_token(identity=identity)
    return jsonify(access_token=access_token)
    print(access_token) 
```

and my axios call:
```
getAPI.post('/refresh', {
          // refresh_token: context.state.refreshToken,
          headers: { Authorization: `Bearer ${context.state.refreshToken}` },
        })
```
I can successfully test the same refresh_token with postman and get new access_token. I am not sure why I cant do it when axios call any help is appreciated.

**Comment by vimalloc** [comment]
Looking at the axios API, it looks like you are using it incorrectly. The API for `.post` is `axios.post(url[, data[, config]])`. Your configuration options need to be the third argument instead of the second, which is the JSON data in the body of the request. Instead try something like this:

```javascript
getAPI.post('/refresh', {}, { headers: { Authorization: `Bearer ${context.state.refreshToken }` }})
```

**Comment by venkatn7** [comment]
That helped, thank you.
