### ISSUE TITLE
Upgrade from 4.0.2 to 4.1.0 - `user_lookup_loader` is no longer called.

### ISSUE THREAD

**Issue by janash** [vimalloc/flask-jwt-extended#414]
I'm upgrading my app from `flask-jwt-extended` version 4.0.2 to 4.1.0. Everything was working as intended using 4.0.2. However, upon updating to 4.1.0, users are no longer loaded upon login. Users are always set as `None`. I have my endpoints decorated with `jwt_required(optional=True)`. Here is the function which is working for 4.0.2

```
@jwt.user_lookup_loader
def user_loader_callback(jwt_header, jwt_payload):
    """Function for app, to return user object"""

    if jwt_header:
        username = jwt_payload["sub"]["username"]
        user = User.query.filter_by(username=username).one_or_none()

        return user
    else:
        # return None / null
        return None
```

Upon upgrading to 4.1.0, it seems this function is no longer called when `get_current_user()`. I have verified this by inserting a `breakpoint` as the first statement in the function above. Upon accessing a protected endpoint in version 4.0.2, the python debugger starts in my terminal. Using version 4.1.0 does not result in the python debugger opening upon accessing a protected endpoint which called `get_current_user()`,  implying that this code in the callback is not being executed. However, inspection using `inspect.getsource(jwt._user_lookup_callback)` in the python debugger shows the same function as defined above for both versions of this package.

```
'@jwt.user_lookup_loader\ndef user_loader_callback(jwt_header, jwt_payload):\n    """Function for app, to return user object"""\n\n    if jwt_header:\n        username = jwt_payload["sub"]["username"]\n        user = User.query.filter_by(username=username).one_or_none()\n\n        return user\n    else:\n        # return None / null\n        return None\n'
```

implying that the callback is being set properly. 

Any help is appreciated. Not sure what changes between `4.0.2` and `4.1.0` would cause this.

**Comment by vimalloc-mavenlink** [comment]
If I understand the issue correctly, it sounds like the `user_lookup_loader` callback isn't being fired when there is a JWT present in the request, is that correct?

I'm trying to reproduce this, but not having any luck so far. The code I'm using to repo this is:

```python
from flask import Flask
from flask import jsonify
from flask import request

from flask_jwt_extended import create_access_token
from flask_jwt_extended import get_current_user
from flask_jwt_extended import jwt_required
from flask_jwt_extended import JWTManager


app = Flask(__name__)
app.config["JWT_SECRET_KEY"] = "super-secret"  # Change this!
jwt = JWTManager(app)


class User:
    def __init__(self, username):
        self.username = username


@jwt.user_lookup_loader
def user_lookup_callback(_jwt_header, jwt_data):
    identity = jwt_data["sub"]
    if identity == "Jester":
        return User(identity)
    else:
        return None


@app.route("/login", methods=["POST"])
def login():
    username = request.json.get("username")
    access_token = create_access_token(identity=username)
    return jsonify(access_token=access_token)


@app.route("/who_am_i", methods=["GET"])
@jwt_required(optional=True)
def protected():
    user = get_current_user()
    if user:
        return jsonify(username=user.username)
    else:
        return jsonify(username=None)


if __name__ == "__main__":
    app.run()
```

And the results of this, trying with a user that is present, non present (from the callback), and no jwt in the request:

![Screen Shot 2021-04-14 at 4 30 02 PM](https://user-images.githubusercontent.com/61286277/114788665-212c8b80-9d3f-11eb-8229-72ab3a18f7da.png)

Could I get some clarification on if I'm misunderstanding the issue, or more code to be able to reproduce this locally?

**Comment by janash** [comment]
Hi @vimalloc-mavenlink - Thanks for looking into this and I apologize because I've now realized the error. I am using cookies with CSRF protection on and had patched the function `_decode_jwt_from_cookies` to only check CSRF on API routes. I am using `flask-forms` on the front end, so anything that comes posted to those forms already has CSRF protection. The patch essentially is setting another option in the config (the URL prefix 'api' and adding the check for that prefix to the statement `if config.csrf_protect and request.method`). I was having trouble interfacing the CSRF tokens from flask-jwt-extended and flask-forms.

I updated my patched `_decode_jwt_from_cookies` function and now all seems to be working fine (I noticed that this function changed a bit recently). This seems like not an ideal solution, so may I ask what you would recommend. The main problem I had was that I did not know how to send the CSRF token from flask_jwt_extended with the POST from from flask-wtforms.

Again, apologies and thank you for looking into it. I've also discovered httpie (that's what you're using right?). Seems like a cool utility.

**Comment by vimalloc-mavenlink** [comment]
Awesome, glad you got that figured out.

> I updated my patched _decode_jwt_from_cookies function and now all seems to be working fine (I noticed that this function changed a bit recently). This seems like not an ideal solution, so may I ask what you would recommend. 

Now that the `jwt_requried` decorator can take arguments, I bet we could add a `csrf` argument which overrides the global `JWT_CSRF_PROTECT` option on a per-endpoint basis. This would be almost exactly the same as the `locations` argument that was added in 4.x.x I think. I think that would probably be a much nicer way of handling things for this use case.

> I've also discovered httpie (that's what you're using right?). Seems like a cool utility.

Indeed it is! Httpie is great, makes things much simpiler compared to something like curl, IMO.
