### ISSUE TITLE
@jwt.expired_token_loader Not Loaded

### ISSUE THREAD

**Issue by benschaedlich** [vimalloc/flask-jwt-extended#415]
While using the new version Flask-JWT-Extended==4.1.0 I expirenced issues with invalid tokens: When a token expires the expired_token_loader is not triggered and Flask returns a 500

raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
127.0.0.1 - - [20/Apr/2021 21:11:23] "GET /api/auth/login HTTP/1.1" 500 -

How can I fix this? I would really like to use the new version and not downgrade...

**Comment by vimalloc-mavenlink** [comment]
It's probably another flask extension interfering with things, the exceptions are absolutely being properly handled in flask-jwt-extended when using just flask. My first suggestion is to Check out #86 and see if anything there helps out.

**Comment by benschaedlich** [comment]
@vimalloc-mavenlink  Thanks for your reply and also pointing out #86 . Although it didnt help my problem excaty it pointed out the right direction. You are right: I am using a flask blueprint in combination with flask-restful API extension which caused the behaviour described above.

However, I have found a solution: Everything that needs to be done is add custom errors to while initilizing the Flask-Restful API object:

`from app import app
from flask import Blueprint
from flask_restful import Api


api_bp = Blueprint('api', __name__)
errors = {
'ExpiredSignatureError': {
'message': "Token Expired",
'status': 401,
},
}

api = Api(api_bp, errors=errors)
`
