### ISSUE TITLE
AssertionError: View function mapping is overwriting an existing endpoint function: wrapper

### ISSUE THREAD

**Issue by GoekhanDev** [vimalloc/flask-jwt-extended#418]
Hello, Im coding a REST API for a website I got his problem when I use @jwt_required. Couldn't find any solutions on the internet so I thought asking here would be the only option.

My Code: 

```python
@app.route('/login', methods=['POST'])
def login():
    email = request.json.get('email', None)
    password = request.json.get('password', None)

    try:

        user = mydb["User"].find_one({"Email": email})
        
        if user is None:
            raise Exception("User doesn't")

        valid = check_password_hash(user['password'], password)
        if not valid:
            raise Exception('Password not correct')

        access_token = create_access_token(
            identity=user['id'], expires_delta=None)
        refresh_token = create_refresh_token(
            identity=user['id'], expires_delta=None)


        ret = {
            'access_token': access_token,
            'refresh_token': refresh_token
        }
        return jsonify(ret), 200
    except Exception as e:
        return jsonify({'Error': repr(e)})


@app.route('/logout', methods=['POST'])
@jwt_required
def logout():
    jti = get_jwt()['jti']
    blacklist.add(jti)
    return jsonify({"message": "Successfully logged out"}), 200


@app.route('/protected', methods=['POST'])
@jwt_required
def protected():
    username = get_jwt_identity()
    return jsonify(logged_in_as=username), 200


@app.route('/refresh_token', methods=['POST'])
@jwt_required
def refresh():

    current_user = get_jwt_identity()
    ret = {
        'access_token': create_access_token(identity=current_user, expires_delta=None)
    }
    return jsonify(ret), 200

if __name__ == '__main__':
    app.run(debug=True, port=80)
```

ERROR: 

> ```
> Traceback (most recent call last):
>     self.add_url_rule(rule, endpoint, f, **options)
>   File "C:\Users\VRX\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 98, in wrapper_func
>     return f(self, *args, **kwargs)
>   File "C:\Users\VRX\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1282, in add_url_rule
>     raise AssertionError(
> AssertionError: View function mapping is overwriting an existing endpoint function: wrapper
> ```

Thanks in advance.

**Comment by vimalloc-mavenlink** [comment]
As of version 4.x.x, it is now `@jwt_required()` instead of `jwt_required`. If you are updating an existing application, you can find a link to all of the breaking changes in the 4.x.x release on the README. 👍

**Comment by GoekhanDev** [comment]
> As of version 4.x.x, it is now `@jwt_required()` instead of `jwt_required`. If you are updating an existing application, you can find a link to all of the breaking changes in the 4.x.x release on the README. 👍

Thanks!
