### ISSUE TITLE
POST with @jwt_required() 

### ISSUE THREAD

**Issue by GoekhanDev** [vimalloc/flask-jwt-extended#423]
Hello,

Im implementing coinbase ecommerce to my website, to create a charge im making a request to coinbase and parsing the payment url to redirect the user.

With clicking the "Buy Now" button a form post request is being made to be able to make this request and redirect the user.

```html
<form method="post" action="/pricing">
   <input type="hidden" name="csrf_token" id="CRSF" value="{{ csrf_token() }}"/>
   <input type="hidden" name="plan" id="plan" value="Daily"/>
   <button type="submit" style="width: 98%;"class="btn btn-lg btn-soft-primary px-lg-2">
      Buy Now 
      <svg class="ms-1" data-name="icons/tabler/chevron right" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 16 16">
         <rect data-name="Icons/Tabler/Chevron Right background" width="16" height="16" fill="none"></rect>
         <path d="M.26.26A.889.889,0,0,1,1.418.174l.1.086L8.629,7.371a.889.889,0,0,1,.086,1.157l-.086.1L1.517,15.74A.889.889,0,0,1,.174,14.582l.086-.1L6.743,8,.26,1.517A.889.889,0,0,1,.174.36Z" transform="translate(4)" fill="#0D6EFD"></path>
      </svg>
   </button>
</form>

```

The issue here is that because im using @jwt_required() it's showing me `{ "msg": "Missing CSRF token" }` as error. Even when the cookies are passed.

Thanks in Advance.
Kind Regards.

**Comment by GoekhanDev** [comment]
This is persists when using POST as method.

**Comment by vimalloc** [comment]
You need to manually pass in the CSRF token, otherwise your endpoint will be vulnerable. For forms, you will want to do a few things to get that setup.

First, set `app.config['JWT_CSRF_CHECK_FORM'] = True`.

Second, add this to your template that is rendering the form: `<input name="csrf_token" type="hidden" value="{{ csrf_token }}">`

Third, in the `render_template` call that is rendering that form, add this argument: `csrf_token=get_jwt()["csrf"]`.

**Comment by GoekhanDev** [comment]
Thank you very much, fixed my issue that I've been trying to fix for hours now.

**Comment by Iamrodos** [comment]
> You need to manually pass in the CSRF token, otherwise your endpoint will be vulnerable. For forms, you will want to do a few things to get that setup.
> 
> First, set `app.config['JWT_CSRF_CHECK_FORM'] = True`.
> 
> Second, add this to your template that is rendering the form: `<input name="csrf_token" type="hidden" value="{{ csrf_token }}">`
> 
> Third, in the `render_template` call that is rendering that form, add this argument: `csrf_token=get_jwt()["csrf"]`.
> 
> Alternatively, if you are ever using ajax calls instead of forms, you can see the documentation around including the csrf_token in the request here: https://flask-jwt-extended.readthedocs.io/en/stable/token_locations/#cookies

I wish I had found this a few hours ago. I read the documentation a few times but never mentioned this. It would be great if the example at https://flask-jwt-extended.readthedocs.io/en/stable/token_locations/#cookies mentioned this as well as the existing one.
