### ISSUE TITLE
Support Flask 2.0

### ISSUE THREAD

**Issue by sjhewitt** [vimalloc/flask-jwt-extended#426]
Flask v2.0 just came out: https://palletsprojects.com/blog/flask-2-0-released/

As far as I can tell, there's no breaking changes so it would be good to relax the `<2` dependency requirement in setup.py.

I'm going to test it out on our project to see if there are any issues, however we don't use the full range of `flask-jwt-extended` features.

**Comment by vimalloc-mavenlink** [comment]
Thanks for the heads up! Got a PR running through specs with that change now, assume everything looks good I'll get a new release cut as soon as I'm off of work! :+1:

**Comment by vimalloc** [comment]
Flask 2.x.x support has been released in Flask-JWT-Extended 4.2.1 :+1:

**Comment by sjhewitt** [comment]
> Flask 2.x.x support has been released in Flask-JWT-Extended 4.2.1 +1

Amazing! Thanks so much for the prompt release!
