### ISSUE TITLE
Add some documentation about porting from flask-jwt

### ISSUE THREAD

**Issue by dusktreader** [vimalloc/flask-jwt-extended#43]
It would be handy if there was a document that highlighted the difference between this package and flask-jwt. Specifically, it would be useful to know what has to be done differently to use this in place of flask-jwt. It appears that this isn't a drop-in replacement. In particular, the identity callback and login route don't seem to be present here.

**Comment by vimalloc** [comment]
Indeed it is not a drop in replacement. This was built from the ground up, with the intent of adding new features and avoiding some things that I believe are design mistakes in Flask-JWT. 

Per the two mentioned differences, you can see some discussion on why I went the route I did here:
* login route: https://github.com/vimalloc/flask-jwt-extended/issues/8
* Identity callback: https://github.com/vimalloc/flask-jwt-extended/issues/30

When I have some more time, I'll look at adding a comparison page in the documentation between this and Flask-JWT. Thanks for the suggestion :+1:

**Comment by vimalloc** [comment]
FYI, the identity callback was just added as an optional feature to this extension. You can see how it would look here: http://flask-jwt-extended.readthedocs.io/en/latest/complex_objects_from_token.html

Cheers

**Comment by dusktreader** [comment]
@vimalloc I elected to use PyJWT directly in my flask-praetorian package to keep things slimmer. Thanks for the great work on this package, though.

I think you should push for renaming this to flask-jwt, since that package looks quite dead

**Comment by vimalloc** [comment]
Good luck with your extension! pyjwt is a great library :)
