### ISSUE TITLE
[Question] Difference between jwt_required and verify_jwt_in_request

### ISSUE THREAD

**Issue by chadbr** [vimalloc/flask-jwt-extended#433]
Forgive me if this is the docs -- I've searched the docs and issues but I don't see anything that describes this.

What is the difference between jwt_required and verify_jwt_in_request?

When I add @jwt_required to my blueprint methods, all the methods execute just fine.

When I call verify_jwt_in_request I get an error verifying the signature here:

```python
        if algorithms is not None and alg not in algorithms:
            raise InvalidAlgorithmError("The specified alg value is not allowed")
```

Shouldn't they be doing the same thing?

If not, when should someone be verifying (verify_jwt_in_request) vs. simply checking (jwt_required)

---

A little background -- I'm trying to verify an OAuth2 Google token... if that clarifies anything. I'm not seeing any docs on how I should or should not be verifying these tokens.

Thanks - and apologies if these questions are too basic.

**Comment by chadbr** [comment]
Also - fwiw - I cannot figure out how to verify the Google token ... when I add RS256 to the algorithms - everything just fails?

JWT_ALGORITHM="RS256"
JWT_DECODE_ALGORITHMS=["HS256","RS256"]

**Comment by vimalloc-mavenlink** [comment]
There is no functional different, `@jwt_required` is just a decorator that calls `verify_jwt_in_request` before calling the decorated method.

If you are seeing an error with `verify_jwt_in_request` and not seeing an error with `@jwt_required()`, you probably have a logic bug or something where that decorator isn't actually being applied, or it's not being applied before the view function is already called.
