### ISSUE TITLE
4.2.2 broke Flask 1.x.x

### ISSUE THREAD

**Issue by vimalloc-mavenlink** [vimalloc/flask-jwt-extended#437]
I'll get a quick fix out ASAP. Tomorrow (after releasing the fix) I'll make sure to add a unit test around this to prevent breakages in the future 😞

**Comment by vimalloc** [comment]
Fix has been released in 4.2.3. I'll work on better test setup so this doesn't happen again tomorrow :+1:

**Comment by haqduong** [comment]
I still got this error in 4.2.3, I think you should check for phrase `"'Flask' object has no attribute 'ensure_sync'"` is contained in e but not only equal.

**Comment by StefanVDWeide** [comment]
@haqduong can you share more information on how you produced the error? I can't seem to replicate it in 4.2.3 with Flask 1.1.4.

@vimalloc Happy to help you with the test setup to prevent this from happening again if needed since I was the one who introduced the Flask 2.0 support. Has any progress been made yet?

**Comment by vimalloc-mavenlink** [comment]
I might change the logic to something like this, might be less error prone: https://stackoverflow.com/a/7580687/272689

@StefanVDWeide Per the specs, I haven't actually looked much into it yet. i would totally welcome a PR if you want to help dig into it. At a glance I didn't see a way to configure tox with different versions of the same package but I might be missing something.

**Comment by StefanVDWeide** [comment]
@vimalloc I've gone ahead and took a first stab at both implementing a better version check as per the SO post you shared (seems like a good solution) and adding an extra test environment to tox which uses flask 1.1.4

https://github.com/vimalloc/flask-jwt-extended/pull/440

Let me know what you think!

**Comment by haqduong** [comment]
@StefanVDWeide thank you for your reply, I saw it once when call stack is quite complex but I lost the log atm. But I really like your PR, it's much better implementation for the issue.

**Comment by StefanVDWeide** [comment]
@vimalloc I think now that https://github.com/vimalloc/flask-jwt-extended/issues/437 is merged we can close this issue. Thanks for thinking along and the quick actions!
