### ISSUE TITLE
Problem with CSRF Cookie

### ISSUE THREAD

**Issue by essembeh** [vimalloc/flask-jwt-extended#439]
Hi 

Recently I started developing a webapp using a restful api and I use  flask-jwt-extended  to secure it.
My webapp has some html/javascript pages which use the api to render the data.
I use ajax get/post/put/delete to manipulate my resources through my api.

I noticed that when the API is used from ajax, I got my POST/DELETE/PUT returning 401.
Some debugging showed me that since I configured  `JWT_COOKIE_CSRF_PROTECT=True` the CSRF token couldn't be verified.
Inspecting the request, I noticed that the `csrf_access_token` was set (because the auth endpoint called previously sets it), but I was missing the header.

I tried to get the csrf token from the cookie if the header was missing and it worked well for my workflow, see the changes I made here:
https://github.com/essembeh/flask-jwt-extended/commit/f94f2b504c3ddd09d934d8a871336c098efa84b8

As the unit tests fail, I think getting the csrf token from the cookie might not be the correct approach, maybe you could give some details about that?
That is to say I have to set it as a header?

Thanks

**Comment by vimalloc** [comment]
Make sure to read the documentation here closely: https://flask-jwt-extended.readthedocs.io/en/stable/token_locations/#cookies

The tl;dr is your instinct about that change is correct. If you read that value from the cookie directly there would be no cross site request forgery protection going on, and your application would be vulnerable to CSRF attacks. That’s why we have to manually  include the header that which contains the double submit verification token.

**Comment by essembeh** [comment]
As a beginner web developper, I didn't understand exactly the workflow when I first read the doc.
Thanks for the extra explanation, I re-read and I understand how reading the token from the cookie is not secure.

I close this ticket.
