### ISSUE TITLE
Possibility to disable Remember Me-esque functionality when refreshing tokens

### ISSUE THREAD

**Issue by Destaq** [vimalloc/flask-jwt-extended#445]
I'm refreshing user tokens implicitly with cookies, as detailed in the docs [here](https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens/#implicit-refreshing-with-cookies). However, I'm at a loss at how to securely prevent this from happening when the user would not like to always remain logged-in.

```python3
@app.after_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError):
        # Case where there is not a valid JWT. Just return the original respone
        return response
```

Since the cookies are set as soon as the user is logged in, and refreshed every time they have expired or are in danger of expiry, remember me functionality is essentially enabled by default. Is there a way to allow for the user to choose if expiring JWTs will be refreshed (and for example if they choose no, having an auto-logout on browser close/in 2 hours)?

**Comment by vimalloc** [comment]
> Since the cookies are set as soon as the user is logged in, and refreshed every time they have expired

This is actually inaccurate. If a token has already expired, then `get_jwt()["exp"]` will throw an exception and the original response will be returned without issuing a new access token. For example, if you put your expires time to something like 1 hours then it will log the user out roughly 1 hours of inactivity even when implicitly refreshing JWTs.

> Is there a way to allow for the user to choose if expiring JWTs will be refreshed

Sure, save that information in your database somewhere and add an `if` block to this after request, where you skip automatic token refreshing depending on their preference.

> remember me functionality is essentially enabled by default.

This doesn't really have anything to do with `remember me` imo. The whole process of implict refresh is to prevent a user from being logged out while in the middle of doing something on your site.

> having an auto-logout on browser close/in 2 hours

Use [JWT_SESSION_COOKIE](https://flask-jwt-extended.readthedocs.io/en/stable/options/#JWT_SESSION_COOKIE) to control if the cookies are removed when the browser is closed, and use [JWT_ACCESS_TOKEN_EXPIRES](https://flask-jwt-extended.readthedocs.io/en/stable/options/#JWT_ACCESS_TOKEN_EXPIRES) to control the expiry times of the cookies.

**Comment by Destaq** [comment]
Thank you for your reply, it seems I've misunderstood the way that the implicit cookie refreshing works. I'm clear now on how to disable the functionality, but it seems I haven't properly set up remember me in the first place.

I've looked through the docs for an example, but the only thing close to what I was looking for was the [implicit cookie refresh pattern](https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens/), which is recommended for my use case of a website. In this case, would you recommend simply increasing the expiry time to something very long like a year in order to _enable_ Remember Me? Or how would you suggest approaching this problem with the flask-jwt-extended library?

**Comment by vimalloc** [comment]
Sorry for the delay here, I somehow missed that you responded. I haven't given much thought to remember me so far, so take what I say with a grain of salt, but I imagine standard `remember me` best practices would work just fine with JWTs. I imagine for this a long lived refresh token would fit the bill nicely, and not conflict with implict access token refresh to prevent users who are actively using your site from being logged out.

**Comment by Destaq** [comment]
No worries, I've managed to figure it out this week. But I've encountered one last issue, this time regarding CSRF, which I hope you can answer.

Due to a limitation of the frontend library I'm working with, I have to set cookies client-side. Set the refresh and access tokens is not a problem, but setting the csrf token is - it seems that the only way to do this is server-side by using the `set_access_cookies` and `set_refresh_cookies` methods. If I just send the access token and refresh token to client side, they are set, but there is no data that can be used to set a csrf access and refresh token.

Do you know of a way to generate such csrf tokens to send to the frontend? I couldn't find any importable methods for doing so.

**Comment by vimalloc** [comment]
Totally!

First you can set the [JWT_CSRF_IN_COOKIES](https://flask-jwt-extended.readthedocs.io/en/stable/options/#JWT_CSRF_IN_COOKIES) configuration option to `false` to prevent those cookies from even attempting to be set, then you can use [get_csrf_token](https://flask-jwt-extended.readthedocs.io/en/stable/api/#flask_jwt_extended.get_csrf_token) to pull the csrf token out of an encoded jwt and send it to your frontend however you want. From there the frontend can do whatever it wants with the value, such as storing it in localstorage or putting it in a cookie. All that's important is that the csrf value gets included as a header when a request is made. :+1:

**Comment by Destaq** [comment]
Great, thanks so much for all your help!
