### ISSUE TITLE
Passing variable values from one route to another in a token authenticated flask application

### ISSUE THREAD

**Issue by aniyya** [vimalloc/flask-jwt-extended#450]
I have a flask token authenticated application implemented by flask jwt extended.

```
import random
import os
from flask import Flask, jsonify, request, session
from flask_cors import CORS
from flask_jwt_extended import create_access_token
from flask_jwt_extended import JWTManager
import json

app = Flask(__name__)
app.config["JWT_SECRET_KEY"] = "some secret key"
jwt = JWTManager(app)
CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'
secret_email = "xxxx@secure.com"
secret_pass = "password"

@app.route("/")
def home():
    return jsonify({"msg":"Hello, World!"})

@app.route("/login", methods=["POST"])
def login():
    email = request.json.get("email", None)
    password = request.json.get("password", None)
    if email != secret_email or password != secret_pass:
        return jsonify({"msg": "Bad username or password"}), 401

    access_token = create_access_token(identity=email)
    return jsonify(access_token=access_token)

@app.route("/configs")
def configs():
    a = random.randint(10,30)
    b = random.randint(1,5)
    summ = a+b
    return jsonify({"a":a,"b":b})

@app.route("/sumcollect")
def sumcollect():
    return jsonify({"sum is":summ})
    
if __name__ == "__main__":
    app.run(debug=False)
```

The summ variable in route /configs needs to be accessed in route /sumcollect . Is there any way to pass the variables when using jwt extended token authentication system

**Comment by vimalloc** [comment]
This isn't really related to JWTs at all, but more of a persistence between requests problem. I'm going to close this issue as it isn't related to Flask-JWT-Extended, but to help you on your way here are some common ways of handling data persistence which might be helpful:

* Use a persistent data stores such as a sql server, redis, mongodb, etc to store your data between requests. In this example it might look like storing data in table when the user hits `/configs`, and reading the data from the table and returning the sum when the user hits `/sumcollect`.
* Not using persistence, and if a route needs some data make sure that it is included as part of the http request (in your example, having `/configs` return `a` and `b`, and then sending `a` and `b` into `/sumcollect` to calculate and return the sum.
* Using flask session (not the extension, but part of core flask: https://flask.palletsprojects.com/en/2.0.x/api/#sessions) to save data for a user between requests. Not very common for APIs, but I'm including it here in case you are working with more of a traditional UI driven website.
