### ISSUE TITLE
Better documentation on revoking request tokens

### ISSUE THREAD

**Issue by tgross35** [vimalloc/flask-jwt-extended#453]
Hey all,

I came across #53 which talks about how to revoke a refresh token. It is kind of unclear what exactly this comment references https://github.com/vimalloc/flask-jwt-extended/issues/53#issuecomment-309292786 and revoking refresh tokens isn't mentioned anywhere else. The only place with some documentation is this random site: https://darksun-flask-jwt-extended.readthedocs.io/en/latest/blacklist_and_token_revoking/ which does not appear to be official, or even tell you what version it's talking about, and it doesn't work anyway.

Basically I'd just like a blurb to be added to the refresh token page saying that they can be revoked in the same way as auth tokens as long as `verify_jwt_in_request(refresh=True)` (or the equivalent decorator) is included. It's just too easy to slip a developer's mind that refresh tokens do indeed need to be revoked, to prevent generating a new access token after one was invalidated.

I think there's also a possible implementation of allowing tokens to be tied a session cookie, then invalidating all refresh/access tokens for a specific session via a logout endpoint. But that's complicated above my use case.

**Comment by Jordon-Chen** [comment]
@tgross35 Hi, I want to revoke the refresh token but find no examples. I'm wondering if you can share your examples if you have time. Thanks!!

**Comment by tgross35** [comment]
Hi Jordan,

Guess I never got around to creating a PR lol. Anyway it's easy, same as revoking access but just need to check for refresh instead. In my case, using methodviews and a table called TokenBlocklist, it looks like this:

```python
def delete(self):
    """Block the given Refresh token"""
    verify_jwt_in_request(refresh=True)

    jti = get_jwt()["jti"]
    TokenBlocklist.create(jti=jti)

    return {"message": "Refresh token revoked"}, HTTPStatus.NO_CONTENT
```

which is identical to my regular revoke, except `refresh=True` is added. Hope it helps!

**Comment by Jordon-Chen** [comment]
Hi @tgross35,
Thanks for your blazing fast response. Your example indeed revokes a refresh token. It helps a lot lol !!!
However, I ran into another problem. This delete method does not work for an access token. 
How do you handle this situation, by providing two endpoints to revoke tokens, one for access token and the other for the refresh token ?

**Comment by tgross35** [comment]
@Jordon-Chen you're lucky to have caught me in the midst of a long docker build :)

My current method is like you said: I have /auth/access and /auth/refresh routes that accept POST to generate and DELETE to revoke access and refresh tokens, respectively. 

You could theoretically have one endpoint that does it all using verify_jwt_in_request(optional=True) and checking the headers, but that seemed more effort than it's worth.

**Comment by tgross35** [comment]
@vimalloc I just wrapped up changes for this in #460, take a look when you get a chance

I think this will play nicely with #441. The new argument I added verify_type currently accepts a bool - this could be expanded to accept a string or iterable of a custom type. If you OK #460, I’ll look at bringe #441 in.
