### ISSUE TITLE
Support for flask-admin

### ISSUE THREAD

**Issue by Jordon-Chen** [vimalloc/flask-jwt-extended#455]
Hi,

I'm new to the flask-jwt-extended library. I am wondering that if there are any integration example for the [flask-admin](https://github.com/flask-admin/flask-admin) library?

Thanks for sharing your experiences!!

**Comment by vimalloc** [comment]
I don't see why it wouldn't work according to their docs https://flask-admin.readthedocs.io/en/latest/introduction/#authorization-permissions. 

That said I've never used flask-admin so I'm not gonna be much help in getting that all wired up. Sorry!
