### ISSUE TITLE
Sponsorship does not allow for one time payments

### ISSUE THREAD

**Issue by skamensky** [vimalloc/flask-jwt-extended#459]
When I feel that I'm getting a lot from a github project I sometimes like to throw a few dollars towards the maintainer. I don't like monthly subscriptions. @vimalloc Is there a way you can add an option for one time payments?

Thanks for all the great work!

**Comment by vimalloc** [comment]
Oops, fixed! Thank you so much for considering this, and letting me know that one time payments were not enabled. 🥳
