### ISSUE TITLE
OIDC

### ISSUE THREAD

**Issue by roivant-matts** [vimalloc/flask-jwt-extended#461]
Hello, first, excellent project, I have used in many projects without a hitch.

I have also successfully adapted a former LDAP auth backed to now use OIDC (front-end manages auth and uses jwt based access token). I noticed that routes seem to be protected with the standard toke jwt_required(). I was curious if anyone could elaborate on the purpose of this decorator in the oidc sample.

https://github.com/vimalloc/flask-jwt-extended/blob/master/examples/oidc.py#L61

**Comment by vimalloc** [comment]
That can be removed, it really isn't necessary at all. You can see it's basically the exact same as the default `@jwt_required()` decorator this extension provides: https://github.com/vimalloc/flask-jwt-extended/blob/2c7ae9e81de030f67fb3577be7a74f2a6b7ef5a2/flask_jwt_extended/view_decorators.py#L118

Not sure why it's there to be honest. Maybe a leftover something or other from before the 4.x.x release that didn't get cleaned up?

Cheers!

**Comment by roivant-matts** [comment]
Thanks, appreciate it!
