### ISSUE TITLE
refresh tokens

### ISSUE THREAD

**Issue by yaron-shamul** [vimalloc/flask-jwt-extended#462]
Hi everyone, I’m using flask-jwt-extended and I liked it, my issue is that I can’t see the refreshing token, I can only see the old one, I saw in the doc the piece of code that declare a decorator and after request making a new one but it doesn’t work for me, can anyone give some advice here?
I used [this code](https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens/)  it didnt helped so much

**Comment by vimalloc** [comment]
Can you give me any more specifics for exactly what it is you are doing and what specifically isn't working?

**Comment by yaron-shamul** [comment]
I'm trying to implement the token refreshing as mentioned in the documentation, I can't see any token refreshing..


`
@app.after_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=1))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError):
        # Case where there is not a valid JWT. Just return the original respone
        return response`

**Comment by vimalloc** [comment]
Thank you.

So in this specific case, this decorator will only fire if the JWT is within 1 minute of expiring. If you change the `timedelta(minutes=1)` it will allow the token to be refreshed if it longer away from being expired. Maybe that is your problem?

**Comment by yaron-shamul** [comment]
I changed it to `timedelta(hours=1)` and I still can't see the token in the response.. maybe you have some video of how-to-use for me?

**Comment by yaron-shamul** [comment]
can you please respond with extra data on how to implement the refreshing tokens? where can I see the token that refreshed? can you maybe make a video?

**Comment by vimalloc** [comment]
I will not be making a video. I'm happy to help out as I can, but I maintain this extension on my free time and it does not provide any source of income or anything for me, so there is only so much troubleshooting I can do. In this case, the code in question has been tested to work, so if the token isn't refreshing I suspect it is related to your specific setup. Can you provide a complete, minimal, and verifiable example which shows the behavior you're seeing to troubleshoot this further?

**Comment by yaron-shamul** [comment]
I will be more specific, I can't see the `Access-Control-Expose-Headers` in the response. im useing axios for front part.

**Comment by vimalloc** [comment]
So it sounds like you are running into CORS issues?

This automatic refreshing of JWTs is simply replacing the cookie that has the JWT with a new cookie that has an updated JWT (so basically a `Set-Cookie` header). As I understand it, `Access-Control-Expose-Headers` has nothing to do with setting cookies, and setting `Set-Cookie` in `Access-Control-Expose-Headers` is invalid (https://stackoverflow.com/a/39505535/272689).

It sounds like the issue you want to debug is why is the cookie not being set by the browser even if it comes back in the request? You might want to look at this stackoverflow answer, and make sure that the appropriate headers and configuration options are being set in your requests and responses: https://stackoverflow.com/a/46412839/272689

**Comment by yaron-shamul** [comment]
thank you very much, I think you're right it just took me some time to understand why, I'm on it now and I think the issue is not an issue anymore, thanks again :)

**Comment by vimalloc** [comment]
For sure, glad to hear that helped :)
