### ISSUE TITLE
Help with Axios Post Call.....

### ISSUE THREAD

**Issue by bostonmacosx** [vimalloc/flask-jwt-extended#468]
So all of my routes work fine...however when I use to call an endpoint and return a page from the FLASK end it returns the "login" page like it is not sending an appropriate cookie with the right JWT.. refreshing the whole page 

I have an after_request method which runs but the unauthorized_loader is what gets called and say NOPE you're not sending in a legit JWT to the backend. 

I'm just not sure how to get an AXIOS post and the @JWT_REQUIRED to work together...

any help appreciated.

```
var myFunction = function(element){
        console.log(element.innerText);
	axios.defaults.withCredentials = true;
	axios.post('/api/cmsaudit/'+element.innerText,{},{
		withCredentials:true
	}).then(function(response){
		//console.log(response.data);
		document.getElementById('resultcol').innerHTML = response.data;
	}).catch(function(error){
	})
}
```

**Comment by vimalloc** [comment]
I don't have any specific Axios knowledge to give you, but it should be basically the same thing as a standard javascript fetch call. You might want to check out https://flask-jwt-extended.readthedocs.io/en/stable/token_locations/. It has working examples of using javascript to make API requets in various different configuration (cookies, headers, etc) and should help point you in the right direction.
