### ISSUE TITLE
Missing Exception when upgrading from v3 to v4. 

### ISSUE THREAD

**Issue by julianjurai** [vimalloc/flask-jwt-extended#471]
Could we update the migration guide to include the exception name change:
https://github.com/vimalloc/flask-jwt-extended/blob/master/docs/v4_upgrade_guide.rst

Version 3.x.x uses `UserLoadError`  while version 4.x.x uses `UserLookupError`. This is a **breaking change**.

Version 3.x.x uses `UserLoadError` 
https://github.com/vimalloc/flask-jwt-extended/blob/12ead38f49580539c4be9f096326b793979f6507/flask_jwt_extended/exceptions.py#L59-L64

Version 4.x.x uses `UserLookupError`

https://github.com/vimalloc/flask-jwt-extended/blob/d13dd8dd7d8e0ee9f08cf3b08e0b11ef72422701/flask_jwt_extended/exceptions.py#L73-L78

Suggestion: 
```

API Changes
~~~~~~~~~~~

- Removed ``UserLoadError`` from ``flask_jwt_extended.exceptions`` . Use ``UserLookupError`` instead.
```

**Comment by vimalloc** [comment]
Seems very reasonable, I'll get that in and a new released pushed out sometime in the next couple weeks.
