### ISSUE TITLE
make `current_user` available in jinja templates

### ISSUE THREAD

**Issue by lkiran5080** [vimalloc/flask-jwt-extended#478]
Can jinja templates get `current_user` variable access without passing it explicitly? Like `Flask-Login` does, its quite convinient

**Comment by vimalloc** [comment]
Seems totally reasonable to me! I'll look into seeing what that entails when I have some time!

**Comment by vimalloc** [comment]
I added a configuration option to allow this. I did not turn it on by default because it's conceivable it would be a breaking change. Once I get another release pushed out you can turn it on like this:

```python
JWTManager(app, add_context_processor=True)
```

or

```python
jwt.init_app(app, add_context_processor=True)
```

Cheers!
