### ISSUE TITLE
inquiry regarding the `refreshing` of tokens

### ISSUE THREAD

**Issue by paulsoh** [vimalloc/flask-jwt-extended#48]
Hi there,

I am glad I encountered this open source, it has met all my basic needs in `protecting` my backend endpoints. Thanks to all the examples in the documentation!

I have a question though, I don't know if this is because I don't have enough knowledge on JWTokens but I am curious on how the exp field works.

Lets say a user logged in and got issued a jwt that expires in 3 seconds.
If the user tries to access the endpoint after 3 seconds has past, it is considered an old token and the user is required to log in again. This part I understand.

What happens if the user makes consequent requests within the 3 seconds. Does the exp field get updated automatically? If not, does the client have to take care of the `refreshing` of the token implicitly?

Thanks once again for the great open source!

**Comment by vimalloc** [comment]
Thanks for the feedback! Glad this is working out for you 👍 

Per your question, the exp field is not automatically updated. There are a few reasons why this is the case. First, there is no way to update a JWT. The contents of the JWT (including the exp field) are all cryptographically signed based on the contents in the token. So if one field is changed in the JWT, the signed portion of the token would have to be updated as well, and you in essence end up with a whole new token.

Now, the reason this extension doesn't automatically send back new tokens is two fold. First, if the backend automatically refreshed a token whenever it was expired, that would mean that the frontend would need to be able to handle receiving a new token on any call to our API, regardless of if the call succeeded or failed. That is something that could be done, but it would require extra knowledge by users of our API, and if someone wasn't aware of this they could just keep using the same expired token forever (as the backend would keep creating new tokens for them), and a bunch of unused tokens would just be floating around. Not ideal. This would also limit what the API could return (it would always have to return a dict at the top level for example, as how could you return the new token to the caller if you were returning only a list?).

Second, if an access token was ever leaked, the person who acquires it would be able to keep generating new tokens and in essence stay logged in forever. As the access tokens are sent with every request, there is (at least in theory) more surface area where they could be leaked. If a refresh token is leaked, obviously we are in the same situation (except for the fact that refresh tokens also have an expires time on them, so eventually it will run out as well, but that may be a long time in the future). However, the refresh tokens should only be sent over the wire when requesting a new access token, so there should be less chance of them getting compromised.

So how can we use these refresh tokens on our frontend? In general there are two ways to go about this. The first way would be to set a timer to go off sometime before the access token expired (if the token expires after 5 minutes, maybe set a timer for 4 minutes) and once the timer hits 0 preemptively ask for a new access token using the refresh token. This has the benefit of being very simple, but has the drawbacks of potential breakage if your page is reload (assuming website frontend) and has some overlap where multiple tokens are floating around. The second way would be to use your access tokens as normal, and on every request check if you get an error back indicating that the token is expired. If you are doing a request and get an expired token error, fire off a request to refresh the access token, then re-make the original request (that had the expired token) using the newly received access token. This has the benefits of always working and only generating new tokens as needed, with the drawback of added complexity in your frontend code.

Phew! That was a wall of text. Hopefully this all makes sense and answers your question. If you want clarifications on any part or have any follow up questions, don't hesitate to let me know.

Cheers!
