### ISSUE TITLE
Refresh with cookies 

### ISSUE THREAD

**Issue by leelerm** [vimalloc/flask-jwt-extended#481]
I have a pretty standard refresh endpoint with the intent to create a new access token and set the new access token as a cookie.
```python
@identity_bp.get('/refresh')
@jwt_required(refresh=True)
def refresh_token():
    identity = get_jwt_identity()
    access_token = create_access_token(identity=identity)

    res = jsonify({'refresh': True})
    set_access_cookies(res, access_token)

    return jsonify(access_token=access_token), HTTPStatus.OK
```
A new access token is created, but the access token cookie remains the same as the access token set upon login. So, despite refreshing, the token stored in the cookie is old. 

For reference, this is our login endpoint, which does successfully create access/refresh tokens and stores them into cookies:
```python
@identity.post('/login')
def login():
    email = request.json.get('email', None)
    password = request.json.get('password', None)

    # ... some logic

    access_token = create_access_token(identity=identity)
    refresh_token = create_refresh_token(identity=identity)

    res = jsonify({'msg': 'Successful login.',
                   'access_token': access_token,
                   'refresh_token': refresh_token})

    set_access_cookies(res, access_token)
    set_refresh_cookies(res, refresh_token)

    return res, HTTPStatus.OK
```

In our React web app, we handle the logic necessary logic to refresh the tokens. I can confirm that when we hit the refresh endpoint there, a new token is created, but the cookie just doesn't change. I've also tried to unset the cookies with `unset_access_cookies`, but it also doesn't remove the cookie.

Perhaps this is just a misunderstanding on my end with how overriding the cookie works, or a bug. I'm not too sure.

**Comment by vimalloc** [comment]
This is your probems:

```python
    res = jsonify({'refresh': True})
    set_access_cookies(res, access_token)
    return jsonify(access_token=access_token), HTTPStatus.OK
```

You are creating a response, setting the access cookie on that response, then throwing it away and returning an entirely different response. What you probably want is something like this:

```python
    res = jsonify(refresh=True, access_token=access_token)
    set_access_cookies(res, access_token)
    return res, HTTPStatus.OK
```

**Comment by leelerm** [comment]
@vimalloc That makes a lot more sense now, thank you!
