### ISSUE TITLE
Flask 2.2.0 `json_encoder` and `json_decoder` are deprecated

### ISSUE THREAD

**Issue by Sir-MaNiAl** [vimalloc/flask-jwt-extended#492]
Since Flask 2.2.0 json_encoder and json_decoder properties on `app` are deprecated and was set to `None` by default ([Flask changelog](https://flask.palletsprojects.com/en/2.2.x/changes/#version-2-2-0))  
`JWTManager._encode_jwt_from_config` method relies on it. It now raises errors on datetime, UUID, etc. values serialisation.

**Comment by vimalloc** [comment]
Thank you for the heads up, looks like there are a few things I need to update for this newest flask release. I will try to get everything updated in the next day or two here!

**Comment by jrast** [comment]
Looking into this and it seems not as easy to switch to the new concept used by flask regarding json:

- with `app.json_provider_class` flask allows now to switch out the complete stdlib json module for another implementation
- PyJWT does use the stdlib json module and only allows a change of the JSON Encoder

PS: It seems like the case @Sir-MaNiAl mentions where encoding fails is not covered by any tests.

**Comment by jrast** [comment]
In a first step (Commig https://github.com/vimalloc/flask-jwt-extended/pull/493/commits/4f18acae751806ac7ceb306a06517f382ce1b6df) I just reused to old Flask JSONEncoder class and use this as default. However, this will break of someone uses a custom JSON Encoder.

**Comment by vimalloc** [comment]
Fix released in version `4.4.4`. Cheers!
