### ISSUE TITLE
Old Access token still working

### ISSUE THREAD

**Issue by BloverseUkeme** [vimalloc/flask-jwt-extended#496]
Hello.

I created an access token with **_create_access_token(identity=handle, fresh=True)_**.
Then I copy the access token without using it.

If I created another access token for the same user and I try to use it with **_@jwt_required(fresh=True)_**

I find out that both access tokens (the one I first created without using and the second one) are able to work with the @jwt_required(fresh=True).

Question: How do I prevent the first(older) access token from working when I create a new one for a user

**Comment by vimalloc** [comment]
As you discovered, fresh tokens are a totally different design pattern. To achieve what you are asking, you would need to use token revoking to add the original token to a blocklist when the new token was created. The documentation around token block listing can be seen here: https://flask-jwt-extended.readthedocs.io/en/stable/blocklist_and_token_revoking/

**Comment by BloverseUkeme** [comment]
Okay. Great. Thank you
