### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by eMaerthin** [vimalloc/flask-jwt-extended#509]
Hi,
I can see that there is a little inconsistency on `typing` of the `expires_delta` argument in `create_access_token`. In [utils](https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py#L133) it is `Optional[datetime.timedelta]` while as per [jwt_manager](https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/jwt_manager.py#L497) and as mentioned in docstrings its type should be rather `Optional[ExpiresDelta]`.

I can prepare a quick fix if you like.

**Comment by vimalloc** [comment]
That would be great, thanks!
