### ISSUE TITLE
How does the CSRF functionality work?

### ISSUE THREAD

**Issue by flixman** [vimalloc/flask-jwt-extended#529]
I am moving away from WTF, and also moving into JWT at the same time. Until now, before a POST / PUT / PATCH / DELETE were issued I would request a csrf token and then add it as a header to my request. I have seen in the documentation that in flask-jwt-extended the token is provided simultaneously by an httpOnly,secure cookie, and as a header to the request. However, this raises some questions:

a) As the CSRF token is encoded within the access/refresh tokens, are we supposed to reuse these tokens until they expire? I assume the underlying reason is that the access tokens are supposed to be short lived?

b) I have read in the documentation that the csrf token is only provided if the JWT is stored in cookies. How can it be used on a scenario based on header authentication? Or this case is considered to be a corner case because an app will usually have its data store isolated from other apps, and therefore is very unlikely?

Thank you!

**Comment by vimalloc** [comment]
> a) As the CSRF token is encoded within the access/refresh tokens, are we supposed to reuse these tokens until they expire? I assume the underlying reason is that the access tokens are supposed to be short lived?

This really depends on the needs of your application. There are two main approaches that I've seen, one is to use a token until it expires then either refresh it or force the user to log in again, and the other is to implicitly refresh a token when it is approaching its expiration time. But regardless, as long as you aren't leaking your access tokens, it should be safe to keep the CSRF double submit token stored in the JWT. 

> b) I have read in the documentation that the csrf token is only provided if the JWT is stored in cookies. How can it be used on a scenario based on header authentication? Or this case is considered to be a corner case because an app will usually have its data store isolated from other apps, and therefore is very unlikely?

That's correct. If you are storing the jwt in something like local storage and using JavaScript to attach it as a header, it shouldn't be vulnerable to CSRF attacks in the first place.

Did these answer all your questions?

**Comment by flixman** [comment]
Yes! thank you very much for taking the time to answer them: I appreciate that. Have a nice weekend!
