### ISSUE TITLE
RS512 not supported

### ISSUE THREAD

**Issue by IDidPython** [vimalloc/flask-jwt-extended#533]
When I set 
`app.config['JWT_ALGORITHM'] = 'RS512'`
And then try to request to an endpoint with a RS512 token I get in return
`{"msg":"Algorithm not supported"}`

How to solve this?

**Comment by vimalloc** [comment]
You need to include the optional `cryptography` dependency to use RSA.

```
pip install flask-jwt-extended[asymmetric_crypto]
```

See these for details: 

https://flask-jwt-extended.readthedocs.io/en/stable/installation.html

https://pyjwt.readthedocs.io/en/stable/usage.html#encoding-decoding-tokens-with-rs256-rsa
