### ISSUE TITLE
Is option JWT_REFRESH_TOKEN_EXPIRES working?

### ISSUE THREAD

**Issue by kwagdy** [vimalloc/flask-jwt-extended#534]
Hello, I am trying to set the refresh token cookies expiration time by setting the option, but is keeps being set to a year ahead!
`app.config['JWT_REFRESH_TOKEN_EXPIRES'] = datetime.timedelta(hours=12)`
`jwt = JWTManager(app) `
![image](https://github.com/vimalloc/flask-jwt-extended/assets/15840617/34022696-1828-4481-bfe2-e162e3081681)

**Comment by vimalloc** [comment]
That option sets the `exp` data in the JWT itself. If you want to set the `max_age` on a cookie, you should either use the `max_age` option on the `set_access_cookies` and `set_refresh_cookies` API calls.

**Comment by vimalloc** [comment]
You are welcome! Glad it’s helping 😊
