### ISSUE TITLE
Documentation examples for double submit removed from latest documentation.

### ISSUE THREAD

**Issue by bostonareahuman** [vimalloc/flask-jwt-extended#537]
I was looking on how to secure the JWT using double submit however the code examples which once existed are now gone from the page.

any way to restore an example of this technique..

**Comment by vimalloc** [comment]
They still exist: https://flask-jwt-extended.readthedocs.io/en/stable/token_locations.html#cookies

**Comment by bostonareahuman** [comment]
The javascript does but not the overall FLASK that will initiate the cookies and how they should be implemented...older versions of the docs had this.

**Comment by vimalloc** [comment]
It's at the very top of the same page. https://flask-jwt-extended.readthedocs.io/en/stable/token_locations.html

**Comment by bostonareahuman** [comment]
The top code doesn't contain the CSRF of the whole example put together...it just contains the access cookie.. I'm spitting hairs but previous version had a full examples of double submission JWT.... it would be helpful...

**Comment by vimalloc** [comment]
That is all the code… you don’t need to do anything to prevent csrf attacks other then what is in that example. 

By default, csrf protection is enabled when storing your jwts in cookies. The `set_access_cookie` call will set both the jwt in an httponly cookies, as well as the double submit token in a non httponly cookie
