### ISSUE TITLE
flask-restless integration

### ISSUE THREAD

**Issue by ludusrusso** [vimalloc/flask-jwt-extended#54]
Is there an easy way to integrate this package with [flask-restless](https://github.com/jfinkels/flask-restless)?

**Comment by vimalloc** [comment]
I have never used flask restless before, so I couldn't say for sure, but I imagine there is a way to hook decorators or some such up with that extension. Assuming that's the case, there is no reason why these two extensions shouldn't be able to play nicely together.

Have you tried using these together? Have you ran into any specific issues?

**Comment by vimalloc** [comment]
Looking at [this](https://flask-restless.readthedocs.io/en/stable/customizing.html#requiring-authentication-for-some-methods) and [this](https://stackoverflow.com/questions/24186694/combining-flask-restless-flask-security-and-regular-python-requests) it looks like it shouldn't be too hard. I haven't tested this, but it looks like it should be something like this:

```python
@jwt_required
def auth_func(*args, **kwargs):
    return True

thing.create_api(..., preprocessors=dict(GET_SINGLE=[auth_func], GET_MANY=[auth_func]), ...)
```

You should read the first link and make sure you properly understand what is happening and that all of your endpoints that you want protected are actually protected. As I mentioned, I haven't used flask-restless before, so take what I say with a grain of salt :wink:

**Comment by ludusrusso** [comment]
@vimalloc thanks! I've also found out [flask-potion](https://github.com/biosustain/potion) that seems better then flask-restless! You can close the issue!

**Comment by vimalloc** [comment]
Will do. Let me know if you run into any issues with this :+1:
