### ISSUE TITLE
DeprecationWarning: The '__version__' attribute is deprecated and will be removed in Flask 3.1

### ISSUE THREAD

**Issue by yctomwang** [vimalloc/flask-jwt-extended#542]
Hi @vimalloc, thank you for such an awesome libarary! I have downloaded the code to playaround with it, however when i run pytest on the unit tests its showing a Deprecation warning. I will propose a quick PR to fix this if you dont mind! Thank you once again!
================================================================================ warnings summary =================================================================================
tests/test_config.py:7
tests/test_config.py:7
  /Users/yuanchenwang/Desktop/flask-jwt-extended/tests/test_config.py:7: DeprecationWarning: The '__version__' attribute is deprecated and will be removed in Flask 3.1. Use feature detection or 'importlib.metadata.version("flask")' instead.
    from flask import __version__ as flask_version

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

![image](https://github.com/vimalloc/flask-jwt-extended/assets/69774548/a7ae0954-f339-4136-a29f-9396fb007bf8)

**Comment by vimalloc** [comment]
Thanks for the report and the fix!
