### ISSUE TITLE
Flask v3 Error Registering Blueprints with Routes Using @jwt_required

### ISSUE THREAD

**Issue by cellaphin** [vimalloc/flask-jwt-extended#552]
Hello! I'm a newbie to all things python and apologize in advance if this post is user error.

I've recently updated my flask app from v1 to v3.  When using blueprints with the @jwt_required decorator, I receive an error when trying to register my blueprint. The error I receive is:

`AssertionError: View function mapping is overwriting an existing endpoint function: myBlueprint.wrapper`

In essence, this occurs with the following setup:

```
myBlueprint = Blueprint("myBlueprint", __name__)

@myBlueprint.route("/", methods=["GET"])
@jwt_required
def MyEndpoint():
    print("Entering MyEndpoint")

#...

app.register_blueprint(myBlueprint) # <-- AssertionError thrown here
```

My initial thought about this is that there is a name conflict with the jwt_required.wrapper function and the flask app.register_blueprint trail. If it's truly that, and not me doing something wrong, I'd be happy to try and make a pull request to change the name of it.

Thanks for your time!

**Edit:** fixed typo and put the code example in a fenced code block

**Comment by vimalloc** [comment]
I suspect you upgrade `flask_jwt_extended` to version 4. In this version, `@jwt_required` has been changed to `@jwt_required()`, which I think is causing the issue you're seeing.

There are a few other breaking changes to be aware of in version 4, I would suggest reading over the breaking change documentation here: https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide.html

Let me know if that resolves the issue!

**Comment by cellaphin** [comment]
Hi Vimalloc,

Thanks for the reply! And sorry for not including that bit of information. Yes, as part of the upgrade to flaks v3, I updated flask-jwt-extended to v4.6.0.  Among some of the other updates that occured, I bet I missed this one. 

While I expect your suggestion to be the solution, I'll verify that tonight.

**Comment by cellaphin** [comment]
That was it! I'll read through the docs more thoroughly if I run into any other issues.

Thank you for your help!
