### ISSUE TITLE
Error: Subject must be a string!

### ISSUE THREAD

**Issue by kwagdy** [vimalloc/flask-jwt-extended#557]
We have been using **flask-jwt-extended** to manage JWT tokens for a few months now, we made a quick recent update to a separate part of our code, unrelated to the JWT. However, we started seeing this error `Subject must be a string` during login phase (_and token management_), which is fired by the function declared under `invalid_token_loader`  that fires when an invalid JWT is encountered. The error refers to the line `set_access_cookies(identity=u_token)` in the following code section:

```
resp = make_response(redirect(url_for("home")))
u_token={}
u_token['user_id']=user.id
u_token['role]=user.role
u_token['c_id]=cAuto.id
access_token = create_access_token(identity=u_token)
refresh_token = create_refresh_token(identity=u_token)

set_access_cookies(resp, access_token, max_age=60*60*24) # <--- Error fires here!
set_refresh_cookies(resp, access_token, max_age=60*60*24*7)
```
It seems that it expects a string. When we change the passed parameter momentarily to a string, the line passes without error. However, as per the [docs](https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.create_access_token), it's ok to add any JSON serializable data to `identity`:

> **create_access_token - identity**: The identity of this token. It can be any data that is json serializable. You can use [user_identity_loader()](https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.user_identity_loader) to define a callback function to convert any object passed in into a json serializable format.

Although we haven't changed any part of the code related to JWT. And the fact that it has been running all the past months without issues. This made our primary suspicion to be one of the dependencies that we might have failed to set a specific version for, in case it was updated recently causing the issue, but it seems we already have the versions in for the JWT related libraries, at least to our knowledge.

This might be a shot in the dark, but we don't see that this might be caused by other libraries at this point, appreciate your help!

For reference here is our requirements.txt:
```
appengine-python-standard
Flask==2.1.3
gunicorn
passlib
Jinja2
Flask-JWT-Extended==4.3.0
Werkzeug==2.0.0
requests
python-dateutil
google-cloud-logging
google-cloud-datastore
google-cloud-storage
google-cloud-core
iso8601
firebase_admin
reportlab
arabic_reshaper
python-bidi
```

**Comment by nathanganser** [comment]
Same issue for us, pretty critical. Still investigating what's going on. 

https://pypi.org/project/Flask/#history Flask updated some code recently, might be related to that. still investigating..

**Comment by manisandro** [comment]
This is due to the just released pyjwt-2.10.0 [1] which adds the sub claim validation [2]. According to the spec [3]

    The "sub" value is a case-sensitive string containing a StringOrURI value

so the validation is correct. So either the flask-jwt-extended documentation should be fixed, or `JWT_IDENTITY_CLAIM` should default to something else than `sub`, or `create_access_token` and ` get_jwt_identity` should internally json-serialize/deserialize.

- [1] https://github.com/jpadilla/pyjwt/releases/tag/2.10.0
- [2] https://github.com/jpadilla/pyjwt/pull/1005
- [3] https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2

**Comment by nathanganser** [comment]
So quickfix is to add
`PyJWT==2.9.0`
at the top of your `requirements.txt` file

**Comment by vimalloc** [comment]
4.7.0 has been published, which now documents that `identity` must either a string, or you must use the [user_identity_loader](https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.user_identity_loader) to convert your object a string.

If you have issues making this change in your applications for whatever reason feel free to let me know. I think it will hopefully be pretty straightforward, but if you run into any unexpected complexities I would be happy to try and help resolve them with you.

Cheers!

**Comment by kwagdy** [comment]
Oh wow you guys are quite active! appreciate the quick turn around!
We started to convert the `identity ` to string, and we will later move the other claims to `additional_claims ` parameter.
Thank you!
