### ISSUE TITLE
Use blacklist with custom store

### ISSUE THREAD

**Issue by zerbusdetroy** [vimalloc/flask-jwt-extended#58]
Hi,

Thanks for this very helpful API.
I would like to use my own database to store the tokens and a service to access it. Simplekv breaks this architecture.
Is it possible to allow to plug a custom object rather than force us to use a simplekv.KeyValueStore ?

**Comment by vimalloc** [comment]
I was thinking about that myself, as it would also have the benefit of allowing you to properly mutex your keys and address #25, and generally giving you more control over the blacklist.

It would be a pretty big breaking change so I want to give it a bit more thought, but my initial thoughts are that it seems reasonable to me. I'll need to find time to work on it though, unless you want to submit a PR.

**Comment by zerbusdetroy** [comment]
OK, I will think about that but I don't have much time available these days either. For my case I finally used a workaround creating a custom implementation of simplekv. 
I have not yet tried to improve the performance of the function get_stored_tokens but if necessary I can use my workaround to duplicate the identity to an other field and do my own get_stored_tokens why nice performances.

However it is a very dirty solution, I may submit a PR so that we can do it properly if I find some time to do it.

**Comment by vimalloc** [comment]
No worries. If you do end up finding time time and want to hack at it I would happily accept a PR, but assuming you don't I'll try to find some time in the next few weeks to properly work through this and see if I can get something ready.

If you don't mind, I'll hit you up when I have the basics in place to make sure it would address your use case.

Cheers.

**Comment by vimalloc** [comment]
I started working on this in on the blacklist_v2 branch. It still has more work to go, but basicallywhat I'm thinking is the user has to define a function that says if a token is revoked or not (if blacklist is enabled), that we check in the `@jwt_required` calls. The user is responsible for inserting tokens into their blacklist of choice, however they so choose.

I think this will give everyone enough flexability to basically do whatever they want. Does this sound good to you?

**Comment by zerbusdetroy** [comment]
Yes of course, with :)

**Comment by vimalloc** [comment]
Version 3.0.0 was just released, which provides support for this. 

Check out these for details, and let me know if you run into any issues
* http://flask-jwt-extended.readthedocs.io/en/latest/blacklist_and_token_revoking.html
* https://github.com/vimalloc/flask-jwt-extended/releases/tag/3.0.0
