### ISSUE TITLE
Follow-up CSRF question

### ISSUE THREAD

**Issue by wittlesouth** [vimalloc/flask-jwt-extended#60]
I'm trying to understand how CSRF works when you follow the example in csrf_protection_with_cookies. I read the documentation you linked to an earlier CSRF question:

http://www.redotheweb.com/2015/11/09/api-security.html

That document says that CSRF protection happens because you're adding an additional token **to the request body**. Specifically, it says a server "should expect both a session cookie header, and a token in the response body.", and the example has the token in the JSON payload of a post.

In your csrf_protection_with_cookies example, I understand that the access_token is HTTP only, and the crsf_access_token is not, but if they're both sent with any request by the browser to the server as cookies, I'm not sure how CSRF protection is achieved?

I note that you also have examples of not sending the CSRF token as a cookie, but that certainly takes a bit more effort for the app developer. If the CSRF token as a cookie is effective, that would make my life easier, but I'm not sure how that could be the case.

To be more specific on why I'm confused, I've set up flask_jwt_extended following the example in crsf_protection_with_cookies. To test it, I'm trying an integration test that calls the server using the python requests library roughly as follows:

- Setting up a requests session object: `s = requests.session()`
- Calling the /login endpoint with a post to the session: `resp = s.post('/login', <login json>)`
- Calling a get method that is marked as protected with @jwt_required using the same session with get: `resp = s.get('/users')`. I would expect this get to fail unless I'd set the CSRF token in the 'X-CSRF-TOKEN' header as described in the comment in csrf_protection_with_cookies, but the request succeeds without any custom header set by me in the test code.

If a plain requests.get call works with @jwt_extended in this case, I must be missing how the CRSF protection works somehow. Shouldn't the request fail authentication because the X-CSRF-TOKEN header was not explicitly set in the get call?

**Comment by vimalloc** [comment]
Your understanding of the csrf protection seems to be correct. The csrf protection is achieved by the csrf token in your jwt (stored as httponly) must match the X-CSRF-HEADER you pass in as well. The reason your example is working is by default this extension only applies csrf protection to http methods that are by convention supposed to change state (post, put, patch, delete). You can change this with the ```JWT_CSRF_METHODS``` config option to include get requests as well, although if you aren't doing any state modifications in a get request it strictly speaking shouldn't be required (but obviously wouldn't hit anything to have there).

**Comment by wittlesouth** [comment]
Thanks for the prompt follow-up, that explains what I'm seeing, and the configuration setting you pointed me to works as expected!

**Comment by walshbm15** [comment]
Hi, I know this is closed now but I am curious why a `GET` request is not included in `JWT_CSRF_METHODS` by default? Even if there is no state modification done with a `GET` request you could still gain access to the data returned back in the response that otherwise you would not be authorized to view if the `X-CSRF-HEADER` was not set. 

In that case, is it just more of a standard convention to always use `POST` when accessing any data that should be protected?

**Comment by vimalloc** [comment]
@walshbm15 check this out for a good explanation: https://security.stackexchange.com/a/115810
