### ISSUE TITLE
Typo: JWT_LOCATION_LOCATION

### ISSUE THREAD

**Issue by slintak** [vimalloc/flask-jwt-extended#68]
There is a typo in file `flask_jwt_extended/config.py` at line 48:

    if location not in ('headers', 'cookies'):
        raise RuntimeError('JWT_LOCATION_LOCATION can only contain '
                           '"headers" and/or "cookies"')

I beleive it should be `JWT_TOKEN_LOCATION` and not a `JWT_LOCATION_LOCATION`.

https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/config.py#L48

**Comment by vimalloc** [comment]
Good catch. Thanks! 👍
