### ISSUE TITLE
Error 500 on Basic Usage sample 

### ISSUE THREAD

**Issue by reiven** [vimalloc/flask-jwt-extended#74]
Hi!

I'm just testing the Basic Usage sample and doing a POST to /login without parameters is giving 500 internal server error

```python
    username = request.json.get('username', None)
AttributeError: 'NoneType' object has no attribute 'get'
```
The request should be checked with
```python
if request.is_json:
```

**Comment by vimalloc** [comment]
Fair enough. Another thing that should be updated there is `request.get_json()` instead of `request.json` (http://flask.pocoo.org/docs/0.12/api/#flask.Request.get_json).

Do you want to make a pull request to update these?

**Comment by reiven** [comment]
Sure
