### ISSUE TITLE
"Missing cookie "access_token_cookie""

### ISSUE THREAD

**Issue by Rajawat23** [vimalloc/flask-jwt-extended#76]
When app.config['JWT_TOKEN_LOCATION'] = ['cookies'] is set and to access @jwt_required you try passing the access_token in cookie the error is thrown

**Comment by vimalloc** [comment]
That means that the cookie named `access_token_cookie` was not present in the request. How are you creating the JWTs and passing them to the frontend? Are you remembering to use the ```set_access_cookies(resp, access_token)``` function to actually set the cookies when a user logs in?

**Comment by Rajawat23** [comment]
For the example mentioned in the documentation I modified the script a bit 
`app.config['JWT_TOKEN_LOCATION'] = ['cookies']`

and login function as 

```
@app.route('/token/auth', methods=['POST'])
def login():
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    if username != 'test' or password != 'test':
        return jsonify({'login': False}), 401
    access_token = create_access_token(identity=username)
    refresh_token = create_refresh_token(identity=username)
    resp = jsonify({'login': True})
    set_access_cookies(resp, access_token)
    set_refresh_cookies(resp, refresh_token)
    resp = jsonify({'access_token':access_token,'refesh_token':refresh_token})
    return resp, 200
```
and when I'm trying to call 

```
@app.route('/api/example', methods=['GET'])
@jwt_required
def protected():
	username = get_jwt_identity()
	return jsonify({'hello': 'from {}'.format(username)}), 200

```

with a get localhost:5000/api/example  where headers are like 
```
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmIjoiNGUzMzRmMTktM2FjNC00NjNhLThlNzYtNTdkNGRlMTlmOWFiIiwianRpIjoiNThiNWNjZWEtYTlmYi00ZjkwLTk2MjktZmE5YjgzMjMyN2RkIiwiZXhwIjoxNTAxNzU2MzQ1LCJmcmVzaCI6ZmFsc2UsImlhdCI6MTUwMTc1NTQ0NSwidHlwZSI6ImFjY2VzcyIsIm5iZiI6MTUwMTc1NTQ0NSwiaWRlbnRpdHkiOiJ0ZXN0In0.GoDlznmAtFJsPcIH-MPYeTuS0DzmfM5xAmNzZ9DNlss
```

the error 
`"msg": "Missing cookie "access_token_cookie""` is returned by the server.
the cookie is the jwt/token returned by login

**Comment by vimalloc** [comment]
The response object is the thing that is returned to the client and tells it to set the cookies. You are creating two separate response objects and not returning the one that does the setting of the cookies:

```python
    resp = jsonify({'login': True})
    set_access_cookies(resp, access_token)
    set_refresh_cookies(resp, refresh_token)
    resp = jsonify({'access_token':access_token,'refesh_token':refresh_token})
    return resp, 200
```

You should probably get rid of that second response object (you generally don't need to include your tokens in both the cookies and JSON data, but I don't know your application, maybe you have a valid use case for that). Alternately you can combine it with the first one like so.

```python
    resp = jsonify({
        'login': True,
        'access_token': access_token, 
        'refesh_token': refresh_token
    })
```

If you want to change the name of the that contains the access token, you can do that with ```app.config['JWT_ACCESS_COOKIE_NAME'] = 'access_token'```. 

Finally, if you are going to be using cookies, make sure to read up on how to prevent yourself from being vulnerable to CSRF attacks here: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

Cheers.

**Comment by Rajawat23** [comment]
Oh Perfect thanks
