### ISSUE TITLE
Configuration setting for authentication url?

### ISSUE THREAD

**Issue by rlam3** [vimalloc/flask-jwt-extended#8]
Going off the Flask-JWT library. Should/would it be a good idea to have an auth url rule?

**Comment by rlam3** [comment]
Auth handler / identity handler similar to flask jwt? https://pythonhosted.org/Flask-JWT/

**Comment by vimalloc** [comment]
I don't want to go that route. It locks people into one way of doing things, which has caused a number of issues in Flask-JWT. Here is a list of just the open ones:

* https://github.com/mattupstate/flask-jwt/issues/67
* https://github.com/mattupstate/flask-jwt/issues/77
* https://github.com/mattupstate/flask-jwt/issues/80
* https://github.com/mattupstate/flask-jwt/issues/91
* https://github.com/mattupstate/flask-jwt/issues/96

All of these could be addressed via adding/changing callbacks and configuration options, but by supplying **create_access_token()** and **create_refresh_token()** we don't need to worry about any of that. Anyone can create and return a JWT in any way that is required for their application, without having to worry about one specific way of doing things.

**Comment by rlam3** [comment]
@vimalloc Thanks!
