### ISSUE TITLE
Travis CI broken - Drop support for python 3.3

### ISSUE THREAD

**Issue by vimalloc** [vimalloc/flask-jwt-extended#89]
The underlying cryptography package used by pyjwt dropped support for python 3.3 in version 2.0 (https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#20---2017-07-17). This is causing travis to fail on python 3.3.

PyJWT looks like it will officially drop support for python 3.3 here as well: https://github.com/jpadilla/pyjwt/issues/297. We should follow suit and remove python 3.3 from the classifiers, travis, and tox.

**Comment by hugovk** [comment]
Here's the pip installs for flask-jwt-extended from PyPI for the last month:
```
$ pypinfo --percent --pip flask-jwt-extended pyversion
python_version percent download_count
-------------- ------- --------------
2.7              48.4%          4,667
3.6              28.1%          2,705
3.5              20.7%          1,992
3.4               2.8%            266
3.7               0.1%              8
3.3               0.0%              3

```

**Comment by vimalloc** [comment]
dropped in 3.3.3
