### ISSUE TITLE
Refresh token should provide a new refresh token as well?

### ISSUE THREAD

**Issue by rlam3** [vimalloc/flask-jwt-extended#9]
Best practice question..

Should we create a new refresh token as well and return it back to the end user when we refresh a jwt token? This way the client will have a new refresh_token with a new_access token... if the session expires and access_token cannot be used, they can use the new refresh token to get another token instead of using the stale refresh token....

**Comment by vimalloc** [comment]
You totally could, and there wouldn't be anything technically wrong with that, but I think that might not be the best idea, as you would then have multiple refresh tokens that are all still valid laying around.

For example, if you have the refresh tokens set to live for 7 days, and the access tokens set to live for 15 minutes, you may end up generating several new access and refresh tokens depending on how long the user is browsing your site. Every refresh token created still has the ability to create new access tokens for this user, which could in theory increase the chance of one of them being compromised.

For the sake of simplicity, I think it might be best to generate a single refresh token with a long expires time, and use that one repeatedly to generate new access tokens as they expire. But if you are worried about it, you could generate a new refresh token every time that you generate an access token, and then blacklist the just used refresh token to prevent it from being used again. I would need to add a method call for that, but it would be very simple to do (could have it done tomorrow). 

One potential downside to this is that if the call to refresh a token was interrupted part way through for any reason, the user would be stuck with an expired access token and revoked refresh token, and would be forced to sign in again. There may also be concerns with race conditions, where your front end fires off two asynchronous AJAX requests to refresh an access token at the same time. If the first request gets there first and revokes the refresh token, the second request could fail in a way that the front end wasn't expecting. You could absolutely make this work but it might take some addition consideration to get right, and I'm not sure if you would get significant security benefits by doing it.

**Comment by rlam3** [comment]
@vimalloc Thank you so much! Another question I have is, if we use refresh token to get another access token... does the older access token get revoked without the implementation of a persistent database?

**Comment by vimalloc** [comment]
Anytime! Keep the questions coming, I'm happy to help :)

The only way to revoke a token is to use some sort of storage to save what tokens have been revoked, that's just the way JWTs are. We provide access to do that with [this library](http://flask-jwt-extended.readthedocs.io/en/latest/blacklist_and_token_revoking.html). You can use a variety of [storage engines] (http://pythonhosted.org/simplekv/#table-of-contents) for storing the tokens.

That said, if you are using a refresh token, chances are your access token is expired, and an expired token cannot be used anymore, so revoking it at that point in time is a moot point anyways.
