### ISSUE TITLE
Should we include CSRF when we use flask-jwt-extended?

### ISSUE THREAD

**Issue by rlam3** [vimalloc/flask-jwt-extended#94]
Because Flask-Forms and Flask-Login require that I use CSRF to protect form submissions it is turned on in my API layer as well because my main app and API are running currently on the same instance in my local environment. 

So for every POST/PUT HTTP requests I first need to GET a CSRF token before using it to get JWT and submitting my with CSRF and JWT together with other params. GET requests do not require me to use CSRF but is able to use JWT. 

So my question is...Should we include CSRF when we use flask-jwt-extended as an extra layer of protection when we are authenticating the user? Or is it this bad practice or it doesn't matter?

I'd like to have my api and main app point to the same database using the same sqlalchemy ORM using the an app factory way of creating the app. 

Thanks! Really appreciate the help here.

**Comment by vimalloc** [comment]
If you are doing a POST to login and get a JWT, having CSRF protection there probably does not matter very much. If you want to include it, by all means, but assuming your login endpoint isn't allowing you to do anything else besides login with a username and password, being able to call that endpoint in a cross request forgery way, sending in the cookies that are already set in your application, shouldn't cause any security concerns. If it were me, I would see if I could disable CSRF protection for that one endpoint. Or alternately break the app and api layers out into different blueprints, and see if you could apply the various CSRF protection models only to the blueprints that required them (not sure if that is possible with those extensions or not, but might be worth looking into).

Hope this helps!

**Comment by rlam3** [comment]
@vimalloc 

If I understand you correctly, are you suggesting that I break my main app and API layer into two separate instances using a flask factory pattern? 

Currently, I already have my API layer separated into different blueprints from my main app but just on the same instance where the blueprints from my API and main app are all imported in the same factory pattern. I guess it would make more sense to have a separate instance for the API without it having access to the main app endpoints.  Right? This way I'm able to include exclude/include certain extensions in my API instance. 

Excluding Flask-Login and Flask-WTForms from the main API instance would most likely be the desired way of ridding any remaining CSRF Protections on my POST/PUT endpoints for my API... 

When you are said "POST to login and get a JWT, having CSRF protection doesn't matter..." Does this apply to all POST/PUT requests for the API too? I'm a bit confused here... 

The following is all the API endpoint looks like for my authentication.

```python
@api_v1.route('/auth/',methods=['POST'])
def authenticate():

    """
    Authenicate username and password. If password is authenicated, user object will be returned
    """

    username = request.json.get('username', None)
    password = request.json.get('password', None)

    user = User.get_where(email=username).first()

    # If user exists and password is correct return user
    if user and user.check_password(password):

        # Use create_access_token() and create_refresh_token() to create our
        # access and refresh tokens
        ret = {
            'access_token': create_access_token(identity=username),
            'refresh_token': create_refresh_token(identity=username)
        }
        return jsonify(ret), 200

    return jsonify({"msg": "Bad username or password"}), 401

```

**Comment by vimalloc** [comment]
So, everything kind of depends on how you have your application setup. I'm working on the assumption that you have multiple blueprints for the same flask application. Some of the blueprints are for a more traditional website (server side rendering of html via jina2 and `render_template()`), and some blueprints for the API side using `@jwt_required` and using headers to send in the JWTs to those endpoints. Correct me if I have any of that wrong.

> When you are said "POST to login and get a JWT, having CSRF protection doesn't matter..." Does this apply to all POST/PUT requests for the API too? I'm a bit confused here...

If this is the case, the API blueprints wouldn't need CSRF protection at all, as they are getting the authentication via headers and are not susceptible to CSRF attacks, whereas the transnational side of your website is using cookies (using something like flask-login and flask-WTForms) and thus need to have CSRF protection enabled to prevent attack. If however you passing the JWTs in via cookies, you will need to have a form of CSRF protection for them. You could use WTForms, or the built in CSRF protection built into this application.

I could see two ideal solutions right off hand for this scenario. The first would be to have everything under one flask app, but have the CSRF stuff only applied to the traditional side of the flask app. I'm not sure if it is possible with those extensions or not, but may they support something like ignoring methods/blueprints for CSRF protection, or only applying CSRF protection to certain methods/blueprints (a blacklist or whitelist approach respectively).

If that isn't possible, you could have it be two separate flask apps instead using the factory pattern. This would let you keep everything in the same code base, but run two versions on flask in production. This should almost certainly work, but it may complicate your local or production setup so you would need to keep that in mind.

Cheers!

**Comment by rlam3** [comment]
Thanks so much @vimalloc You are the boss! I ended up seperating my API instance from my main app to have more control over what to include in my API and also exclude any CSRF protection required by Flask-Login/Flask-WTForms
