### ISSUE TITLE
Logout = Missing CSRF token in headers

### ISSUE THREAD

**Issue by n4rk0o** [vimalloc/flask-jwt-extended#96]
Hello,

I successfully implemented the JWT authentication (login and get claims) and I can access to protected resources with only an access token (no refresh token implemented yet).

I would like to implement the logout as mentioned in the documentation but when I try it it returns : 

{
  "msg": "Missing CSRF token in headers"
}

I'm using Flask and Flask-RestPlus so I test it directly on the Swagger UI with the button "Try it out!". I didn't disable the CSRF check and I wonder if I need to do so.

Here is my code:

	   @auth_api.route('/login', methods=['POST'])
	   class login(Resource):
	       @api.expect(login)
	           def post(self):
	               if not request.is_json:
	   	   	   return {"msg": "Missing JSON in request"}

	   	       username = request.json.get('username', None)
	   	       password = request.json.get('password', None)

	   	       if not username:
	   	   	   	   return{"msg": "Missing username parameter"}
	   	       if not password:
	   	   	   	   return {"msg": "Missing password parameter"}
	   	   	  
	   	       try:
	   	   	   	   if get_ldap_info(username,password,'<DN>'):
	   	   	   	   	   access_token = create_access_token(identity=username)
	   	   	   	   	   resp = jsonify({'login': True})
	   	   	   	   	   set_access_cookies(resp, access_token)
	   	   	   	   	   return resp
	   	   	   	   else:
	   	   	   	   	   return {"msg": "User is not authorized to login"}
	   	       except LDAPException as e:
	   	   	   	   return {"msg": "Authentication failure"}

	   @auth_api.route('/logout', methods=['DELETE'])
	   class logout(Resource):
	   	   @jwt_required
	   	   def delete(self):
	   	   	   resp = jsonify({'logout': True})
	   	   	   unset_jwt_cookies(resp)
	   	   	   return resp, 200

**Comment by vimalloc** [comment]
To preform the CSRF protection, you need to include the double submit verification header for any method defined in `JWT_CSRF_METHODS`. By default, these are `POST, PUT, PATCH, and DELETE`. Also by default, the double submit verification token for access tokens will be stored in the `csrf_access_token`, and must be passed in via the `X-CSRF-TOKEN` header on those requests. This is not something that swaggerui knows how to do.

You have a couple options here. You can disable CSRF protection for development, which will allow you to use cookies with swaggerui (assuming they are being severed from the same domain). If you go this route, **make sure** you turn CSRF protection back on in production. Alternately, you could setup this extension to allow JWTs to be sent in via headers, which do not use CSRF protection, and use the 'Authorize' button to set those headers in swaggerui.

Hope this helps.

**Comment by n4rk0o** [comment]
It is more clear, thanks.

My new question is, how can I retrieve the CSRF token to pass it to requests after login?

I am not able to retrieve it for now and I don't wan't to send it as a parameter in SwaggerUI. Is it possible to retrieve it and send it for each requests? (maybe with "get_access_token" call)

In issue [https://github.com/vimalloc/flask-jwt-extended/issues/33](url) you mentionned a call for:

    get_csrf_token_from_jwt(access_token)

Is it implemented?

**Comment by vimalloc** [comment]
Yea, but the name is slightly different. See the very bottom of this page for an example of how to do that: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

**Comment by rlam3** [comment]
@n4rk0o would love to know why you need csrf tokens when using JWT in the first place.

Maybe you can take a look at this https://github.com/vimalloc/flask-jwt-extended/issues/94

However if you must include CSRF_Tokens you can probably include it in the header
https://stackoverflow.com/questions/21357182/csrf-token-necessary-when-using-stateless-sessionless-authentication

https://security.stackexchange.com/questions/170388/do-i-need-csrf-token-if-im-using-bearer-jwt

I've tried implementing CSRF with JWT by making an open get request with CSRF Protect. But calling on the CSRF on every POST/PUT when it is not through a web browser seems excessive when JWT is in place. 

Hope this is of some help.

```
@api_v1.route('/csrf_token/',methods=['GET'])
def get_csrf_token():

    """
    Returns csrf token
    """
    return jsonify(csrf_token=csrf.generate_csrf())
```

**Comment by n4rk0o** [comment]
It is just a suggestion but if I store the data in database, is it not the solution? Ok this is not the best solution because I need to get data every time I do a request but I think this is more easier.

**Comment by vimalloc** [comment]
How you send the token in (cookies vs headers) and using a database are two totally separate issues. You can use a database regardless of how you want to send in the JWTs to the protected endpoints.

**Comment by zero-shubham** [comment]
> Yea, but the name is slightly different. See the very bottom of this page for an example of how to do that: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

I was hunting for this all day, thanks a lot!
