### ISSUE TITLE
Request - utils - check validity of token

### ISSUE THREAD

**Issue by johaven** [vimalloc/flask-jwt-extended#98]
It would be great to have a method to check token validity/expiration in one way.

**Comment by johaven** [comment]
Ok i see how to check expration, from PyJWT docs:

Expiration time is automatically verified in jwt.decode() and raises jwt.ExpiredSignatureError if the expiration time is in the past:
```python
try:
    jwt.decode('JWT_STRING', 'secret', algorithms=['HS256'])
except jwt.ExpiredSignatureError:
    # Signature has expired
```
But a wrapper will be great :)

**Comment by vimalloc** [comment]
The token expiration is checked every time a token is passed to a protected endpoint. If an expired token is passed in, the expired_token_callback is fired off and your endpoint will never be called. The behavior of the expired_token_callback can be modified via this [loader decorator](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.expired_token_loader)

**Comment by vimalloc** [comment]
I'm still not clear on what you are trying to do. Why would you pass in a JWT to an endpoint if you aren't planning on actually verifying the JWT? Why not just have an endpoint that is available to the world and not need a JWT to access it at that point (such as a login endpoint, for example).

If you pass a token into an endpoint that is not protected, flask-jwt-extended won't know anything about that token. It is the view decorator functions (`@jwt_required`, `@jwt_optional`, etc) that look for the token, do the verifications, perform all the callbacks, and store the token in the flask request context.

**Comment by johaven** [comment]
An example will be more obvious, WebDAV mecanism use Basic Auth or Digest Auth, instead of providing a login password i want to pass token as login.

**Comment by rlam3** [comment]
@johaven Are you trying to use an JWT as an API key? This is different from JWT approach I believe. Getting access to your API without proper authentication doesn't seem to be a good idea.

**Comment by johaven** [comment]
I know the approach is different but JWT Token is not so far from a classic token and of course there is an authentication step.
I think the issue can be closed, i had the answers, thx :)
